### ISSUE TITLE
Ctrl+key combination is hard to register

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1001]
I have to be very deliberate when using `Ctrl+key` combinations. Most of the time only the `key` is registered.

**Comment by damithc** [comment]
Experiencing it more with `Ctrl+B` and `Ctrl+R`

**Comment by damithc** [comment]
Definitely a problem in how HT detects key combinations. My Ctrl+B has a 100% success rate in Office applications but less than 50% in HT. It's not a problem with my keyboard or the way I press keys. Anybody else has that problem?

**Comment by HansNewbie** [comment]
I tried with `Ctrl+B` on different focus (on panel, on filter box, on issue) but it works 100%.

**Comment by rd1992** [comment]
Probable cause is the `Ctrl` is released before the modifier key is pressed.

**Comment by HansNewbie** [comment]
Tested on `PanelFocusTest` where I switch the order of releasing `Ctrl` and `F` and the test fails. Seems that `Ctrl` release is indeed the problem.

**Comment by HansNewbie** [comment]
Managed to solve it by changing `KeyEvent.KEY_RELEASED` to `KeyEvent.KEY_PRESSED` for `addEventHandler` in `ListPanel`.

**Comment by damithc** [comment]
Let's do this soon.

**Comment by rd1992** [comment]
@damithc could you switch to bbfe3b65ce2faee522af79af22cc2e60990a6b36 ? and try it for a couple of days and see if this still affects you? Can merge after that

**Comment by damithc** [comment]
If it works for you, proceed with the fix. However, I'm not sure if the fix is done in the right place. It looks like the fix is wider than the reported problem. May be it needs to be wider, i'm not sure.

**Comment by dariusf** [comment]
Another approach could be to bind hotkeys globally, rather than to panels (JavaFX HBoxes, which can only be given focus are programmatically, not by the user). This can remove some duplication.

**Comment by rd1992** [comment]
@damithc the fix is for all shortcuts i agree. I'll it to only for combinations and not for single key presses

**Comment by rd1992** [comment]
@dariusf we cant bind all of the shortcuts globally. especially single key presses.For example, If the user presses something in the filter box then we need that to be typed, not act as a shortcut. Or did i misunderstand you?

**Comment by dariusf** [comment]
I know, I mean combinations which won't interfere with typing, and which are duplicated in a few places. There are probably only a small number of these?

**Comment by rd1992** [comment]
yea. i think barely any left. I'll check for duplicates in the next commit
