### ISSUE TITLE
Filter and sort issues in Logic

### ISSUE THREAD

**Issue by acruis** [HubTurbo/HubTurbo#1004]
Currently, upon a program refresh, `GUIController` requests a refresh in `Logic`, which retrieves data from GitHub and passes it to the `GUIController` without metadata. `GUIController` then filters and sorts issues to retrieve metadata for, which it then sends to `Logic` again, which retrieves more data from GitHub and passes it to the `GUIController`, upon which it will filter and sort the issues again, and then finally display the issues to the user.

Filtering and sorting should be moved to `Logic` instead. In this manner, `GUIController` does not have to worry about managing the flow of execution of the program.

There are multiple implementation design concerns with migrating the filtering and sorting of issues in `Logic`, which are followed by how they are to be dealt with below:
* As `GUIController` does not do filtering and sorting any more, `Logic` should pass the issues to be displayed, for each panel, in the order in which they are to be displayed.
 * Solution: `Logic` attaches issues to be displayed with a filter text string. This works under the assumption that panels with the same filter text will be displayed exactly the same (which is true for the forseeable future)
* Each `ListPanelCard` needs to know if its panel's filter contains an `updated` qualifier so that it can decide when to display metadata for: 
 * Solution: `Logic` attaches a flag signifying whether a filter text string has an `updated` qualifier together with the filter text string, too.
* Currently, <kbd>F5</kbd> / `TickingTimer` / bView refresh event call `ui.logic.refresh()` directly. However, `Logic` needs to get the filter text from the panels.
 * Solution: ~~<kbd>F5</kbd> / `TickingTimer` / bView refresh event will enter the program from `GUIController` instead, which will pass the filter Strings to `Logic` as method call arguments.~~ Expose a method in `GUIController` for the `uiManager` to retrieve filters from panels.

**Comment by dariusf** [comment]
I'm not sure how we can break this down, but if we tried, maybe multiple people could chip in (on the more mechanical bits) and/or we could do it in stages?
