### ISSUE TITLE
Rapid modifying of labels of the same issue during the undo period undoes the previous labels

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1007]
Steps:
1. add labels to issue
2. add/modify labels of same issue during undo window

expected: the 2nd step is cumulative
actual: the 2nd step undoes step 1

**Comment by lejolly** [comment]
It should be cumulative, the way it works now is that if the undo notification pops up again (while a current one is being shown, i.e. still within the first undo window), it immediately sends all previous label changes to github first.

**Comment by damithc** [comment]
It seem to work when I checked now. It didn't work earlier when I posted this issue. However, that might be related to #974 . At that time, the labels added in the first step did not appear on pView either. Let's wait for #974 to be fixed before proceeding with this issue.

**Comment by damithc** [comment]
Noticed again that it is not always cumulative. I added a label and removed it during the undo period. I expected nothing to be sent to the server, but both operations got saved on the server.

**Comment by lejolly** [comment]
noted, this is what i'm trying to solve in #1058. is the proposed implementation there sufficient?

**Comment by damithc** [comment]
OK, let's wait for that to merge. I haven't been following that issue so can't offer any opinion atm.

**Comment by damithc** [comment]
Old issue. closing for now.
