### ISSUE TITLE
Change Ctrl+Key combination from KEY_RELEASED to KEY_PRESSED

### ISSUE THREAD

**Issue by HansNewbie** [HubTurbo/HubTurbo#1015]
Noting down any files that still use KEY_RELEASED.

- PanelControl.setupKeyEvents()

**Comment by rd1992** [comment]
We only use `KEY_PRESSED` for more than one key. This will change the behavior, especially for single keys such as `f` and `d`.

**Comment by damithc** [comment]
When I press the `R` key (and keep it pressed), the focus jumps to comment box and types a string of `r`s. Is that consistent with how we understand the key press behavior? Looks like it's triggered by the key press and not key release? Also, it looks like the OS sends a string of `pressed` events if the key is kept pressed?
