### ISSUE TITLE
User can use aliases to refer to milestones

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1019]
... so that filters containing milestones do not have to change after each milestone.

e.g. `current` `previous` `next` `next+1` and so on. These aliases should be dynamically resolved based on the list of milestones.

**Comment by HansNewbie** [comment]
@damithc last time we agreed that `current` would be the oldest milestone with open issue(s). How about closed milestone with issue(s)?

For e.g. V1.0 due a week ago is closed but it has 1 open issue. and V2.0 due next week is open with open issues. Will V1.0 be `current` even though it is closed?

**Comment by damithc** [comment]
I think we should give higher priority to the status of the milestone. If it is closed, it is no longer current.

**Comment by HansNewbie** [comment]
Another question. For `previous` (I will allow `prev` as well), will it be `previous+1` or `previous-1`? Or just exactly `previous`?

**Comment by damithc** [comment]
`prev-2`, `prev-1`, `prev`, `current`, `next`, `next+1`, `next+2`?

**Comment by HansNewbie** [comment]
Alright.
