### ISSUE TITLE
User can generate a 'milestones' board for a repo

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1030]
... so that the user need not create board manually.

It can be under the 'Borads' menu.
It will generate a board with one panel each for five milestones, name the panels, and save the board.

**Comment by dariusf** [comment]
The five milestones should be the current one + the next four?

**Comment by damithc** [comment]
May be the most recently closed one, current 1, and the next three? By the way, may be this should be done after the support for milestone aliases had been added.

**Comment by damithc** [comment]
Add a `sort:status` to the filters so that open issues appear on top
