### ISSUE TITLE
User can generate a 'work allocation' board automatically

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1031]
... so that user can avoid the work required to create such a board manually.

**Comment by damithc** [comment]
`assignee:john sort:milestone,status`?
If there are many members, may be limit to 5? In a future version we can add a way to choose which members. @HansNewbie

**Comment by HansNewbie** [comment]
Alright. To choose members, maybe I can make something like label picker but for members. Will do it as separate issue.
