### ISSUE TITLE
Users can load related PR using a keyboard shortcut

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1045]
... while the issue is selected in pView, so that user can navigate to the relevant PR easily.

**Comment by codemanmeet** [comment]
It is possible that an issue might be related to multiple pull requests. What do we do then?

**Comment by damithc** [comment]
For now, just show the first one. In future, we can probably pop up a
dialog to choose.

**Comment by rd1992** [comment]
@damithc Github API does not provide any way of doing this also. Just like #1046. Example code to verify this : `curl https://api.github.com/repos/HubTurbo/HubTurbo/issues/1065/events`
So how should we proceed here?

**Comment by rd1992** [comment]
For reference here is the email Github API team sent me:

*No, it's not possible to get that information via the API currently -- the cross-reference links you see in the UI are not exposed via the API. I agree that would be a neat thing to have in the API so I'll pass your feedback to the API team, but I can't make any promises.*

*Wish I had better news, but I don't. Thanks for expressing interest in this, and let us know if you have any other questions.*

**Comment by damithc** [comment]
You can base this feature on mentions.

**Comment by dariusf** [comment]
The other direction is fine, but this is harder because we need to have all PRs to see which mention an issue. @ndt93
