### ISSUE TITLE
User can load the related issue in bView when a PR is selected in pView using shortcut

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1046]
... so that user can easily navigate to the issue being fixed by the PR

**Comment by rd1992** [comment]
@damithc there is currently no way of doing this via the github API. The only we this can be done is checking the PR body if there are mentions of what issue it tackles. This is fine for repos like hubturbo etc but won't work for other repo's where PR's do not mention which issues are fixed for which PR

**Comment by damithc** [comment]
That's fine. It can work only when there is a mention. If there is no mention, there is no way to link an issue to a PR anyway.
