### ISSUE TITLE
Intuitive closing of renaming Panel box

### ISSUE THREAD

**Issue by codemanmeet** [HubTurbo/HubTurbo#1053]
Currently when a user is renaming a panel, the cross sign just next to it is unintuitive in giving an impression of the renaming box being closed while in fact the entire panel would get closed, which can be dangerous. It happened to me the first time I used the renaming panel feature.

![pencil_issue2](https://cloud.githubusercontent.com/assets/4116346/10452745/84191296-71d9-11e5-8877-f3fb2c6c4040.png)

I was thinking of keeping the pencil in its place and using it as a toggle to go back to the non-naming mode (This is in addition to pressing the escape key which also takes you to the non-naming mode). This is shown below - 
![pencil_issue](https://cloud.githubusercontent.com/assets/4116346/10452469/caecd4ca-71d7-11e5-86c0-9d5bc017e0b7.png)

**Comment by dariusf** [comment]
How about removing the cross entirely when the text field takes up the whole space? That way there would be no confusion. I don't think the pencil is particularly intuitive because it doesn't have an alternative toggled state.

**Comment by codemanmeet** [comment]
I am adding an alternative toggle state for the pencil. That way the user can just click again on the pencil to close the renaming box.

**Comment by codemanmeet** [comment]
Correction: By alternative toggle state do you mean like the pencil button appearing differently to indicate that it can be closed? Or do you mean it should be clickable to be used as a toggle? - Click, you go to the renaming mode, click again you go to the non renaming mode.

**Comment by HansNewbie** [comment]
I think he is saying if you are in editing mode, remove all buttons, including both the pencil and the cross. This way user will not be tricked that the cross is to clear the name or to close the panel, at the same time no pencil since putting pencil there would question its function (like toggling the function of the pencil is not so clear).

**Comment by codemanmeet** [comment]
Oh, got it. Thanks.

**Comment by damithc** [comment]
The new UI looks like this. Is it supposed to look like this?
![image](https://cloud.githubusercontent.com/assets/1673303/10564470/0591252c-75e8-11e5-913a-bcaab96f481d.png)

**Comment by damithc** [comment]
Another thing: when I'm in edit mode, there is no button to accept my changes. A user may not realize pressing enter is the only way to get out of edit mode.

**Comment by codemanmeet** [comment]
The first part has been resolved. How do you want the second part to be? Should there be a different 'accept' button? If so, we should have a separate symbol for that. As Darius mentioned earlier, having a pencil to accept changes would still render it unintuitive. What do you recommend?

**Comment by damithc** [comment]
Tick mark for accept?
Should we have something for cancel too? May be some sort of 'go back' symbol?

**Comment by damithc** [comment]
Remember to post screenshots when a change involves UI changes.
