### ISSUE TITLE
milestone missing from some issues

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1054]
This happens for teammates (has a lot of milestones), so it could be a pagination issue
![image](https://cloud.githubusercontent.com/assets/1673303/10473539/368229f6-725f-11e5-8d6f-584c4a048bd3.png)

**Comment by damithc** [comment]
Did not rectify even after refreshing the cache.

**Comment by ndt93** [comment]
Yes, it's a pagination problem.`egit`'s `PageIterator` doesn't download the earlier milestones (before V4.80) for some reason. I will look into this.
