### ISSUE TITLE
Create undo buffer

### ISSUE THREAD

**Issue by lejolly** [HubTurbo/HubTurbo#1058]
Which is basically a queue of size 1. 

When an undo object comes in, it waits there till it times out (then it gets acted on) or is canceled. If before the timeout occurs, and a new undo object comes in, both objects get reconciled and the resulting first object gets acted on, while the resulting second object remains in the queue. 

e.g.
Undo Object 1: +a +b +c
Undo Object 2: -a +d

After reconciliation:
Undo Object 1: +b +c (this gets sent off to github)
Undo Object 2: +d (this remains in the queue)
Undoing an action now, will only remove Undo Object 2, which means only "+d" will be removed. "-a" will not be undone. 

Obviously this needs to be linked up with notification controller which should no longer have any undo logic. 

Should fix #1049.

**Comment by lejolly** [comment]
New scope:
1. No delay
2. No eager update
3. Notification for 30 sec

**Comment by damithc** [comment]
3. Why not keep the notification till it is replaced by the subsequent one?

**Comment by lejolly** [comment]
I think it's dangerous to keep it around for too long as the data it holds might get stale if someone else is editing the same issue.

**Comment by damithc** [comment]
That's true. However, stale data is a problem no matter what the duration is, so there should be proper error handling. Once we have proper error handling, might as well keep it open as long as we need, right?

**Comment by lejolly** [comment]
so far the only error handling we're doing is to check if the action to replace labels is successful, what other kind of error handling are you thinking of?

**Comment by damithc** [comment]
Yes, that's enough. Just check if it was successful and give an error message if it wasn't.
