### ISSUE TITLE
Model is deleted when repo letter casing is wrong

### ISSUE THREAD

**Issue by HansNewbie** [HubTurbo/HubTurbo#1060]
e.g. default repo is `TEAMMATES/repo` and filter is `(repo:TEAMMATES/repo || repo:hubturbo/hubturbo)`. Everytime something is added to the filter, the model of HubTurbo will be deleted and reloaded.

Will cause same issue with #1056, except that the only blank issues would be HubTurbo's issue and TEAMMATES's issue would show up just fine.

**Comment by dariusf** [comment]
Not sure if this is the right issue to fix this, but I think the deeper problem is that we represent repo ids with raw strings instead of some value object (which would maintain invariants and compare repo ids modulo case).

**Comment by HansNewbie** [comment]
Can we open a new issue for representing repo as some value object? I can make a quick fix for this issue at least to ensure the application is not broken.

**Comment by damithc** [comment]
@HansNewbie My powerpointlabs repo is downloaded every time I start HT. Is that a result of this bug?

**Comment by HansNewbie** [comment]
I don't think so. This bug only deletes the model but not the JSON, and redownloading means the JSON is not present. It might be related to the problem that we represent repo as raw string, but not because of the model deletion. I will confirm this again.

**Comment by HansNewbie** [comment]
@damithc it is not related to this bug. I tried removing the codes for deleting models but it (#1065) still happens.
