### ISSUE TITLE
Create keyboard shortcuts for swapping panels

### ISSUE THREAD

**Issue by HyungJon** [HubTurbo/HubTurbo#1062]
The function to swap panels using the mouse is rather blocky. Takes some tries to get it right, and it is especially troublesome for testing. ```PanelsTest``` has a part where panels are supposed to be swapped, but they don't get swapped, at least much of the time.

Therefore adding keyboard shortcuts to swap the currently selected panel with the left/right panel would be helpful. Would not be activated if there is <2 panel, and will have to wrap to the other side if it swaps to the left when it's the leftmost panel and vice versa.

What ```KeyCodeCombination``` would be appropriate?

**Comment by damithc** [comment]
`Ctrl`+`Shift`+`left/right` ?
