### ISSUE TITLE
Some repos not saved as json files

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1065]
I have powerpointlabs/powerpointlabs as a repo in my filters. Turns out it is never saved to the hard disk. Everytime I start HT, the repo is downloaded again.

**Comment by HansNewbie** [comment]
Happened to me as well. The repo JSON is not written.

**Comment by damithc** [comment]
I removed another repo using the 'remove repo' feature. The json file got deleted. Now that repo is also downloaded everytime and never saved. So it seems if a json file got removed from hard disk, it is never created again.

**Comment by HansNewbie** [comment]
Yes. I am checking which commit introduced this.

**Comment by HansNewbie** [comment]
Introduced in the commit 6eb63f8364a8c5251bc814126c612fb6326df16e on `[1054] milestone missing from some issues`.

**Comment by HansNewbie** [comment]
Comparison of log where things differ:
Log where repo is saved:
```
UpdateModelTask [pool-4-thread-2] - HansNewbie/coral-repo | Updated model with 31 issue(s), 17 label(s), 0 milestone(s), 0 user(s)
WriteTask [pool-5-thread-1] - HansNewbie/coral-repo | Written to JSON store
```

Log where repo is not saved
```
UpdateModelTask [pool-4-thread-1] - HansNewbie/coral-repo | Updated model with 31 issue(s), 17 label(s), 0 milestone(s), 0 user(s)
RepoIO [pool-4-thread-1] - HansNewbie/coral-repo | Nothing changed; not writing to store
```

Based on the log, the line `if (!model.equals(newModel))` in RepoIO fails. But nothing in the commit seems to cause this.
