### ISSUE TITLE
Show closed issues in a different fill color

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1068]
e.g. change the fill color of closed issues into a light shade of green. That way, a panel sorted by status will look like a container filling up (like a vertical progress bar). This will make the 'milestones' board look nice.

**Comment by codemanmeet** [comment]
Just to understand, so instead of adding a strikethrough across the name of the issue, you want the color to change to a light shade of green? or are you looking for both, the light green color and the strikethrough?

**Comment by damithc** [comment]
We can use both. We should not depend on color alone as some users may be color blind.
