### ISSUE TITLE
Warn users who don't have all dependencies

### ISSUE THREAD

**Issue by dariusf** [HubTurbo/HubTurbo#1082]
A dialog should open on startup to warn users (and/or give the option to exit) if they don't have all the dependencies. This can be implemented in the updater.

- JRE 1.8.0_40
- Chrome: warn those who don't have it installed, and those who have an outdated version (unlikely, also do we need a specific version?)

**Comment by dariusf** [comment]
We may actually need 1.8.0_60, because we're depending on ControlsFX 8.40.10, which is expressly for that version (it uses private JavaFX APIs, which is fragile and forces us to be up to date as well).

**Comment by HansNewbie** [comment]
Changed to check Java version only since browser might change.
