### ISSUE TITLE
Open issues is coloured green after some clicking

### ISSUE THREAD

**Issue by HansNewbie** [HubTurbo/HubTurbo#1088]
![screen shot 2015-10-24 at 5 29 06 pm](https://cloud.githubusercontent.com/assets/3381536/10709973/dfd85ce2-7a74-11e5-96b5-9ed492921822.png)

Not sure if it only happens to me. If I click on some issues, the green colouring is messed up, at least when you start scrolling up and down.

**Comment by damithc** [comment]
Happens to me too. Just scrolling will make open issues become green.

**Comment by codemanmeet** [comment]
I figured the [problem](http://stackoverflow.com/posts/32696440/revisions).
