### ISSUE TITLE
Replace manual menu navigation in tests with clickMenu()

### ISSUE THREAD

**Issue by HansNewbie** [HubTurbo/HubTurbo#1094]
Menu tests that use `push(KeyCode.DOWN)` to traverse the menu manually should be replaced with `clickMenu(String... menuNames)` as menu manual traversal will fail in the future if the menu is rearranged.

**Comment by dariusf** [comment]
I brought this up before, and I believe the problem back then was that searching for menu nodes by text didn't work on Travis. Maybe it was a synchronisation problem and the new methods added since will solve it?

**Comment by HansNewbie** [comment]
Seems to work fine now. Maybe because the cases that are using it now have no synchronisation issues.
