### ISSUE TITLE
hub turbo does not update automatically

### ISSUE THREAD

**Issue by madsonic** [HubTurbo/HubTurbo#1096]
version is still at 3.8.0. does not download the latest version after hubturbo is launched

**Comment by damithc** [comment]
@HansNewbie could you follow up?
@madsonic is using a Mac. @madsonic what is the exact java version you are using?

**Comment by HansNewbie** [comment]
@madsonic do you see the following java icon in your dock? If you click on that Java icon, nothing will show up.

![HT AutoUpdater](https://cloud.githubusercontent.com/assets/3381536/10781497/929fbbe4-7d82-11e5-94e4-bd8447038ad5.png)

**Comment by madsonic** [comment]
@HansNewbie I'm using java 8 update 60. i have the icon in my dock, it brings hubturbo to the front when clicked

**Comment by damithc** [comment]
Closing as no longer applicable.
