### ISSUE TITLE
Updater is blocking use of HT

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1100]
I noticed one student had the updater blocking the use of HT until the new version is downloaded. Student said it was not the case in previous weeks. The java version was fine and HT was in a separate folder.

**Comment by HansNewbie** [comment]
Happened to me just now as well. The thing is, there is no change at all to the updater.

**Comment by damithc** [comment]
It could have been broken from the beginning. It doesn't happen all the time though.
