### ISSUE TITLE
Issues don't grey out when marked as 'read'

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1105]
I marked all these three as read, but they look like not read.
![image](https://cloud.githubusercontent.com/assets/1673303/10867976/f1e0a2be-80b9-11e5-9a0b-b6c7dca8b954.png)

**Comment by damithc** [comment]
@rd1992 is this something to do with `g,e` shortcut? We use `e` to mark as read.

**Comment by rd1992** [comment]
I just tested this and it works. Pressing `e` on an issue greyed it out for me. Context menu also changed to marked as unread

**Comment by damithc** [comment]
Seems it works for issues but not PRs.

**Comment by rd1992** [comment]
No i tried with a PR also and it works. Might have to do something with the `updated` filter.

**Comment by damithc** [comment]
It used to work until I noticed a few hours ago. Even a restart didn't fix it. I didn't change any of the filters.

**Comment by damithc** [comment]
Actually, it worked for PRs as well. It's some specific issues. Try 4547 from teammates project or 1103 from hubturbo projects.

**Comment by rd1992** [comment]
Hmm. This might not just be a shortcut issue. Could you answer the following? 
1. Are you running HT from master? 
2. Can you mark the PR as read by right clicking on the PR and selecting the `mark as read` option?
3. Is the behaviour only seen in panels with `updated` filter?

You could also post your log. @ndt93 you might want to take a look at this also.

**Comment by damithc** [comment]
1. yes
2. For those issues, no I cannot.
3. For those issues, no I cannot.

**Comment by damithc** [comment]
Log file uploaded to slack

**Comment by rd1992** [comment]
Yeah i tried the issues mentioned and it does seem that for those specific issues your `markAsRead()` does not work. @ndt93 any thoughts?

**Comment by ndt93** [comment]
I've looked at the log, it reports that there are some review comments and commits changes in those PRs (hubturbo 1103 and teammates 4547) in several update cycles near the end. So either that's the bug there or there are in fact some changes to the PRs.

I just try to mark as read those PRs on my side and it works ok with the latest master.

**Comment by damithc** [comment]
Yup, they are working now. It was a temporary problem. Closing.
