### ISSUE TITLE
BoardSwitchTest uses real preferences and not test preferences

### ISSUE THREAD

**Issue by HansNewbie** [HubTurbo/HubTurbo#1111]
Should be a quick fix; change all `testPrefs = new Preferences(false);` to `testPrefs = new Preferences(true);`.

Discovery: test suddenly fails in Mac after auto-creating work allocation boards. Log shows that it is referencing some work allocation board name instead of the testing board name.

**Comment by nicholaslum444** [comment]
I'll attempt this. Will be opening a PR for discussion

**Comment by HansNewbie** [comment]
@nicholaslum444 remember to choose the milestone and assign yourself on the right for next issues :)
