### ISSUE TITLE
Integrate Mockito

### ISSUE THREAD

**Issue by ndt93** [HubTurbo/HubTurbo#1133]
http://mockito.org/

*Mockito* can be used to mock behaviors of classes which are not targets for a test case but are needed by classes under test. This is a step to work towards eliminating special variables for testing and manually constructed dummy classes.

**Comment by acruis** [comment]
Is the code from the mocked classes covered in the tests? i.e. are they run in the tests?

**Comment by ndt93** [comment]
They shouldn't be covered (i.e. the code from the original classes which are being mocked), unless parts of their code are called in their mocked versions. We can create separate test cases that focus on those classes to cover them or they shouldn't be mocked if they have to be covered together with other classes under tests.

**Comment by ndt93** [comment]
I was reading up a bit more. There is a feature in *mockito* called *spy* which can mock some methods and use other methods from the original classes. There are a quite a number of other features also including some verification methods. Probably needs exploring some more.
