### ISSUE TITLE
Panel menu options for auto-creating custom panels (assignee, milestone, updated)

### ISSUE THREAD

**Issue by codemanmeet** [HubTurbo/HubTurbo#1136]
The panel filters would be `is:open assignee:me` and `is:open updated:<24` respectively. The panel would be created on the right. @damithc Are the filters ok? Let me know!

**Comment by damithc** [comment]
No need for `is:open`

**Comment by codemanmeet** [comment]
Sure! Let's do <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>A</kbd> for assignee and <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>U</kbd> for the last updated issues?

**Comment by damithc** [comment]
hang on, we don't need keyboard shortcuts for this. This is not an action to be used frequently. Just a menu item would do.

**Comment by codemanmeet** [comment]
Sure, will include it in the Panels menu.

**Comment by damithc** [comment]
Here are some panel shortcuts I can think of:
My open issues: `is:open assignee:me`
Recent updates to my issues: `assignee:me updated:<48`
Current milestone: `...`
Any more?

**Comment by codemanmeet** [comment]
I was wondering whether we could have a panel shortcut for `PR's authored by me` to track its review- 
`is:pr author:me`

**Comment by damithc** [comment]
Perhaps add PRs to existing panels instead? e.g.
My open issues: `is:open ((is:issue assignee:me) OR (is:pr author:me))`
It is unlikely one person will have many issues and PRs at the same time to warrant two separate panels.

**Comment by codemanmeet** [comment]
Sure, this sounds better! I'll go ahead with this.
