### ISSUE TITLE
Add a 'new' option for the 'Boards' menu

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1142]
This option is for creating an empty board. We can prompt for a board name before creating it.

**Comment by zhongwei-z** [comment]
I was trying to implement this. I am not sure if my approach is correct. As I see in the board auto creator, the creation is done by closing all current panels and adding in new ones. I suppose to create an empty board we do the same except that no panels are added. However, in the method to do a "Save As", there is a check for currently opened panels so it won't save an empty board. So I think there is a conflict of logic. We want to create an empty board but we do not allow to save an empty board?
