### ISSUE TITLE
Users can use aliases for qualifiers

### ISSUE THREAD

**Issue by codemanmeet** [HubTurbo/HubTurbo#1145]
`milestone` : `m`
`status` : `s`

@damithc any more that we could include?

**Comment by damithc** [comment]
Go through the entire list and find which one are suitable. At the same time, see much work it takes to define shortcuts and whether there are any performance costs.

**Comment by damithc** [comment]
Manmeet, when implementing, may be implement just a few first? I want to see how difficult the change is. If the it is not that difficult, we can crowdsource the rest as beginner issues. We are short of them anyway.

**Comment by codemanmeet** [comment]
Sure Prof. let's do that. I'll implement the following as of now - 

`milestone` : `m`
`status` : `s`
`author` : `au`
`assignee` : `as`

The rest for sort, user, type, body can be crowdsourced as beginner issues.
