### ISSUE TITLE
If there is only one open milestone, consider it as the current milestone

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1147]
If there is only one milestone open, it can be considered the `current` milestone even if it doesn't have a date assigned to it. i.e.alias `curr` should resolve to that milestone

**Comment by damithc** [comment]
@HansNewbie is this suitable for firsttimers?

**Comment by HansNewbie** [comment]
If I point which method to be changed, I think yes. Might take some time
for them to understand why and how it works, but can get them to understand
our workflow, especially on writing tests, and the software design (since
this involve Filter and backend on milestones).

**Comment by damithc** [comment]
@HansNewbie may be mention which class/method needs changing?

**Comment by HansNewbie** [comment]
The method to be changed is `Qualifier.replaceMilestoneAliases()`. `Qualifier.getCurrentMilestoneIndex()` should also be looked into.

The tests that may need to be changed or added would be `tests.MilestoneAliasTests`.

`guiTest.FilterTest.milestoneAliasFilterTest()` may need to be changed but it needs to wait for Mockito when we can change the dummy repo comfortably.

**Comment by raisfathin** [comment]
In that case, do we consider other aliases (for example: curr-1) invalid?

**Comment by HansNewbie** [comment]
I believe `curr-1` should be the previous milestone that was just closed.
Milestones are sorted by deadlines.
