### ISSUE TITLE
Aliases for qualifiers - sort, type, body, title

### ISSUE THREAD

**Issue by codemanmeet** [HubTurbo/HubTurbo#1151]
Alias for `sort` could be `so`. Aliases for the other qualifiers can be discussed!

**Comment by damithc** [comment]
This issue is not ready for first timers until your PR is merged.
Define all the abbreviations first. Defining them should be done in one shot while implementation can be done one at a time.

**Comment by dariusf** [comment]
This should be doable by first-timers now.

**Comment by damithc** [comment]
Shall we do one as an example?

**Comment by dariusf** [comment]
It would involve adding a line [here](https://github.com/HubTurbo/HubTurbo/blob/master/src/main/java/filter/expression/QualifierType.java#L30), and below in the completions method if the alias is too short to complete. After that it's just tests and docs.

**Comment by jinified** [comment]
How about these abbreviations ? 

so -> `sort`
ty -> `type`
tl -> `title`

**Comment by damithc** [comment]
I think we should decide abbreviations in one go, not in piecemeal fashion. The implementation can be done one by one though. Perhaps you can list all the keywords here and propose abbreviations for frequently used ones? Note that the more frequently used ones can be given one letter abbreviations while others can be given 2 letter ones.

**Comment by jinified** [comment]
Here are the list of keywords without any abbreviations assigned:

- CREATED -> `cr`
- COUNT -> `cnt`
- DATE -> `d`
- REPO -> `rp`
- SORT -> `so`
- TITLE -> `t`
- UPDATED -> `u`
- LABEL -> `l`
- LABELS -> `ls`
- MILESTONES -> `ms`
- TYPE -> `ty`

I believe some of the qualifiers like `NO`, `IS` and `HAS` do need any aliases right ?

**Comment by damithc** [comment]
The purpose of the abbreviation is to minimize typing, so yes, even things like `has` can have abbreviations. Can you give full list including the ones that are assigned already. We can change existing ones if needed.

**Comment by jinified** [comment]
| Qualifier   | Aliases                   |
|-------------|---------------------------|
| ASSIGNEE    | "as"                      |
| AUTHOR      | "au", "creator"           |
| CREATED     | "cr"                      |
| COUNT       | "cnt"                     |
| DATE        | "d"                       |
| DESCRIPTION | "body", "desc"            |
| HAS         | "h"                       |
| ID          |                           |
| IN          | "within", "include"       |
| INVOLVES    | "user"                    |
| IS          |                           |
| LABEL       | "l"                       |
| LABELS      | "ls"                      |
| MILESTONE   | "m"                       |
| MILESTONES  | "ms"                      |
| NO          | "not"                     |
| REPO        | "rp"                      |
| SORT        | "so"                      |
| STATE       | "s", "status"             |
| TITLE       | "t", "head"               |
| TYPE        | "ty"                      |
| UPDATED     | "u", "amended", "revised" |

Here is the full list of qualifiers with assigned aliases. I can't really think of any suitable aliases for `ID` and `IS` at the moment

**Comment by damithc** [comment]
Give the full list (existing + proposed). May be add 'proposed' as the 3rd column? You may also want to investigate what aliases are there in the GitHub's own filter syntax. We want to follow those where possible. @dariusf FYI
BTW, this issue might take a while. I'm removing the 'first timer' label. You can attempt a different first timer issue while continuing to work on.

**Comment by jinified** [comment]
@damithc @dariusf  any comments on the updated list of aliases above.

**Comment by damithc** [comment]
Sorry, didn't realize you updated the comment (there are no email alerts for updated to comments).
No need to introduce longer aliases. Our objective is to reduce typing. So the aliases should not be longer than 2 chars.
`repo` can have the alias `r`?
`is` is used frequently, so assign `i` for it?
Move the table to the first comment, update it as suggested above, and add a comment to let us know it is ready for review again.

**Comment by jinified** [comment]
updated and ready for review

**Comment by damithc** [comment]
No need for `head`
count and description don't have 1-2 letter versions.

**Comment by jinified** [comment]
Done. And should I remove the existing alias with more than 2 chars ?

**Comment by damithc** [comment]
Leave them for now. I think some of them are there to be compatible with GitHub syntax.
Because `status:open` is same as `i:open`, we can use `st` for `status` and `s` for `sort`.
Are you going to implement all aliases in this PR? alternatively, you can break it into several issues and do only one of them.
BTW, I think we missed keywords such as 'open' 'closed' etc. Can you add them too?

**Comment by jinified** [comment]
I did not include  `open` and `closed` because they are not QualifierType and are matched just as string. But we can definitely create an alias for these keywords, maybe in a separate issue ?

**Comment by damithc** [comment]
Yes, can be implemented as separate issues, but we have to decide all the aliases in one go, to ensure we have a global optimum for aliases. For example, I think `c` should be assigned to `closed`, not `created`, as `closed` is used more frequently and deserves the shortest alias.

**Comment by jinified** [comment]
What about using "x" for closed instead of "c" ? It feels more intuitive for me if we are using 
"o" for `open`.

**Comment by damithc** [comment]
We use the first letter everywhere else, so better to follow the same here.

**Comment by jinified** [comment]
ok updated the table already. Is everyone agreeable with the proposed aliases ?

**Comment by damithc** [comment]
Didn't I say `sort` should be `s`?
Sure you covered all the keywords?

**Comment by jinified** [comment]
Was really confused between the keywords and qualifiers. I decided to separate them into two separate tables. I believe the table covers every keywords mention in the `filter` doc. Can any of the senior devs help check if I miss anything.

**Comment by damithc** [comment]
So what happened to `open`, `close` etc.? I don't see them anywhere now. By 'keywords' I meant any predefined words used in filters, qualifiers included. As you know, we are trying to reduce typing.
It shouldn't be too hard to go through the documentation to find all the keywords mentioned in there.

**Comment by jinified** [comment]
It is in the second table below the main one where I group all the keywords together. The second and third row.

**Comment by damithc** [comment]
OK, I can see the 2nd table now. There was an update delay.
Seems like we don't have an alias for `issue`. How about we take `i` from `is` and give it to `issue`. `is` is short enough and no other 2-letter keyword has an abbreviation.

**Comment by damithc** [comment]
BTW, are you able to edit the first comment? If you can, move the tables to the first comment.

**Comment by jinified** [comment]
Unfortunately I am unable to edit the first comment. Two other keywords that can be aliased with one char: 
- `pr` -> "p" 
- `no` -> "n"

**Comment by damithc** [comment]
I'm fine with the current list. @dariusf any further comments?

**Comment by dariusf** [comment]
'labels' and 'milestones' are not qualifiers.

'assignee' is both a qualifier and a keyword that can appear on the RHS of the `:`.

I don't think we need different aliases for the plural forms of these. The plural forms are themselves aliases and are mainly for readability. For example, `has:label` and `has:labels` mean the same thing.

Apart from that it looks good.

**Comment by jinified** [comment]
Ok I will work on it then
