### ISSUE TITLE
Refactor keywords in the Qualifier class.

### ISSUE THREAD

**Issue by codemanmeet** [HubTurbo/HubTurbo#1152]
As discussed in #1150, keywords need to be refactored in order to avoid duplication in `Qualifier.java`.

**Comment by codemanmeet** [comment]
Each string literal appears twice in this class. We can remove that duplication. e.g.
1. define an enumeration for all key words e.g. KEYWORDS={ASSIGNEE, AUTHOR, ...}
2. create a hasmap where the key is the string literal and the value is the enumeration value
3. during parsing, retrieve the enumeration value using the string literal and do the switch based on the enum value.

**Comment by dariusf** [comment]
To provide a specific example of what the change should look like, right now we have code like this in a number of places.

```java
switch (name) {
    case "author":
    case "creator":
    case "au":
        return authorSatisfies(issue);
}
```

When we replace the strings with enum values, we should be able to do
```java
switch (name) {
    case AUTHOR:
        return authorSatisfies(issue);
}
```
with a way to normalise "au" and "creator" to `AUTHOR`.

**Comment by codemanmeet** [comment]
Yup! would make it neater and remove duplication!

**Comment by damithc** [comment]
Can someone do this soon? We need this before we can get contributors to implement the other aliases.

**Comment by codemanmeet** [comment]
Would be out on vacation tonight onwards. Wouldn't be able to take this up :(

**Comment by dariusf** [comment]
I can do this later.
