### ISSUE TITLE
Eclipse and Gradle setup

### ISSUE THREAD

**Issue by dariusf** [HubTurbo/HubTurbo#1154]
Our Gradle setup involves a nested source set (#1025, #1040). Eclipse's Gradle integration doesn't like this, and as a result we can't get the project to build in Eclipse. There are a few options.

- Change the default IDE to IntelliJ
- Create an Eclipse project completely separate from Gradle (that is, don't import the Gradle setup when creating the project), use that for development, and access Gradle (for running unstable tests, building jars, etc.) using the CLI. @HyungJon @nicholaslum444 maybe you guys could try this?
- Come up with a more elegant solution for running different sets of tests. I don't think this is trivial and requires a deeper understanding of Gradle than just reading the user guide.

Any other ideas?

**Comment by damithc** [comment]
I don't mind make IntelliJ the preferred IDE if that is the easiest option. @ndt93 is there an IntelliJ version for Linux?

**Comment by ndt93** [comment]
@damithc Yes, there is.

**Comment by damithc** [comment]
In that case let's make IntelliJ *the* IDE. Supporting 2 IDEs seems like an unnecessary overhead. Any downsides?
