### ISSUE TITLE
Reorganize dev docs for better logical progression

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1164]
How about this? {Only the bold ones separate documents. non-bold ones are sub sections within that document}

* **Vision** {why it is a desktop app, target audience, etc.}

* **Setting up**  
  * Install prerequisites
  * Check out code
  * Build

* **Development process** {structure similar to [TEAMMATES process documentation](https://github.com/TEAMMATES/repo/blob/master/devdocs/process.md)}
 * Background knowledge
  * **Submitting a PR** <br>
    Roles: contributor/developer <br>
    {Give sufficient details building, testing, code coverage, style violations, etc. here. but can refer to other documents for further details}
  * **Reviewing a PR**<br>
    Roles: reviewer
  * **Merging a PR**<br>
    Roles: developer
  * **Releasing a new version**<br>
    Roles: team lead

* **Tool stack** 
   * IDE: Intellij
   * Core tech: Java, JavaFX, Selenium, etc.
   * Testing: ...
   * CI: 
   * Code coverage:
   * Static analysis: 

* **Design**

* **Testing**

* **Coding guidelines**
  * Java coding standard
  * Use of optional
  * Immutability
  * Thread safety
  * ...

* **Troubleshooting** 
   * set up
   * CI
   * testing

* **Useful resources**

**Comment by dariusf** [comment]
Sounds good. Vision probably needs a proper writeup.

Are the bold items in 'development process' separate documents?

**Comment by damithc** [comment]
Vision doc can be omitted in the first round. I'll add it at some point.
Having development process in one doc is ideal but could be too long to put in one doc, in which case the bold one can be created as separate docs.

**Comment by damithc** [comment]
Can do soon? New contributors are going to start from tomorrow.

**Comment by dariusf** [comment]
I'm working on it, will probably finish tomorrow.
