### ISSUE TITLE
Unexpected inputs should trigger parse exceptions instead of failing silently

### ISSUE THREAD

**Issue by dariusf** [HubTurbo/HubTurbo#1174]
All qualifiers should be changed to throw exceptions on unexpected conditions instead of returning `EMPTY`. `EMPTY` is what is defaulted to *upon* an exception, and should not be used directly as much as possible.

**Comment by jinified** [comment]
Only need to change the `parse` method in`Parser.java` right to throw ParseException when the input is null or empty.

**Comment by dariusf** [comment]
There are quite a few other places to change. For example, `id` [expects a number or number range](https://github.com/HubTurbo/HubTurbo/blob/9939cd94b136c9ae738bda619009a98e94df7e85/src/main/java/filter/expression/Qualifier.java#L619), and otherwise shows nothing (if given a string, date, etc.). Instead of this, we want an exception to be thrown so the user sees an error message, and so on, for all qualifiers.

It's quite mechanical, but the changes aren't really localised, so in that sense this might not be an easy issue.

**Comment by jinified** [comment]
From what  I understand, I just need to make sure all methods in [isSatisfiedBy](https://github.com/HubTurbo/HubTurbo/blob/master/src/main/java/filter/expression/Qualifier.java#L203-L251) throw ParseException whenever an invalid input is given. Here is an example after adding exception to `idSatisfies`.

![idsatisfies](https://cloud.githubusercontent.com/assets/3635970/12396723/e6538980-be43-11e5-85a7-6596abeee466.png)

**Comment by dariusf** [comment]
Okay, that's a good start. There are a few other methods for the special qualifiers (`sort`, `repo`, `count`, `in`, etc.) which aren't found in `isSatisfiedBy`, but those can be done in separate issues.

It might be a good idea to create a SemanticException type for these, since invalid but well-formed inputs shouldn't be considered parse errors. It and ParseException can be a subclasses of FilterException, and the latter can be the one that's caught when we show that error message.

**Comment by jinified** [comment]
That is a good idea. I think it also useful to catch the SemanticException and display it as feedback to user. (maybe not as error but suggestion to user)

**Comment by jinified** [comment]
TODO
- [ ] create FilterException to be subclassed by ParseException and SemanticException
- [ ] change [applyStringFilter](https://github.com/HubTurbo/HubTurbo/blob/master/src/main/java/ui/issuepanel/FilterPanel.java#L177) to catch FilterException instead
- [ ] make sure all methods in [isSatisfiedBy](https://github.com/HubTurbo/HubTurbo/blob/master/src/main/java/filter/expression/Qualifier.java#L203-L251) throw `SemanticException`
