### ISSUE TITLE
Fix KeyboardShortcutTest running on small screens

### ISSUE THREAD

**Issue by m133225** [HubTurbo/HubTurbo#1181]
KeyboardShortcutTest fails when it tries to click the last issue, which cannot be seen in the panel

**Comment by dariusf** [comment]
We might have to scroll the issue card into view before trying to click it.

**Comment by xinan** [comment]
However, `KeyboardShortcutTest` clicks the last issue but hitting the `END` key instead of using the cursor. (As this test is testing for all the keyboard shortcuts) Guess the problem is not that the issue is not in view, it is that the key is not working.
