### ISSUE TITLE
GUI test resources not found for unstable tests when running `gradlew clean check`

### ISSUE THREAD

**Issue by xinan** [HubTurbo/HubTurbo#1185]
Encountered `NullPointerException` for `repositorySelectorTest` when running `gradlew clean check`. 

It seems that running the `check` task is different from running the `unstableTests` task, as it does not setup the test resources for the unstable tests. (As in, copy the `resources/guitests` to `resources/unstable`). 

Creating a soft link from `guitest` to `unstable` does the trick. But I'm not sure whether it works on Windows.

**Comment by ndt93** [comment]
This is a duplication of #1146.

**Comment by xinan** [comment]
Oh sorry I was searching for open issues but couldn't find anything related. 

Anyway I seem to found a way to fix this.

**Comment by ndt93** [comment]
No problem :-). That's just to let you know an existing issue in case you can find any useful info.
