### ISSUE TITLE
Ctrl+B doesn't work when the open board is deleted

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1198]
`Ctrl+B` stops switching boards when the currently open board is deleted.

**Comment by garbanzos** [comment]
@damithc When the currently open board is deleted and `Ctrl+B` is pressed, which board should I switch to? 

For example, I may have boards
- board1 
- board2 
- board3 
- board4

When I delete board2, should I switch to the first board (board1) or to the board right after the deleted board (board3).

**Comment by xinan** [comment]
I have to change something for #1199 and as a side effect, it will fix this issue. So I will assign myself for now.
