### ISSUE TITLE
Travis and Coveralls badges are not displaying

### ISSUE THREAD

**Issue by xinan** [HubTurbo/HubTurbo#1202]
Seems that there are some problems with `shields.io`. 

![screen shot 2016-01-22 at 00 58 37](https://cloud.githubusercontent.com/assets/2834397/12487794/b5e9b988-c0a3-11e5-9b23-a580663f105c.png)

Since Travis and Coveralls now both host the badge image their own. 

[![Build Status](https://travis-ci.org/HubTurbo/HubTurbo.svg?branch=master)](https://travis-ci.org/HubTurbo/HubTurbo) [![Coverage Status](https://coveralls.io/repos/github/HubTurbo/HubTurbo/badge.svg?branch=master)](https://coveralls.io/github/HubTurbo/HubTurbo?branch=master)

Shall we switch to these instead of using `shields.io`?

**Comment by dariusf** [comment]
Sure. The Coveralls version does look a bit nicer.

**Comment by yl-coder** [comment]
Hi, i think this was fixed?

**Comment by dariusf** [comment]
The badges link to Travis/Coveralls, but still use images from shields.io. It's more apparent from the [raw](https://raw.githubusercontent.com/HubTurbo/HubTurbo/master/readme.md) contents of the file.
