### ISSUE TITLE
LabelPickerTests waits infinitely for the notification to hide

### ISSUE THREAD

**Issue by m133225** [HubTurbo/HubTurbo#1206]
More specifically, addAndRemoveLabelTest waits infinitely for the notification to hide after making changes to dummy issue 9.
This is probably due to the latest changes, test should be updated.

**Comment by damithc** [comment]
Does this affect travis or just local testing?

**Comment by m133225** [comment]
Local testing, since it is under 'unstable', so there is no immediate need to fix it yet.

**Comment by dariusf** [comment]
Unstable tests don't run on Travis, but they do help prevent regressions. We should fix this soon.

**Comment by m133225** [comment]
I think this problem is no longer there since #1232 has removed the problematic test completely.
