### ISSUE TITLE
Auto-create sample board menu option

### ISSUE THREAD

**Issue by codemanmeet** [HubTurbo/HubTurbo#1211]
This auto-create option would generate 3 panels with filters that correspond to the sample repo that is created within the `HubTurbo` repository.

**Comment by dariusf** [comment]
Do you need the sample repo created within the organisation? What should it be called, etc.?

Also, is this an auto-create menu item or just something that appears the first time for new users? I thought it would the second one.

**Comment by codemanmeet** [comment]
This is just an auto create menu item. The other one will be taken care of in a separate issue, where first time users would be able to view the sample board on startup of the app. 

Let's create the sample repo within the organization. Let's call it `SampleRepo`.

**Comment by dariusf** [comment]
Okay. Created the new repo.

**Comment by codemanmeet** [comment]
Thanks!

**Comment by codemanmeet** [comment]
1. `Issues with labels but no milestones and ID>5` -> `repo:HubTurbo/SampleRepo has:label NOT(has:milestones) id:>5`.

2. `Open issues in my two sample repos` -> `(repo:HubTurbo/SampleRepo OR repo:HubTurbo/HubTurbo) is: issue is:open sort:comments,updated`. @dariusf This would require the creation of two sample repos. If not possible, we can use `HubTurbo/HubTurbo` as the second repo to demonstrate multiple repository search!

3. `Issues assigned to Darius not closed in V4 or V5` -> `repo:HubTurbo/SampleRepo as:dariusf NOT(state:closed) (milestone:V5 OR milestone:V4)`. 

4. `Open Issues in the current milestone` -> `repo:HubTurbo/SampleRepo milestone:current is:issue is:open`

5. `Issues updated between 2 Feb to 3 Feb 2016` -> `repo:HubTurbo/SampleRepo updated:2016-02-02 .. 2016-02-03 is:issue`

6. `Unmerged PR's` -> `repo:HubTurbo/SampleRepo is:unmerged is:pr`

7. `Open issues assigned to Darius or Manmeet` ->  `repo:HubTurbo/SampleRepo is:issue is:open (as:dariusf || as:codemanmeet)`

8. `Issues that contain the term "UI"` -> `repo:HubTurbo/SampleRepo sort:updated "UI"`

9. `Open Issues created on/after 1 Feb 2016` -> `repo:HubTurbo/SampleRepo is:issue is:open created:>=2016-2-1`

10. `Latest 3 open issues that are urgent` -> `repo:HubTurbo/SampleRepo is:issue is:open label:"urgent" count:3`
11. `Recent unread updates from my repos` -> `(repo:HubTurbo/SampleRepo;HubTurbo/SampleRepo2) is:unread updated<24 sort:~updated`
12. `Progress of the current milestone` -> `repo:HubTurbo/SampleRepo m:curr sort:status`
13. `Issues awaiting prioritization` -> `repo:Turbo/SampleRepo1 is:open is:issue ~label:priority`
