### ISSUE TITLE
Refactor LabelPickerUILogic.java

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1215]
This class is a good opportunity to practice refactoring skills and also to get used to our coding style.
Things to improve:
* Use more SLAP
* Make methods more testable e.g. if a method doesn't have any side effects, it is easier to test.
* Add header comments to non-trivial methods (comments should explain WHAT and WHY, but not HOW)

The end goal is to make the class easier to understand.

**Comment by damithc** [comment]
Funny how the effort label shows two values, even on GitHub :-p
I think it was created as `18` at first and corrected to `16` eventually, but that was long ago.
![image](https://cloud.githubusercontent.com/assets/1673303/13560491/d25f7096-e45a-11e5-9aae-cede0827b320.png)

**Comment by dariusf** [comment]
I corrected it right after adding it to this issue. Seems that the data in the event feed isn't related to the actual labels.
