### ISSUE TITLE
Warn users if an invalid username is used

### ISSUE THREAD

**Issue by dariusf** [HubTurbo/HubTurbo#1219]
`assignee` and `author` can check that the user referenced is a valid one.

We may need some support for displaying warnings, which don't propagate via an exception and show the error graphics, can be viewed in a list, etc.

**Comment by raisfathin** [comment]
@dariusf Do you mean checking username validity based on GitHub username requirement, or whether the resulting list after applying filter will be non-empty?

As for the second part, how about displaying them in a tooltip?

**Comment by dariusf** [comment]
By valid I mean checking that the user exists. I know there are limitations with being able to get the contributors for repositories that you're not a contributor for, but we can ignore that for now.

Sure, but you should post screenshots to see how it looks. I don't know how good a short list of long lines looks in a tooltip.

**Comment by raisfathin** [comment]
@dariusf So, to clarify, a user exists if the user is a contributor to the repository?

Okay, will provide it in the PR.

**Comment by dariusf** [comment]
Basically, if it can be found in the Model we build from GitHub data. You might look in the collection of users, or go through all issues to find the users mentioned, assigned, etc. Just pick the simplest one and if it's insufficient, it can be improved in future.

**Comment by raisfathin** [comment]
@dariusf Can you suggest a place in the code to implement this? I think this can't be purely done inside the UI (as it requires the knowledge of Model), and I can't think of a good place to implement this without changing a lot of existing code :disappointed:

**Comment by dariusf** [comment]
Checking if the assignee can be found should be done in Qualifier.

Continuing execution after encountering an error in order to generate a list of all the warnings seems tough, yeah. I guess we could just reuse the current error-handling for now and throw an exception? The exception could have a different type which makes it a warning instead.

If we want to support a list of warnings in future, we need some way to continue traversing the filter expression after an exception is thrown. This means we should catch the exceptions during traversal and somehow propagate them out together with the current boolean result.
