### ISSUE TITLE
Update the 'Team' page to reflect recent promotions.

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1235]
Area leads:
Dat  - API, Performance, 
Joshua - UI, Config, Testing,
Thien - Storage, Filters, Threading

Senior developers:
Hans,
Manmeet 

Committers:
Xinan, Martin, Yi Yan, Soon Jin, Rais

**Comment by YijinL** [comment]
First draft [here](https://github.com/YijinL/HubTurbo/blob/%231235-update-team-page-promotions/docs/team.md).

- I organised the active team member section for readability and ordered names alphabetically.
- I couldn't find the committer 'Martin' when searching the authors of this repo's PRs and issues, do you have a link to his contribution/github?
- I found a few more contributers e.g. [Weihan](https://github.com/HubTurbo/HubTurbo/pull/1227), should I compile the list of all unique contributers with closed pull requests? From what date should I start counting?

**Comment by xinan** [comment]
Martin is @m133225 :laughing:

**Comment by YijinL** [comment]
Updated martin.

First draft [here](https://github.com/YijinL/HubTurbo/blob/%231235-update-team-page-promotions/docs/team.md).

- I organised the active team member section for readability and ordered names alphabetically.
- I found a few more contributers e.g. [Weihan](https://github.com/HubTurbo/HubTurbo/pull/1227), should I compile the list of all unique contributers with closed pull requests? From what date should I start counting?
- ~~I couldn't find the committer 'Martin' when searching the authors of this repo's PRs and issues, do you have a link to his contribution/github?~~

**Comment by dariusf** [comment]
All the contributors ever are listed [here](https://github.com/HubTurbo/HubTurbo/graphs/contributors). It'd be good to have full names as well, where possible. We can help to fill in those people you don't know. Thanks!

**Comment by YijinL** [comment]
Does anyone know  [Gai](https://github.com/gaieepo)'s full name?
Latest draft [here](https://github.com/YijinL/HubTurbo/blob/%231235-update-team-page-promotions/docs/team.md).

**Comment by dariusf** [comment]
Wang Jie

**Comment by YijinL** [comment]
OK, the only person left that might not have a full name is **Martin**. After that I will submit the PR.

**Comment by xinan** [comment]
*Martin Choo Boon Yong* :trollface:
