### ISSUE TITLE
Support specifying repo for id filters

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1238]
e.g. `id:hubturbo/hubturbo/2431`
This will allow us to create watch lists using one id filter e.g.  `id:hubturbo/hubturbo/2431;teammates/repo/3489`

**Comment by dariusf** [comment]
Maybe we could use `#` as the delimiter? `id:hubturbo/hubturbo#2431`. Also makes sense because `#x` is how we refer to issues by id.

**Comment by damithc** [comment]
Good idea.
