### ISSUE TITLE
Recover when failed to update issue's labels on GitHub.

### ISSUE THREAD

**Issue by ndt93** [HubTurbo/HubTurbo#1246]

**Comment by ndt93** [comment]
Discover another concurrency issue when doing this:

`Logic.replaceIssueLabels` gets a reference to an Issue A -->  periodic refresh detect some changes to A and replace it with an updated copy in the list of issues for A's repository -->  `Logic.replaceIssueLabels` proceed to assign the labels using the reference to the discarded copy of A.

Consequently, there are no changes to A in the Ui. This happens especially during an interleaving of assigning labels, period refresh and undoing but still pretty rare. I ran into it once but haven't been able to replicate again.

**Comment by ndt93** [comment]
Fixed the above problem and also previously mentioned clashes with periodic refresh using some primitive synchronisations and additional flags and timestamp on an issue.

**Comment by dariusf** [comment]
Would that fix it in general? Ideally both kinds of updates should come in through the same channel and be synchronised at that point.

**Comment by ndt93** [comment]
We need to do synchronisation on a finer level since the eager update and the periodic refresh happen concurrently. There are rules associated with how the additional fields should be read from/write to that if future methods follow should fix the problems in general, provided that the client's physical clock is sufficiently accurate.

That's from what I'm reason about it at the moment but I could be wrong.

**Comment by ndt93** [comment]
Realised the problem gets carried up to the `Model` level too as the `Model`'s reference is also replaced. We probably need to put the whole thing in the queue then, and accept a bit slower local update.

**Comment by ndt93** [comment]
Putting in the queue can be too laggy when user change labels during refresh, so back to original solution which does help to reduce problem to very small chance and gives feedback when there is failure.
