### ISSUE TITLE
Show panel stats at the bottom of the panel

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1253]
We can show number of issues in the panel, broken down by open/closed?
![image](https://cloud.githubusercontent.com/assets/1673303/13047501/741e600a-d41a-11e5-920e-a4ff9d037bfa.png)

**Comment by HyungJon** [comment]
Rather than open/closed, would it be better to indicate as "20/100 open"? I think open/closed might not be very clear.

**Comment by yl-coder** [comment]
How about 20(open)/100(closed)

Let me know if this is ok, so i can proceed.

**Comment by damithc** [comment]
For a start, you can show the total only. We can add more details later.

**Comment by damithc** [comment]
@yl-coder Perhaps you can now move to adding a breakdown of the total? e.g. `4+6=10`. first number can be green (open issues) and the 2nd one can be red.

**Comment by yl-coder** [comment]
ok will work on this, can someone open this issue again?

**Comment by damithc** [comment]
@yl-coder Create a new issue for it. No need to continue this one :-)
