### ISSUE TITLE
Add an 'filter syntax index' table to documentation

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1291]
To be added to the bottom of docs/filters.md

A partial list can be found in #1151 

Columns: `keyword` `aliases`
keyword column should be sorted alphabetically, and each keyword can be hyperlinked to the explanation.

**Comment by yl-coder** [comment]
Just to clarify, i found the keyword and qualifier aliases in Qualifier.java(expandKeywordAliases method) and QualifierType.Java(initialiseQualifierAliases method). Am i referencing in the correct place? Please advise. 

Appended the code below for easy reference.


/**
     * Expands aliases for Qualifier keyword in user input.
     * Includes aliases for Qualifier that also functions as keyword 
     * @param input
     * @return 
     */
    public static String expandKeywordAliases(String input) {
        
        switch(input) {
            case "as":
                return "assignee";
            case "body":
            case "desc":
            case "de":
                return "description";
            case "d":
                return "date";
            case "l":
            case "labels":
                return "label";
            case "m":
            case "milestones":
                return "milestone";
            case "r":
                return "repo";
            case "st":
            case "status":
                return "state";
            case "t":
                return "title";
            case "u":
                return "updated";
            case "o":
                return "open";
            case "c":
                return "closed";
            case "i":
                return "issue";
            case "p":
            case "pullrequest":
                return "pr";
            case "mg":
                return "merged";
            case "um":
                return "unmerged";
            case "rd":
                return "read";
            case "ur":
                return "unread";
            case "cm":
                return "comments";
            case "ns":
                return "nonSelfUpdate";
            default:
                return input;
        }
    }

    /**
     * Consists of aliases for all supported qualifiers. Applicable only when 
     * parsing Qualifier left hand side of ":"
     */
    private static Map<String, QualifierType> initialiseQualifierAliases() {
        Map<String, QualifierType> aliases = new HashMap<>();
        aliases.put("as", ASSIGNEE);
        aliases.put("au", AUTHOR);
        aliases.put("creator", AUTHOR);
        aliases.put("cr", CREATED);
        aliases.put("cn", COUNT);
        aliases.put("d", DATE);
        aliases.put("de", DESCRIPTION);
        aliases.put("desc", DESCRIPTION);
        aliases.put("body", DESCRIPTION);
        aliases.put("h", HAS);
        aliases.put("user", INVOLVES);
        aliases.put("l", LABEL);
        aliases.put("m", MILESTONE);
        aliases.put("n", NO);
        aliases.put("r", REPO);
        aliases.put("s", SORT);
        aliases.put("st", STATE);
        aliases.put("status", STATE);
        aliases.put("t", TITLE);
        aliases.put("ty", TYPE);
        aliases.put("u", UPDATED);
        return Collections.unmodifiableMap(aliases);
    }
