### ISSUE TITLE
Make auto-complete on-demand

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1293]
Currently, it is getting in the way more than it is helping. Suggestion:
Do not activate insert the suggested letters unless user requests for auto-complete suggestions e.g using a keyboard shortcut
Optionally, we can show the suggestions automatically, but outside the filter box (e.g. just below cursor). The suggestion will not be inserted unless the user requests.

**Comment by jinified** [comment]
I think using `TAB` for auto-completion of keyword is more intuitive and since we don't many completion words, I don't think it warrant a pop-out

**Comment by damithc** [comment]
A popup (especially if it shows all matches instead of the best match) helps the typing. User can look at the popup when he needs guidance while ignoring it at other times.  A `TAB` slows down the typing because it breaks the flow.

**Comment by jinified** [comment]
I guess for now we would not have a problem if we don't set a limit to the list of suggestions in the popup. I have already implemented a suggestion menu that behaves  like GitHub's autocomplete for `reference` and `mention` for my issue creator. 

What about the keyboard shortcut to trigger it ? 
- `CTRL + SPACE`

**Comment by damithc** [comment]
I should not fill in text if the user doesn't explicitly asks for it. period. There were so many times I wanted `is:i`, typed it, hit enter, and ended up with `is:id`. It should be like google search bar. It's fine to show suggestions, but it's not fine to fill in text without being asked to.

**Comment by damithc** [comment]
Ideally, showing suggestions (without auto-filling) should not require any action from user. If the user doesn't want suggestions, just don't look at them. However, accepting the suggestion (i.e. auto filling) should need a user action. I'm ok with using `TAB` for that if that works.

**Comment by jinified** [comment]
Understood. Will work on it.
