### ISSUE TITLE
Tweak author/assignee display in PRs

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1298]
![image](https://cloud.githubusercontent.com/assets/1673303/13419100/9caf7304-dfb6-11e5-9012-e1e85467e4e2.png)

1. Add space between avatar and userid?
2. display author/assignee after milestone? (saves one line)

**Comment by garbanzos** [comment]
@damithc 
Where should the author/assignee be displayed if there is insufficient space to display them? (eg. when there are many labels for the PR)

**Comment by damithc** [comment]
Then it can overflow to the next line.

**Comment by garbanzos** [comment]
Then won't the cards be rather inconsistent?  
Some of the cards will have author/assignee on the same line as the milestone and some will have author/assignee on a different.

**Comment by damithc** [comment]
You have a point. Perhaps we can show labels *after* assignee/author?
