### ISSUE TITLE
Unexpected write error

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1300]
![image](https://cloud.githubusercontent.com/assets/1673303/13453829/0d9bf326-e08e-11e5-9192-0ad2298919b3.png)

Quota seems to be ok and I have write permissions.
On a related note, the icon in the dialog looks like a close button.

**Comment by damithc** [comment]
Here's the log
[hubturbo-log - Copy.zip](https://github.com/HubTurbo/HubTurbo/files/154292/hubturbo-log.-.Copy.zip)

**Comment by ndt93** [comment]
That's the default error message whenever it fails to update the issue's labels regardless of the actual errors. The actual exception is `SocketTimeoutException` but I'm not sure why that happened yet.

**Comment by damithc** [comment]
GitHub was unusually slow today, which could have caused the timeout. The error reporting needs to be more informative and more accurate. The current error message suggests this is a permission issue when it may not be.

**Comment by damithc** [comment]
Happened a few times today too.

**Comment by ndt93** [comment]
We should probably increase the timeout and see if GitHub being slow is the actual cause for this. It takes quite a long time for me to pull from GitHub this afternoon but seems fine now

**Comment by damithc** [comment]
It's been a while with this one. Can finish soon?

**Comment by ndt93** [comment]
Sure. I will try to finish this for the coming milestone.
