### ISSUE TITLE
More obvious sign of filter syntax problem

### ISSUE THREAD

**Issue by acruis** [HubTurbo/HubTurbo#1301]
Should we make it more obvious when the syntax for the filter is wrong? Something like the bottom half of this:

![image](https://cloud.githubusercontent.com/assets/8437638/13456896/3b0f3ed2-e0a0-11e5-9af7-e1e2c7b89c10.png)

(example from Wireshark)

**Comment by damithc** [comment]
Yup, that could be useful.

**Comment by garbanzos** [comment]
Should the text field change colour after the user presses enter or every time the text in the text field changes?
