### ISSUE TITLE
Add a generic way to traverse context menus in tests

### ISSUE THREAD

**Issue by dariusf** [HubTurbo/HubTurbo#1314]
We have `traverseMenu`, which takes a menu path (as a list of strings) and clicks the trigger. We can do the same for context menus, which might allow us to move some tests (for example, `ContextMenuUnstableTests`) out of `unstable`.

**Comment by raisfathin** [comment]
@dariusf Is it ok to implement something like `private void traverseContextMenu(ContextMenu, String...)` or do we need to make it more general (e.g., by passing the `Node` instead of `ContextMenu`)?

**Comment by dariusf** [comment]
Hmm, if we're doing stuff specific to context menus, it's fine to have it be specific. I'm not sure if it's possible to traverse nodes in such a generic way, since not all types of nodes have names.
