### ISSUE TITLE
AppliedFilterEvent should be triggered when there is a parse error

### ISSUE THREAD

**Issue by m133225** [HubTurbo/HubTurbo#1321]
Bug caused by #1280.

Currently, the list of issues remains faded when the filtering terminates early due to a parse error.

**Comment by damithc** [comment]
After getting the version with #1280, I notice panels going blank a few times (and staying blank) even when the panel should be showing issues. Possibly related to this?

**Comment by m133225** [comment]
@damithc I suspect that is a separate issue caused by the asynchronous filtering. Will look into it before making another issue and PR for it. Should the priority for this issue be lowered?

**Comment by m133225** [comment]
This issue is not required anymore since the cause was wrongly identified. #1322 should be sufficient to fix the ongoing problems with the filter. Can I close this?
