### ISSUE TITLE
Label picker appears partially off-screen

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1324]
Here's how it looks in my home computer (but looks ok in my office computer):
![image](https://cloud.githubusercontent.com/assets/1673303/13571744/cdda055c-e4b1-11e5-9d6c-ac7edbb4a0a8.png)

I remember this was a problem with the original label picker as well, but it was fixed at some point.

**Comment by jinified** [comment]
I think that is because I removed the `positionDialog`. Though it seems to work on my computer, I guess I will add it back.
