### ISSUE TITLE
Rename File menu item

### ISSUE THREAD

**Issue by dariusf** [HubTurbo/HubTurbo#1356]
The File menu item doesn't contain anything related to files. :stuck_out_tongue: We can probably change the name to 'App'? 'HubTurbo'?

<img width="88" alt="screen shot 2016-03-15 at 1 29 01 am" src="https://cloud.githubusercontent.com/assets/4328341/13753328/79b4b67e-ea4d-11e5-8908-4a4ec1889952.png">

**Comment by damithc** [comment]
I had the same thought once. But it seems this is a common practice, for some reason :-p

**Comment by yl-coder** [comment]
True. I think changing it to HubTurbo is good. Most Mac Apps follow this convention of using the App name to contain item like Logout and Quit.

**Comment by damithc** [comment]
In windows apps on the other hand, quit/exit/logout seem to appear under the `file` menu. I checked Powerpoint, Sourcetree, and Synctoy just now. So it looks like a OS-dependent thing :-p

**Comment by yl-coder** [comment]
How about showing HubTurbo for Mac and File for Windows?

On other hand, having a missing file menu item just seems weird.

**Comment by damithc** [comment]
Or come up with a name that is acceptable to all three OS, even if it is different from the conventions of all three. May be `App` as @dariusf suggested is a good idea after all.
