### ISSUE TITLE
'go to file view' keyboard shortcut is broken

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1364]
`g,f` shortcut used to go to the diff view of a PR seems to be broken, possibly due to a change in the webpage structure.

**Comment by damithc** [comment]
So is the `g,c` shortcut used to go to the commits view.

**Comment by damithc** [comment]
I think most shortcuts related to PR page is broken. Need a quick fix.

**Comment by damithc** [comment]
This broke again :-p #1393

**Comment by acruis** [comment]
It was working before this?

**Comment by acruis** [comment]
Apologies, should continue the conversation in the new issue.
