### ISSUE TITLE
Change BrowserComponent switchToTab to openTab

### ISSUE THREAD

**Issue by HansNewbie** [HubTurbo/HubTurbo#1375]
Currently, `switchToTab` would switches the tab of PR page (Conversation, Commits and Files). It expects the bView to be in a PR page, otherwise it won't work. This method is problematic when bView iss not originally in a PR page, e.g. bView is in keyboard shortcut then user presses `G``F` to open PR file tab; bView will open PR page first (by default go to conversation tab) before switching tab to file tab. It is slow and user will wonder what's happening since the pages keep changing.

The proposed solution is to have `openPrTab` instead; instead of switching tab by clicking the tab in the page (as `switchToTab` is doing), open the URL to the given PR tab directly instead. May change the method signature to `openPrTab(prId, tabName)`.

As proposed in #1367.

**Comment by YijinL** [comment]
Can I fix this issue even though it lacks the `forContributors` label?

**Comment by damithc** [comment]
Go ahead @YijinL

**Comment by HansNewbie** [comment]
@YijinL are you doing this issue?

**Comment by YijinL** [comment]
@HansNewbie yes, but if you already fixed it then no need to wait for mine

**Comment by HansNewbie** [comment]
@YijinL nope, I haven't. I will leave this issue to you then.

**Comment by YijinL** [comment]
Since clicking the tabs is faster than using the url, how about:
```
if browser is in PR page
    click tab
else go to url
```
Or should it always go to url so we stay insulated from DOM changes?

**Comment by HansNewbie** [comment]
I was thinking of that for speed, but that means whenever the DOM changes we still need to fix it. Personally, I find opening url is better in the long run as it will require less maintenance. However, if the workflow in mind is switching from one tab to another often it's better to click tab.

@damithc what do you think? I thought of the same thing but any DOM changes will require manual fix.

**Comment by damithc** [comment]
Yes, let's go for URL approach. The DOM approach is too brittle. We have plans to introduce predictive preloading at some point, so the loading speed problem might get solved at that point.
