### ISSUE TITLE
"Change labels (L)" option doesn't appear in the context menu for an issue sometimes

### ISSUE THREAD

**Issue by codemanmeet** [HubTurbo/HubTurbo#1383]

**Comment by garbanzos** [comment]
The option does not appear on my computer at all.

**Comment by damithc** [comment]
Any Mac user has the same problem?

**Comment by raisfathin** [comment]
I'm having that problem as well. It doesn't appear on the default panels. However, when I create a new panel, it appears only on that new panel.

Maybe this happens only to default panels?

**Comment by m133225** [comment]
I agree with @raisfathin . Never had this problem before until I read his comment and tried opening a sample board.

**Comment by raisfathin** [comment]
After further testing on my computer, the menu only appears on the last panel added.

It seems that there is a weird behaviour where when we add the same object of `MenuItem` which is already contained in some other `Menu` (let's say, Menu1) to another `Menu` object, the `MenuItem` will disappear from Menu1.

This is the relevant source code of `Menu.java` inside javaFX (in my computer it is located at line 359):
<img width="537" alt="screen shot 2016-03-23 at 03 44 31" src="https://cloud.githubusercontent.com/assets/9299240/13965559/bb2bbffa-f0a9-11e5-98b4-9c5f8e03eae4.png">

I also tested this on an [online compiler](http://ideone.com/m6S3Gz).
