### ISSUE TITLE
User can add issues to a 'watch list'

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1389]
... so that users can maintain a 'watch list' of selected issues.

User should be able to right click on an issue card and choose `add to new watch list`. This will create a new panel with the corresponding `id:repo#id` filter. User will be prompted to give a name for the panel.

After that, user should be able to add more issues to the that panel by right-clicking on issues and choosing `add to watch list` --> `panel name`

**Comment by raisfathin** [comment]
Is the `panel name` in `add to watch list` --> `panel name` going to be nested inside the `add to watch list`? Or we just let the user choose one using a dialog?

**Comment by damithc** [comment]
Let's try nesting first.

**Comment by damithc** [comment]
In fact, it can be:
```
Add to watch list
    New watch list
    existing watch list 1
    existing watch list 2
```

**Comment by raisfathin** [comment]
Okay. Just to clarify, can we add it to any existing panel? Or just those that were created using `New watch list` menu?

**Comment by damithc** [comment]
At the moment, only to panels that contain a watch list (i.e. an `id` filter or an empty filter). I don't think it makes sense to add issues to a panel containing a regular filter.

**Comment by raisfathin** [comment]
Understood, thanks.
