### ISSUE TITLE
Milestone picker: support up/down arrows

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1412]
Let's say we want to reschedule an issue from current milestone to the next one. `M` `down` `enter` should accomplish that.

**Comment by m133225** [comment]
What should the behaviour be if there is currently no milestone assigned to the issue, and the user presses `M` `down` `enter`?

**Comment by damithc** [comment]
I think up/down keys should simply navigate the best matching milestones. When the milestone picker opens, the best matching panel should contain the next milestone at the top of the list so that the above key sequence still works. Does that answer both your questions?
