### ISSUE TITLE
Milestone picker: show all milestones in a scrollable panel

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1413]
Below the best 5 matches panel, we can show the full list in a scrollable panel. It can be a static panel (no highlighting etc), but it should be clickable.

**Comment by m133225** [comment]
Should this be done only after #1411? Since there is no _best 5 matches panel_ yet.

**Comment by damithc** [comment]
The one we have already is the 'best 5  matches' panel right? The only problem is it sometimes show fewer than 4. 
The one requested in this issue is somewhat independent. It's just a clickable panel of milestones sorted by due date.

**Comment by m133225** [comment]
No, it currently shows all matches, fitted into a scrollable panel.

**Comment by damithc** [comment]
Actually, I don't mind if it shows more than 5 and is scrollable. Just ensure that it shows at least 5 and height is fixed to 5 milestones.
