### ISSUE TITLE
Hotkey for closing an issue should be consistent with the context menu option

### ISSUE THREAD

**Issue by m133225** [HubTurbo/HubTurbo#1430]
Currently, 'X' is used to close an issue using even though the context menu indicates 'Close issue (C)'.
<img src='https://cloud.githubusercontent.com/assets/12193772/14066779/cab4bf00-f485-11e5-8e31-c7a014013d7e.png' width=300/>

**Comment by xinan** [comment]
I think I fixed this before. Don't know why it is back again. Maybe there was a merge conflict and someone made a mistake in resolving it. 😳
