### ISSUE TITLE
Error message: invalid keyboard shortcuts

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1432]
I get this error when I open HT with latest master 
![image](https://cloud.githubusercontent.com/assets/1673303/14070218/5f811ffc-f4d6-11e5-8954-15fe7c796ece.png)

**Comment by damithc** [comment]
@xinan possibly related to your PR on open/close shortcut?

**Comment by xinan** [comment]
Isn't that normal when you add a new keyboard shortcut?

**Comment by damithc** [comment]
Not really. It may be a weakness in the validation check.

**Comment by dariusf** [comment]
I got this too. I think we can make it so that new shortcuts are set to their default value. If there's some schema inconsistency, maybe we can produce a backup of the user's configuration, then reset the shortcuts used.

**Comment by damithc** [comment]
I don't mind removing the custom keyboard shortcuts feature entirely. I don't think that feature has a future.
