### ISSUE TITLE
Add login username to auto-create panel filters

### ISSUE THREAD

**Issue by codemanmeet** [HubTurbo/HubTurbo#1457]
`Recently updated issues` -> `assignee:codemanmeet updated:<48` obtained from the Auto-create Panels menu would have codemanmeet appear based on the logged in user.

**Comment by damithc** [comment]
Can elaborate more?

**Comment by codemanmeet** [comment]
Just added it!

**Comment by dariusf** [comment]
Hmm, don't think the title needs to mention the password.
