### ISSUE TITLE
`Menu > Boards > New` should restore current board if save is aborted

### ISSUE THREAD

**Issue by xinan** [HubTurbo/HubTurbo#1460]
The way we are doing it now is a bit hack-ish. It clear the current board, and calls `Menu > Boards > Save as`. So what happens if I abort the `Save as`?

Steps to reproduce the bug:
1. Choose `Menu > Boards > New` and click `OK`.
<img width="472" alt="screen shot 2016-04-03 at 15 35 20" src="https://cloud.githubusercontent.com/assets/2834397/14231338/43b6a180-f9b2-11e5-800a-004c7b41b132.png">
2. Click `Cancel` to abort the `Save as` dialog.
<img width="524" alt="screen shot 2016-04-03 at 15 35 30" src="https://cloud.githubusercontent.com/assets/2834397/14231342/73fac920-f9b2-11e5-94a8-d5bf89a85f04.png">
3. Voila! You remain at your current board but all panels are closed.
<img width="552" alt="screen shot 2016-04-03 at 15 35 37" src="https://cloud.githubusercontent.com/assets/2834397/14231346/a899d6f8-f9b2-11e5-89b2-a29dc7b003c6.png">

**Comment by dariusf** [comment]
Can we fix this by clearing only after getting a response to `Save as`?

**Comment by xinan** [comment]
Hmm, we can do that. However, we are editing the behaviour of `Save as`. Why not just have a dedicated dialog for creating boards?

**Comment by dariusf** [comment]
That also works. We can factor out the relevant parts of `Save as`.
