### ISSUE TITLE
repo picker: clicked repo is not switched to

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1464]
If I click a repo name and press 'confirm', the default repo doesn't change to the chosen repo. I think we had the same bug in the label picker or the milestone picker (don't remember which one)

**Comment by raisfathin** [comment]
Can you clarify further? Both click repo + enter and click repo + click confirm works on mine.

Is the text field empty?

**Comment by damithc** [comment]
Here's an example. It happens when there is some text in the text field.
![image](https://cloud.githubusercontent.com/assets/1673303/14233345/4a4c9af4-f9f8-11e5-8dee-977510ab5caa.png)

**Comment by raisfathin** [comment]
:( My bad. Found the bug. Fixing it now.
