### ISSUE TITLE
repo picker: when there are multiple matches, at least one should be selected

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1465]
Even a random selection is better than no selection. For example, one of the matches should be selected:
![image](https://cloud.githubusercontent.com/assets/1673303/14233285/9d7d8da2-f9f6-11e5-8135-6a2078fcf235.png)

**Comment by damithc** [comment]
Also refer #1468

**Comment by raisfathin** [comment]
Just realised this is also fixed in #1486. Is it fine to just let that PR do the fix for this issue as well?

**Comment by damithc** [comment]
Sure.

**Comment by raisfathin** [comment]
Resolved in #1486
