### ISSUE TITLE
repo picker: move 'add repo' functionality to a menu item or a separate button.

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1468]
I think pickers should not facilitate a 'add' function, at least not the way it does now. Either we should move the 'add repo' function to a new menu item or provide a 3rd button to add a new repo within the repo picker. i.e. type new repo name and click 'add'.
The current implementation prevents us from picking a repo by typing a few letters only.

**Comment by raisfathin** [comment]
I think having a 3rd button to add a new entry to the repo picker is better since in the future we want the repo picker to be reused for something else. Also, having a new menu item to add repo can be confusing since it would defeat the purpose of having a repo picker.

What do you think?

**Comment by damithc** [comment]
Yes, I don't mind having an extra button in the picker itself, but not for the reasons given :-) The 'picker' is for picking among available options, not for 'adding' stuff. e.g. label picker is not used to add new labels.

**Comment by raisfathin** [comment]
True... Guess I was still thinking of the old repository selector :sweat:

Alright, I need a few more clarifications about the new behaviour:
1. Should we check whether the new repo exists (and retrieve it)?
2. Should we automatically select the new repo (but not changing the filter)? Or do we just assume that the user wants to choose the new repo?

**Comment by damithc** [comment]
Under what scenario exactly? Are you clarifying about the `add` button?

**Comment by raisfathin** [comment]
Yes
