### ISSUE TITLE
Add documentation about headless testing workflow 

### ISSUE THREAD

**Issue by jinified** [HubTurbo/HubTurbo#1471]
## To be included
- [x] how to run in headless mode
- [ ] mention about tests failing on Mac
- [x] brief description about how headless testing works

**Comment by jinified** [comment]
@dariusf  Do you think I should include the details about some issues I encounter while stabilizing the tests

**Comment by dariusf** [comment]
Yes, as much as possible. All the random caveats about hotkeys only working sometimes if you're pressing the same one consecutively, why dragging is unreliable, etc. Maybe it could be structured as a FAQ. This will really help people who work on the tests in future.

**Comment by jinified** [comment]
Ok noted
