### ISSUE TITLE
assignee & milestone picker: position needs adjusting

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1478]
The left edge is outside the screen on my home computer
![image](https://cloud.githubusercontent.com/assets/1673303/14268897/31671e2c-fb12-11e5-9648-c2ca2ac12c7b.png)

**Comment by damithc** [comment]
Noticed this problem in both my computers.

**Comment by garbanzos** [comment]
@damithc the milestone picker also suffers from the same problem on my computer
Should it be a separate issue or it can be fixed in this issue also? 

![image](https://cloud.githubusercontent.com/assets/12397473/14274742/c0953006-fb45-11e5-8612-d8a4742c0b72.png)

**Comment by damithc** [comment]
Yes, have the same problem. Both can be fixed here.
