### ISSUE TITLE
Milestone Picker: previous and new milestone should not be the same

### ISSUE THREAD

**Issue by m133225** [HubTurbo/HubTurbo#1487]

**Comment by damithc** [comment]
@m133225 How about this:
* No milestone assigned: text box auto-filled with most likely milestone to be assigned, and the text is selected.  
  * To assign the suggested milestone, press enter.
  * To choose a different milestone, start typing.
* Already has a milestone assigned: text box auto-filled with the most likely milestone the issue could be reassigned to. 
  * To reassign the issue to the suggested one, press enter. 
  * To unassign the current one, press backspace once (which will make the text box empty and will strike out the currently assigned milestone) and press enter. 
  * To assign a different milestone, start typing.

What the above means is, an empty query box is interpreted as 'remove existing'.

@garbanzos FYI.

**Comment by m133225** [comment]
However, when there is already an assigned milestone, filling the query box with a suggested one while keeping the existing one intact will cause the selected milestone to be independent of the query box. In other words, the query box by itself cannot determine the outcome of the changes. The major refactor of the label picker was meant to avoid this, wasn't it?

**Comment by damithc** [comment]
No, in this case the current one will be stricken out. i.e. we are suggesting a rescheduling of the issue which means the current one will be stricken out and a new one will be suggested. We just need to figure out the next best milestone and autofill the text box with it. The striking out and the suggestion will happen automatically, right?

**Comment by m133225** [comment]
Sounds reasonable, updated the opening comment with the latest behaviour.
So in this case, #1481 simply needs to make sure that the milestone in the textfield is not the same as the currently selected one? This PR for this issue should address the same thing for milestone picker.

**Comment by damithc** [comment]
Yes, that problem is inevitable. It's matter of improving the algorithm we use to find the best 5 matches. 

Even if the algo is not good, if the user doesn't like the suggested one and the other 4 suggestions, he can just backspace to clear the text box which gives us an opportunity to fill the best-5 with more potential matches.
