### ISSUE TITLE
Author qualifier does not consider real name

### ISSUE THREAD

**Issue by raisfathin** [HubTurbo/HubTurbo#1489]

**Comment by raisfathin** [comment]
@dariusf We don't have complete user data for users who are not a repo's contributor. And I don't think it's wise to query for all of them (as it requires 1 more API call per issue). What do you think?

**Comment by dariusf** [comment]
Depends on how frequently we do this. Wouldn't non-contributors not appear in the list of users though?

**Comment by raisfathin** [comment]
@dariusf Yes, they won't. But we can use GitHub API to get their real names based on the login name from `creator` field in `TurboIssue.`

**Comment by dariusf** [comment]
Do we currently go over all the issues to find creators, assignees, etc.? If no, then I don't think we need to do this yet. Something simple will work.

**Comment by raisfathin** [comment]
No. Hmm, what do you mean by something simple?

**Comment by dariusf** [comment]
I mean we can just fix the author qualifier not considering the real name here, and worry about how to get non-collaborator names later.

That will require some planning. For example, we currently know if there are changes to issues using the last modified time. We can use that to look at all new comments and request the real names then. That information needs to be cached somewhere too, etc.
