### ISSUE TITLE
Label picker unexpected behaviour when combining type and click.

### ISSUE THREAD

**Issue by ndt93** [HubTurbo/HubTurbo#1494]
To reproduce:

Open label picker on an pull request with label `onGoing` > type `toReview` to add that label > click on `onGoing` to remove that label.

Expected: remove `onGoing` and add `toReview`

Actual: `onGoing` is removed but `toReview` is not added.

**Comment by raisfathin** [comment]
Are you sure about the expected behaviour? [This if statement](https://github.com/HubTurbo/HubTurbo/blob/master/src/main/java/ui/components/pickers/LabelPickerDialog.java#L279) suggests that the current behaviour is intended :confused:

**Comment by ndt93** [comment]
The unexpected behaviour is from the my point of view of a user :-P. If it's intended then this is open to discussion.

**Comment by damithc** [comment]
W.r.t the steps:
1. Open label picker on an pull request with label `onGoing` 
2. Type `toReview` to add that label : this should automatically remove `onGoing`
3. click on `onGoing` to remove that label

I'm not sure about the step 3. Shouldn't it have been removed already?

**Comment by ndt93** [comment]
Ah all rights, I need to type <kbd>space</kbd> after `toReview` before it's actually added in. The `toReview` already appeared on the list of selected labels (in a faded state) before that so I thought it was added in and press <kbd>Enter</kbd>.

Another behaviour is that while the `toReview` is in the faded state as above, if I click on the `toReview` label, it will show as being removed (crossed out state) although it's correctly applied after confirmation.

**Comment by damithc** [comment]
yes, that's a bug. Clicking the suggested label should select it rather than remove it. Clicking a selected label should remove it.

**Comment by raisfathin** [comment]
In that case, what should happen if `toReview` is clicked again? Removed or faded?

**Comment by damithc** [comment]
![image](https://cloud.githubusercontent.com/assets/1673303/14410888/b0643472-ff6c-11e5-8edb-f5ec60c2d20a.png)
Clicking on the 'suggested' label should make it selected.
Clicking on a selected label should remove it from the selected list.

**Comment by raisfathin** [comment]
I see, thanks!
