### ISSUE TITLE
Issue count is not showing up on all panels

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1501]
![image](https://cloud.githubusercontent.com/assets/1673303/14403101/7707ae1a-fe7d-11e5-86b5-5b5f24d88fbd.png)

**Comment by yl-coder** [comment]
It works fine on my mac computer. Does it happens all the time or intermittently?

**Comment by damithc** [comment]
Seems to be intermittent. Not sure what caused it though. I'll upload the log if it happens again.

**Comment by damithc** [comment]
Here's the log. What happened was I edited a filter and the panel issue count because 0 although the panel had issues.
[hubturbo-log - Copy.zip](https://github.com/HubTurbo/HubTurbo/files/212113/hubturbo-log.-.Copy.zip)

**Comment by damithc** [comment]
After a while, it became correct again though.
