### ISSUE TITLE
Arrow keys don't work for 'close issue' dialog

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1502]
![image](https://cloud.githubusercontent.com/assets/1673303/14404036/aa641e98-fe9f-11e5-87a7-480932ba4371.png)
At this point, I expected to be able to press the right arrow to move the focus to 'cancel' button and be able to hit enter to cancel the 'close' operation. However, doing so resulted in closing the issue.

**Comment by yl-coder** [comment]
Its a normal javafx behaviour. Pressing "Enter" will close the default button(Highlighted in Blue). Pressing "Space" will trigger the button selected by using the arrow key.

http://stackoverflow.com/questions/29959565/javafx-alert-dialog-ignores-the-focused-button

**Comment by damithc** [comment]
I see. May be we have to get used to it then :-p
