### ISSUE TITLE
Close button not working (Board -> New )

### ISSUE THREAD

**Issue by yl-coder** [HubTurbo/HubTurbo#1503]
Happen in this scenario,

When there are new changes in the board.

1) Click on Board on the menu

2) Then click on New.

3) Dialog show up
![image](https://cloud.githubusercontent.com/assets/9070608/14404856/5cdceac0-fe4e-11e5-9917-d80a05ee3c8c.png)

4) I can't close by clicking on the small red close button on the top left hand corner of the window. The only way for user to exit is through the next prompt window.

**Comment by damithc** [comment]
Confirmed on Windows. 
Closing this dialog should result in aborting the whole operation.

**Comment by xinan** [comment]
I found that all dialogs in `DialogMessage` have this problem. For example, if you try to create a board that has the same name as an existing board, it will prompt you about whether to overwrite or not. You can't close that alert with the close button too. 

I can fix this.
