### ISSUE TITLE
issue picker: issues shown are from a different repo

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1511]
![image](https://cloud.githubusercontent.com/assets/1673303/14410665/131e3834-ff67-11e5-9b15-02f2b33e18f5.png)

The default repo at the time was hubturbo, but the issue shown is from teammates

**Comment by jinified** [comment]
@damithc  Do you have any specific steps to reproduce this error ? I can't seemed to reproduce this by switching repository and launching the Issue Picker

**Comment by damithc** [comment]
Note that some of my panels have other repos open using the `repo` filter. Other than that, I just opened the issue picker.

**Comment by jinified** [comment]
Ok. I will look into it
