### ISSUE TITLE
Clear the filter box by pressing esc

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#223]
For example, 
Type some keywords and press enter --> show the issues matchng the keywords and auto completes the filter
Press ESC --> clear the filter syntax and go back to keywords
Press ESC again --> clear the filter box entirely so that a new set of keywords can be entered

**Comment by dariusf** [comment]
Currently Esc in the filter box reverts the previous edit (since hitting Enter).

Rajan suggested emulating the functionality of browser url bar, so when we click on it all text is selected, and we can then start typing immediately to replace the contents of the box. Would this be better?

**Comment by damithc** [comment]
Yes, that sounds like a good idea.

**Comment by damithc** [comment]
On second thoughts, emulating browser url bar exactly may not be suitable. In Browsers, we type a new url by default. In filters, we may want to add to the existing filter.

**Comment by dariusf** [comment]
Okay, so we won't change the way the box works. Should we change Esc?

**Comment by damithc** [comment]
Let's think about all the things we do using filters and see what hotkey combination works best. On a related noted, how hard is it to detect an event such as 'rapid double space'? e.g. how iOS replaces a rapid double space with a dot.

**Comment by dariusf** [comment]
It isn't built in, so we'll have to implement it ourselves. What do you have in mind for it?

**Comment by damithc** [comment]
When typing, a quick double space is much easier to do than a key
combination such as ctrl+down. Besides, space is easier to type than arrow
keys. If we can catch that event, we can use it for something useful. e.g.
Double space to go from filter to first issue. space bar to go down the
issue list one issue at a time. double space again to go back to filter
box. Anyway, it's not urgent.

**Comment by damithc** [comment]
Removing from V1.9. We need to discuss further before implementing this.

**Comment by rd1992** [comment]
User can use ctrl + a to select all the text in the box. ESC is used to revert any edits and escape the filter box.
