### ISSUE TITLE
Make query language more like GitHub's query language

### ISSUE THREAD

**Issue by dariusf** [HubTurbo/HubTurbo#231]
## Current filter syntax vs GitHub’s

**Both**
- NOT, AND

**Current**
- OR

**GitHub**
- Can mix keywords with predicates
- (Date) ranges
- More predicates (involvement, commenters)
- Can specify lists of sources to search
- Site-wide integration: can search across repositories, differentiate pull requests, private/public repositories, merged, searches comments, mentions, etc.

**Comment by acruis** [comment]
Test comment

**Comment by damithc** [comment]
This is one of the issue causing json explosion.
