### ISSUE TITLE
Visible jump when down arrow is pressed after regaining focus

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#288]
After regaining focus, pressing the down arrow will just the selection to the top item immediately followed by jumping to the intended item. The final outcome is as expected, but the jump is an eyesore.
Interestingly, it doesn't happen for the up arrow. Are the two keys handled differently?

**Comment by dariusf** [comment]
Fixed in b985fe9244e97a3eb5ca57f339396b18f07fd513 and d0b6501803b2ade7de5aadf5264fef0f13060bb2.
