### ISSUE TITLE
Add logging to HT

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#299]
This can help in debugging memory leaks etc.

**Comment by damithc** [comment]
I think we need a "rolling" log file that keeps last x Mb or n entries (so that the log file does not keep growing infinitely). Not sure if built-in logging of Java can do that. if not, we might need something like log4j

**Comment by damithc** [comment]
@dariusf you may have to set up the logging infrastructure for others to start using it.

**Comment by dariusf** [comment]
We are actually using log4j already, but logging is only done in a few places. It's also probably not configured optimally yet.

**Comment by damithc** [comment]
DEBUG level log messages should be verbose enough to tell us the sequence
of actions that happened.

**Comment by dariusf** [comment]
Logging has been added for almost all of the UI elements and operations (may have missed some). It's still needed for local file updates and syncing.
