### ISSUE TITLE
 -milestone: doesn't work if it is in the middle of the filter

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#300]
This is when I want to list issues that doesn't have a milestone
`state:open -milestone:  label:priority.high` doesn't work
`state:open label:priority.high -milestone:` works

**Comment by dariusf** [comment]
The first one parses as `-milestone:"label:" priority.high`. The parser is a bit too permissive with what `milestone:` can take.

Would it be better to make this empty string case a parse error, or support it? The intended filter for "issues with no milestone" is `no:milestone` or `-has:milestone`.

**Comment by damithc** [comment]
I'm ok with giving an error message.
What's the filter for 'no status label'? `-label:status.*` still works?

**Comment by dariusf** [comment]
Alright, I'll make it stricter.

Yup, but without the `*`.
