### ISSUE TITLE
Update not done for issue's labels

### ISSUE THREAD

**Issue by taychunmei** [HubTurbo/HubTurbo#301]
![image](https://cloud.githubusercontent.com/assets/2648455/5604541/b12f3f68-93fd-11e4-91c0-05be9b05256e.png)

Not sure what happened. I think recolouring of labels was done and perhaps removing of some labels. But HT doesn't seem to update the removal of a label from an issue currently.

**Comment by damithc** [comment]
are you referring to `github-api` label in issue 244? seems to be ok on my side (it has changed to `api`) but may be because I did the change myself

**Comment by damithc** [comment]
label management seems to be buggy on HT side and/or GitHub side. Anyway, we are not going to release the label management feature soon, so not urgent.
