### ISSUE TITLE
login form: 'owner id' doesn't work for repos under organizations

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#306]
The first parameter need not be owner id. it can be org name too. e.g. TEAMMATES/repo

**Comment by dariusf** [comment]
Do you mean that "owner" is the wrong term in the `<owner>` text?

**Comment by damithc** [comment]
yes. `<owner/organization>`?

**Comment by dariusf** [comment]
Okay, I'll make the dialog slightly wider to accommodate that.
