### ISSUE TITLE
'force refresh' freezes HT

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#308]
What is it supposed to do?

**Comment by taychunmei** [comment]
It retrieves everything(issues, labels, milestones, collabs) again from GitHub, like when you first log in without a cached copy. 
It mimics what the browsers do: invalidating the cache and get everything again

I can put the loading bar to prevent users from thinking that HT is unresponsive.

**Comment by damithc** [comment]
yes, adding a progress dialog would be useful. It's nice if we can reload a single issue only. Can be done as a separate issue.
