### ISSUE TITLE
Allow shorter aliases for filter criteria

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#319]
e.g. m for milestone, s for state, o for open etc.

**Comment by rd1992** [comment]
currently we have auto completion for suggestions. Do we still want this then? user will have to remember all this

**Comment by damithc** [comment]
Auto-complete requires an extra TAB key. One solution is to make ':' accept
the autocomplete solution. So, typing 'a:' should result in 'assignee:'

**Comment by damithc** [comment]
Duplicate. closing.
