### ISSUE TITLE
`updated` filter qualifier

### ISSUE THREAD

**Issue by dariusf** [HubTurbo/HubTurbo#322]
It filters by number of hours for now.

**Comment by damithc** [comment]
Doesn't work for me. In fact if I use `updated:<24` in a filter, the whole filter doesn't work. I'm using V1.1.0

**Comment by dariusf** [comment]
You may have to clear the cache for it to work (force refresh, failing that
delete .hubturbocache). Caching doesn't work very well with changes to the
data model currently.
