### ISSUE TITLE
Wrong issue selected when selected issue disappears

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#334]
Select issue.
Switch to bView and do something that makes the issue no longer matching to the filter.
Switch to HT. Press down arrow before the refresh happens. the next issue is selected and loaded in bView. So far so good.
Refresh completes after a few seconds and the previously selected issue disappears, as it should.
Selection (which was already in the right issue) jumps one issue downwards and selects the wrong issue.

**Comment by lejolly** [comment]
i can't reproduce this bug either, seems to be fixed with the latest master?

**Comment by damithc** [comment]
Seems to be fine now.
