### ISSUE TITLE
Document keyboard shortcuts internally

### ISSUE THREAD

**Issue by dariusf** [HubTurbo/HubTurbo#342]

**Comment by rd1992** [comment]
@damithc could you please take a quick look at [Keyboard Shortcuts](https://github.com/HubTurbo/HubTurbo/wiki/Keyboard-Shortcuts)? Then we can close this issue.

**Comment by damithc** [comment]
Don't separate 'to be implemented'. Instead, use some other way (symbol, extra column, different font etc.) to show which ones are not yet implemented.
Use another column to show when the shortcut can be used? 
Let me have another look after addressing the above.

**Comment by rd1992** [comment]
Alright have updated the wiki again. Shortcuts in italics are not implemented . Also instead of having a third column i divided shortcuts by sections. Could you take another look? Thanks

**Comment by damithc** [comment]
Add a third column for detailed explanation.
Mention the meaning of italic text.
Not "S+O", it is "so (s followed by o)"
Use lower case letters for C, M, A etc.
Add this: Mi*d* size --> d (note the d in Mid is bold. Showing that
connection will help users to remember the shortcut)
Add a link to this page in the sidebar menu.

**Comment by damithc** [comment]
Here is an example:

| **Task**| **Shortcut**|**explanation**|
| ------------- |:-------------:|----|
| New Issue|`CTRL` + `i`| Loads the 'new issue' page in the Browser view|
| Close Panel|`CTRL` + `w`| Closes the panel in focus|
| :soon: *Maximize HT Window*|`x`|
| :soon: *Minimize HT Window*|`n`|
| :soon: *Automatically update filtered list*|`SPACE`|

**Comment by rd1992** [comment]
@damithc have given updated this again. Could you take a look? Also could you explain what Mid size is? I did not write an explanation for that yet

**Comment by damithc** [comment]
Mid size is the default size (one panel width). Coincidentally, 'd' goes
with 'default' as well.

**Comment by rd1992** [comment]
alright updated that in the wiki. if this seems alright I can start implementing them

**Comment by damithc** [comment]
Let's discuss when we meet next time. Meanwhile, think of other 'actions'
we want to bind to a keyboard shortcut. e.g.how to move focus out of the
filter box
Meanwhile, you can implement j k l m a keys.

**Comment by damithc** [comment]
More things to include:
For PR loaded in bView: load files tab
For any bView: scroll to top, bottom, page up/down, first unread comment

**Comment by damithc** [comment]
Shall we use panel view and browser view (pView and bView) to refer to the two views? We have been using HT previously, but that might not make sense to users. It makes more sense to say HT = pView +  bView
