### ISSUE TITLE
HT (re)creates some labels automatically

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#354]
HT seems to recreate deleted labels. specifically, status.open and status.closed

**Comment by damithc** [comment]
Do we create a default config file containing those two labels? If yes, does HT pushes those labels to the server?

**Comment by damithc** [comment]
users are not going to like this. Better fix it before we release it.

**Comment by dariusf** [comment]
I've fixed this.

In the spirit of removing unused code, should we also remove project configuration entirely? None of the [options](https://github.com/HubTurbo/HubTurbo/wiki/Configuration#project-configuration) do anything right now, and removing it will shave a bit off startup time.

**Comment by damithc** [comment]
Yes, we can remove the code. May be do it as a separate commit and mention
it clearly in the commit message so that we can recover the code later (if
we need to)?

**Comment by dariusf** [comment]
Yup, will do.
