### ISSUE TITLE
Some updates missing from cards in the feed

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#365]
![image](https://cloud.githubusercontent.com/assets/1673303/5678832/aff026c0-9831-11e4-8704-0dec473022eb.png)

**Comment by damithc** [comment]
For this issue, the card says @xeluna self assigned although I was the one who assigned @xeluna. Not sure if this is a problem with the GH api or a bug on our side. #244 may be related

**Comment by xeluna** [comment]
It's the problem with the GitHub API mentioned in #244. The actor is wrong. [This](https://api.github.com/repos/HubTurbo/HubTurbo/issues/events/216445642) is what the API returns for the assigned event in this issue.

**Comment by damithc** [comment]
That's what I thought too. See if there is a way to report this bug to
GitHub team.

**Comment by damithc** [comment]
Wrong actor issue aside, what about the missing updates issue?

**Comment by xeluna** [comment]
For referenced, it's not currently supported by the API. It's only an issue event if the reference is from a commit message and not another issue. I'll look into the closed issue.
