### ISSUE TITLE
Constant updates to status bar about next refresh hides parse errors

### ISSUE THREAD

**Issue by dariusf** [HubTurbo/HubTurbo#371]
We could partition the status bar into portions. The new status bar control in the [new version](http://fxexperience.com/2014/09/announcing-controlsfx-8-20-7/) of ControlsFX may help. Or we could partition the status bar ourselves, if we don't want to risk upgrading now.

**Comment by damithc** [comment]
We can try an 'experimental' upgrade to see if it breaks anything.
Alternatively, can postpone the upgrade until summer.
