### ISSUE TITLE
Issues of one project shown under another project

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#392]
See below. Happened during project switching.

![image](https://cloud.githubusercontent.com/assets/1673303/5836297/a0575914-a1ae-11e4-9984-048765ca4ede.png)

**Comment by damithc** [comment]
The corruption is semi-permanent. switching back to another project and switching back again didn't solve it. Only a hard refresh brought back the right data.

**Comment by damithc** [comment]
may be same as #379 
Disable switching until the current switching is completed?

**Comment by dariusf** [comment]
Yes, it's the same issue. It writes the wrong data to the cache, which is then loaded later. I'm hoping to address this with the refactoring.
