### ISSUE TITLE
is:pr filter not working

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#396]
This filter seem to keep breaking
![image](https://cloud.githubusercontent.com/assets/1673303/5885518/d6342f92-a3a9-11e4-9da0-b85ae3e4061d.png)

**Comment by dariusf** [comment]
Does this happen only after a while? I see the right issues on my end, but then I restart HT a lot.

**Comment by damithc** [comment]
It happens even after a restart, or a hard reset. I'm seeing it for the HT repo too.This issue itself appears under `is:pr` filter

**Comment by damithc** [comment]
The issues that appears under 'is:pr' filter disappears if I do an update to the issue. This issue no longer appears under the filter after I added the comment above.

**Comment by damithc** [comment]
I did a hard reset again to see what happens. This issue is back in the `is:pr` filter. It will disappear again after adding this comment.

**Comment by damithc** [comment]
Sorry, closed by mistake. 
Found something else. When I manually deleted the cache file and the config file for the repo, the filter started working again. So there was something wrong in the previous cache. A hard reset (Ctrl+F5) didn't solve it. But deleting the files manually did solve it. Not sure which file though. I deleted both.

**Comment by dariusf** [comment]
I see, it was most likely the cache (`.hubturbocache` directory) becoming corrupted. Maybe we should make Ctrl+F5 remove the cache files too.

**Comment by damithc** [comment]
I thought that's what is does :-p Yes, Ctrl+F5 should give the user a clean
start.
