### ISSUE TITLE
project switching gets disabled permanently

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#416]
At some point, it got disabled and never got enabled again.

**Comment by damithc** [comment]
Looks like it is not permanently disabled, but disabled most of the time. I'm connected to the TEAMMATES repo and project switching is available for 1-2 seconds for each minute. Can this be a result of slow connection?

**Comment by damithc** [comment]
It is a bit frustrating because when I switch to HT window to change the project, it triggers a refresh, which disables the switching for a long time.

**Comment by dariusf** [comment]
Yes, a slow connection will cause it to stay disabled. Maybe we could pause the timer during an update? So the next refresh isn't triggered so quickly after doing a long update.

**Comment by damithc** [comment]
Yes, that's a good idea.
