### ISSUE TITLE
Ctrl+down doesn't always jump to first issue

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#428]
In some cases, it jumps to an issue not at the top. At other times, it just shifts focus to the panel, not to an issue

**Comment by rd1992** [comment]
@damithc the key combination only works to go from filterbox to issue. Its not a universal combination. I thought we decided we already have home and end key to jump to the top and bottom of the list respectively?

**Comment by damithc** [comment]
Yes, I'm referring to going from filter box to first issue. Sometimes it
works, sometimes it doesn't.

**Comment by damithc** [comment]
Ok, I have more specifics. Here's how to reproduce.
1. type a filter and press enter
2. press ctrl+down. It jumps to the first issue and loads it in bView.
3. Navigate (down arrow) to the 2nd issue
4. Click on the filter box again and press ctrl+down again
5. The first issue is loaded in the bView correctly. But the HT highlights 2nd issue (the last issue that was selected before). So the problem is in highlighting the issue on the list.

**Comment by rd1992** [comment]
Yeah i got the same behaviour. CTRL + down does work but its the highlighting which is the problem.
