### ISSUE TITLE
Shows issues from wrong project

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#430]
This happened when I loaded powerpointlabs repo for the first time. A hard refresh fixed the problem.
![image](https://cloud.githubusercontent.com/assets/1673303/6166653/ed233606-b2ec-11e4-9890-4d2f4f4b783a.png)

**Comment by dariusf** [comment]
Do you have the logs for this?

**Comment by dariusf** [comment]
Hmm, according to the logs the right issues from powerpointlabs/repo were downloaded. If this happens again could you try to create a new panel, and see if the new panel contains wrong data? It could be that they weren't displaying correctly.
