### ISSUE TITLE
Project switching is hampered by 'syncing'

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#432]
Every time I want to switch projects, I have to wait for a while because HT starts syncing as soon as I click on the window.

**Comment by damithc** [comment]
At HT gaining focus, may be update the selected issue only (instead of triggering a full scale sync)?

**Comment by dariusf** [comment]
Somewhat addressed by making clicks on the project-switching box not trigger syncs (#477) and not syncing if there was no change to the page (#457). Will also fix by looking into why syncs take inordinately long sometimes (#431).
