### ISSUE TITLE
HT response comes after bView response

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#447]
When I do something on the HT window, I expect HT window to respond first before bView responds. e.g. pressing down arrow should move the selection to the next issue before loading it in bView. Currently, the bView responds first, which is odd, and was not the case in V1.8.

**Comment by damithc** [comment]
Perhaps this was the case all along, but I'm noticing it now because of the increased lag? I'm not sure.

**Comment by rd1992** [comment]
hmm. just to clarify which window is on top (mean has system/keyboard focus)?

**Comment by damithc** [comment]
HT has focus.

**Comment by damithc** [comment]
I notice this problem only during the laggy behavior reported in #448

**Comment by damithc** [comment]
This is not a big problem if there is no lag

**Comment by rd1992** [comment]
Has been fixed in latest version of HT
