### ISSUE TITLE
HT becomes laggy after a few minutes of use

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#448]
After a few minutes of use (try a few filters, load a few issues, etc.), HT response becomes quite laggy. Painfully slow to use after that. No unusual increase in memory usage or cpu usage though.

**Comment by damithc** [comment]
I wonder if it is the sync operation that is causing this lag.

**Comment by damithc** [comment]
This version is unusable at this point. :-p At times, even a keypress can take 10-15 seconds to respond. See if you can reproduce the problem.

**Comment by damithc** [comment]
Are we updating the comment count in every panel? The lag may be related to more intensive read operations to update comments count.

**Comment by damithc** [comment]
Seems to be related to the `updated` filter, and possibly, the detection of new comments. I don't notice it when I don't have an `updated` filter

**Comment by dariusf** [comment]
Does HT go back to normal after the lag stops?

Couldn't reproduce the lag, but I was getting exceptions consistently (index out of bounds; my bad). Those might be the cause of the problems. I'll fix those now and release V1.9.1.

**Comment by dariusf** [comment]
Been trying to upload for a while but it isn't going through. Will try again tomorrow.

**Comment by damithc** [comment]
The persists as long as I have an `updated` filter. I checked in both comps.

**Comment by dariusf** [comment]
Is the lag better improved in V1.9.1?

**Comment by damithc** [comment]
Not much. The lag is back if I use an `updated` filter. I think the two
problems feed off each other. `updated` filters are naturally slow and the
sync loop makes it worse.

**Comment by dariusf** [comment]
I'll fix the sync loop first. The updates will happen less frequently then.

**Comment by dariusf** [comment]
Fixed the overly-frequent updates and released V1.9.2.

**Comment by damithc** [comment]
Seems to be ok in V1.9.2. I see the progress bar going twice at a time, but no more than that. Couldn't reproduce the lag in office comp. I'll check the home comp later.

**Comment by damithc** [comment]
The lag is still there, but less noticeable. It is caused by the feed panel. Possibly it has some blocking behavior during updates. The first part of the sync goes fine, but the UI becomes laggy during the 2nd part of the sync if there is a feed panel open.

**Comment by damithc** [comment]
Close this one and open a separate issue to deal with lagginess of the feed?

**Comment by dariusf** [comment]
Yup, that's exactly what happens -- the feed is updated on the UI thread after the regular sync, but before the issue list is updated. Created the issue.
