### ISSUE TITLE
User can jump to comment box using a hotkey

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#449]
When an issue is selected in HT (and the issue is loaded in bView), we can use the 'C' key to jump to the comment box of the issue.

**Comment by rd1992** [comment]
and the keyboard focus should go to the bView too? Like the user should straightaway start typing?

**Comment by damithc** [comment]
Yes, that's the idea

**Comment by damithc** [comment]
There should be only one `status.*` label per issue. Remove the previous status label before adding a new one.

**Comment by damithc** [comment]
Nice. Definitely a time saver :-)
