### ISSUE TITLE
Sync happens more frequently than intended

### ISSUE THREAD

**Issue by dariusf** [HubTurbo/HubTurbo#456]
The problem is that the sync doesn't always respect the time kept by the visual timer shown to users. It may happen during project switching as in the past.

This could be the cause of the concurrency issues in #430, as well as the progress bar restarting in #444.

**Comment by damithc** [comment]
I did notice the progress bar coming on when the counter is not at 60. This happens even in V1.9.1. But those unexpected syncs don't go into a loop. The syncs that go into a loop are the ones that happens at 60 or the ones triggered by HT gaining focus.

**Comment by dariusf** [comment]
Yes, it hasn't been fixed yet. Hoping to tackle the lag problem first.
