### ISSUE TITLE
Upon regaining focus, sync only if the bView has changed

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#457]
This should reduce the annoyance of syncing everytime HT gains focus.
One simple minded way to o detect if the bView has changed: HT can keep a copy of the HTML loaded to bView and compare it with the current HTML.

**Comment by rd1992** [comment]
Should also fix [https://github.com/HubTurbo/HubTurbo/issues/477]

**Comment by rd1992** [comment]
Issue mentioned in https://github.com/HubTurbo/HubTurbo/pull/483 has been fixed

**Comment by dariusf** [comment]
Fixed in #492.
