### ISSUE TITLE
HT fails to get a proper handle on the bView if user interacts with other windows during startup

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#467]
If the user interacts with other windows intensively during HT startup, the bView handle is not acquired properly by HT.

**Comment by rd1992** [comment]
Cant reproduce but switching to process id of chrome window to get the handle instead of finding it directly.

**Comment by damithc** [comment]
To reproduce, try spam-clicking another window while HT starts up.

**Comment by rd1992** [comment]
hmm. Just to be more specific when you interact with the other windows does HT window behave okay? Like its in the foreground? what i am seeing is that HT window itself remains in the background and trying to bring it in front results in the other window stealing focus. If you could clarify this it will help  isolate the problem.

**Comment by damithc** [comment]
Tried several times. Can't reproduce it now. I'll report back if it happens
again. The previous time I was able to reproduce it couple of times.

**Comment by damithc** [comment]
Happened once more (the first time I tried V2.0). But wasn't able to reproduce it afterwards.

**Comment by damithc** [comment]
Interestingly, the first time I try a new version, this problem happens. It happened for the last three versions at least. But it seems to be fine in subsequent runs.

**Comment by rd1992** [comment]
Still cant figure out what causes this. However handler will be acquired based on name instead of the fact that HT is the topmost window in Z order at startup.

**Comment by damithc** [comment]
Still not fixed :-p Still happens occasionally

**Comment by rd1992** [comment]
Ok i need to meet you and see how you reproduce this :p

**Comment by damithc** [comment]
I have no idea how to reproduce it either. It just happens sometimes. Do some intense logging for the section of the code so that we can examine what happened after the fact.

**Comment by damithc** [comment]
In most cases, this happens the first time I run a new resources.jar file. Just now it happened to V2.1.1

**Comment by damithc** [comment]
Happened again when I ran 2.2.0 for the first time :-p
