### ISSUE TITLE
Show download progress during initial issue download

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#469]
Downloading issues for the first time can take a long time during which the user might think the app is stuck. Perhaps we can show some kind of progress (e.g. issue count downloaded) in addition to the progress bar.

**Comment by damithc** [comment]
We can also show a warning message to alert the user that it's going to take a while and it's only for the first time.

**Comment by dariusf** [comment]
Progress is now shown in all progress dialogs (initial load, repo switch, force reload).
