### ISSUE TITLE
Milestones are not updated when dragging issues to milestones

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#472]
e.g. dragging to `milestone:V1.9 is:open` seem to change the milestone in HT, but it is not updated in the server.

**Comment by damithc** [comment]
In fact this is not due to the extra condition. The 'drag to change milestone' behavior stopped working completely. I had to restart to get it working again.

**Comment by dariusf** [comment]
Drag and drop has been removed for now.
