### ISSUE TITLE
Syncing stuck halfway

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#475]
V2.0
This happened during the initial sync after login
![image](https://cloud.githubusercontent.com/assets/1673303/6325062/76848696-bb7d-11e4-8f45-7285ce6bea0e.png)

**Comment by damithc** [comment]
Happened again. Both times it was the TEAMMATES repo.

**Comment by dariusf** [comment]
That stage is when the changes to issues are retrieved, which can take quite long. Did the login dialog go away?

**Comment by damithc** [comment]
Yes, this is after the login dialog went away. Didn't happen in my other comp though.

**Comment by damithc** [comment]
This is not limited to the first sync. Happened again in a subsequent sync. However, it gets unstuck after a while. So it could be just a slow connection.

**Comment by damithc** [comment]
This seems to be an issue related to bigger projects and possibly a slow connection to GitHub. It appears like stuck for a long time, but eventually gets unstuck. Doesn't seem to affect hubturbo or powerpointlabs, but affects teammates at times. With a huge project like homebrew, it stays stuck for 10+ minutes.

**Comment by damithc** [comment]
Sometimes a sync of a large project can appear stuck for 5-10 minutes. I get frustrated and restart HT. The same project then can sync in a few seconds. :-p

**Comment by dariusf** [comment]
It's likely a problem with the GitHub API, the Java interface to it (this is most likely), or how we're using it. Seems that sometimes lots of changes are logged even when nothing happened. These are the relevant lines from the log from the past couple of days, along with how many times they occurred:

```
60 issues changed/added since last sync (x27)
472 issues changed/added since last sync (x4)
1 issues changed/added since last sync (x1)
2 issues changed/added since last sync (x5)
```

**Comment by damithc** [comment]
I checked the log when this happened again. Seem 3000+ issues were reported as 'updated'. Need to figure out where the bug is and report to the relevant developers.

**Comment by damithc** [comment]
Unfortunately, this problem seem to remain at V2.2.0 even after the eGit update.

**Comment by dariusf** [comment]
I've been working on this since yesterday. The problems were on our end. We're now able to correctly identify when nothing has changed and get a 304 response from GitHub, which speeds things up a lot. Still have a bunch of edge cases to handle though.

One caveat: the changes I made require a deletion of the cache. This issue requires #332 to be in.

**Comment by damithc** [comment]
Glad to hear the problem was on our end. Much easier to fix our end than
theirs. :-)
