### ISSUE TITLE
Clicking on project switcher triggers a sync (sometimes)

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#477]
Related to #468 
I'm able to dropdown the project selection, but it triggers a sync before I'm able to switch the project.

**Comment by damithc** [comment]
The problem occurs only when HT gains focus from the click on the project switcher. The focus is initially on some other window and then the user clicks on the project switcher. It should not trigger a sync, but it does, preventing the very thing the user wanted to do.

**Comment by dariusf** [comment]
I can't reproduce this. Tested that scenario repeatedly but couldn't get it to sync (on Mac, though).

The focus event comes before UI focus events, so I implemented this using a small (100 ms) delay that starts from after the window is focused. Maybe I could try increasing the delay? It would be slightly less responsive but possibly more stable.

**Comment by damithc** [comment]
Yes, can try that.
I can reproduce this in both computers. May be it is a Windows thing. The dropdown drops down momentarily before the sync starts.

**Comment by rd1992** [comment]
clicking on the issue box does not trigger a sync. Seems to work fine for me.

**Comment by damithc** [comment]
Good. Note that the problem was observed when the click on the project
switcher brings focus to HT, not just any click.

**Comment by rd1992** [comment]
yeah i checked for that in particular

**Comment by damithc** [comment]
Seems to be fine in V2.0.1
