### ISSUE TITLE
bView stops responding after alerts in window

### ISSUE THREAD

**Issue by rd1992** [HubTurbo/HubTurbo#484]
to reproduce: try deleting a comment on an issue. Alert pops up for confirmation. HT throws an exception. is also tied to https://github.com/HubTurbo/HubTurbo/issues/471

**Comment by damithc** [comment]
Yup. Good job spotting it.

**Comment by rd1992** [comment]
@damithc you want to assign a priority?

**Comment by damithc** [comment]
If there is no 'clean' fix readily available, can go for a dirty fix such as restarting the bView.

**Comment by rd1992** [comment]
Selenium does throw this exception in this case of alerts.
org.openqa.selenium.UnhandledAlertException: unexpected alert open
I guess alerts can be handled better than us restarting the window. Looking into it now.

**Comment by rd1992** [comment]
well this is fixed in the new version of chromedriver. I believe we should update to 2.14 (currently on 2.13)

**Comment by damithc** [comment]
Yes, let's do that.
