### ISSUE TITLE
Implement keyboard Shortcuts (Navigational Shortcuts)

### ISSUE THREAD

**Issue by rd1992** [HubTurbo/HubTurbo#488]
Implement the coming soon keyboard shortcuts in the Navigation section documented [here](https://github.com/HubTurbo/HubTurbo/wiki/Keyboard-Shortcuts)

**Comment by damithc** [comment]
Issue title needs to be more specific. Implementing all pending shortcuts is too much to do in one issue.

**Comment by rd1992** [comment]
I have updated the title. Implementing only navigation related ones for this issue.

**Comment by rd1992** [comment]
in commit https://github.com/HubTurbo/HubTurbo/commit/b8a1a6cec31cbf9b3533ccc0d3482d35e63fc250
-implemented j, k for moving up/down in issue list.
-double tap SPACE to move from filterbox to issue list and back. (this will only occur if the two taps are within a second of each other)
