### ISSUE TITLE
Ctrl+W sometimes doesn't work

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#489]
Supposed to close the current panel. Sometimes it works, sometimes it doesn't.

**Comment by damithc** [comment]
This works only if there is an issue selected. If I close the panel with the selected issue, an issue is no longer selected, and the shortcut doesn't work.

**Comment by dariusf** [comment]
If I recall correctly this was done intentionally, because there's no more selection then and no panel to close. Maybe on closing we can move selection to the previous panel? Then the next Ctrl+W would close that.

**Comment by damithc** [comment]
That reasoning is correct, but the behaviour does not follow that exactly.
Sometimes the UI shows a panel as selected (e.g. the focus is in the filter
box) but Ctrl+W wont close it unless an issue is selected in that panel.
Yes, closing a panel should move focus to another panel.
