### ISSUE TITLE
Don't load issue if 'passing through' the issue

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#490]
Currently, user needs shift+up/down to pass through issues without loading them. This is inconvenient. It is better if HT can auto-detect 'passing through' (e.g. if the selection doesn't stay on the issue for 0.5 seconds) and avoid loading such selections.

**Comment by rd1992** [comment]
Just to clarify a question (am going to use an example to describe this):
1. User currently is on issue 1. Issue 1 is being shown in the Bview.
2. User presses a down key quickly thrice and lands on issue 4.

Now what should be shown in the bview? It should load issue 4? or should it keep showing issue 1 till ENTER is pressed (in my current implementation, the user needs to press enter for Issue 4 to be shown)

**Comment by damithc** [comment]
It should show issue 4 without having to press ENTER.  Once this feature is done, user will never have to press ENTER to load an issue.
