### ISSUE TITLE
Save login credentials to avoid typing password everytime

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#491]
The web ui doesn't require users to login every time. May be we can do something similar in HT?

**Comment by damithc** [comment]
@rd1992 can you look into this one?

**Comment by rd1992** [comment]
@damithc on it.

**Comment by rd1992** [comment]
just to confirm should the user be prompted with the login dialog (with details filled in) or be presented with the HT window straight?

**Comment by damithc** [comment]
Go to HT straight? But we should have a 'Login' and 'Logout' options somewhere in the menu, in case the user wants to change the login or logout. Note that we have to store the password/cookie in a secure way.

**Comment by rd1992** [comment]
alright. yeah saving is not an issue. we can encrypt details using [Preferences API] (http://docs.oracle.com/javase/1.5.0/docs/guide/preferences/index.html)

**Comment by rd1992** [comment]
Have made some initial commits. Some points to note:
1. Logout will quit the app and destroy the saved password without prompt. Maybe a confirmation box should be added?
2. Automation of login seems to put focus on browser instead of HT (HT keeps blinking on the taskbar).

**Comment by dariusf** [comment]
We'll need to save the password. It's needed to log in when the browser view loads.

Is this considered secure? It can be reverse-engineered, but then the data only resides on the user's computer. (We could generate a random key but that would also reside on the user's computer...)

**Comment by rd1992** [comment]
I did save the password in the sessionconfig file. 
I am using a random key to encrypt the password before i save it to file. I decrypt it using the same key before signing in. 
as for safety there is no way around it if we have to decrypt it. We have to either:
1. store the password in plain sight
2. store the encrypted password and have the encryption key on hand (needs to be saved somewhere)

1. is obviously a bad thing to do. 2. is what am currently doing

**Comment by damithc** [comment]
Is 2 the standard solution? How do others do it? There are many other apps
that seem to store the password somewhere.

**Comment by rd1992** [comment]
Skype stores the encrypted hash of the password in the 'config.xml' located in Skype's user profile directory. Thats what we are doing now.

**Comment by damithc** [comment]
In future, may be we can ask the user whether it ok to save the password.
and recommend the user not to choose 'yes' if it is a shared/unsecure
computer.

**Comment by dariusf** [comment]
What Skype does is a bit different: it stores the hash of the password, then uses the hash for authentication. There's no way to recover the password from the hash. They don't need the password text after the initial login anyway.

Our current method could be improved by using a variable or randomised key to encrypt the password. That seems to be [what Chrome does](http://securityxploded.com/googlechromesecrets.php).

**Comment by rd1992** [comment]
@damithc had a question regarding this. Login works but as i mentioned two weeks ago, the browser has focus. Running native code is not an option. So there are a couple of ways we can go with this:
1. Simulate ALT + TAB ( Command + TAB for mac) to bring HT focus.
2. Initiate browser before showing the HT window (there would be a chrome window open before login)

Personally i like option 1. Though i would like to hear your thoughts.

**Comment by damithc** [comment]
option 1 may not work all the time right? Start up take some time and the
user is likely to click on other windows during that time. I know I do :-)

**Comment by damithc** [comment]
Can we have a native hot key binding that always brings up HT? e.g.
Windows+H If we can, then we can simulate that key combination?

**Comment by damithc** [comment]
Another option is to have a splash screen. We show the splash screen
immediately, followed by bView, followed by pView. Would that work? It also
solves the current problem we have: nothing shows up for a long time after
starting HT.
