### ISSUE TITLE
Upgrade to JavaFX 8u40

### ISSUE THREAD

**Issue by dariusf** [HubTurbo/HubTurbo#496]
JDK 8u40 was just released. There are a few changes which benefit us:

- the listview performs a lot better (motivated by [Flowless](https://github.com/TomasMikula/Flowless), a third-party project)
- improved keyboard navigation ([accessibility improvements](http://jaxenter.com/java-8-receives-improved-memory-javascript-support-115142.html))
- a few dependencies have been integrated into the JDK (openjdk-dialogs), so we no longer need to include them

We've also been conservatively staying on the same version of JavaFX since the beginning (a bit under a year old) this should improve things in general.

**Comment by damithc** [comment]
Upgrade now or hold off till end of semester?

**Comment by dariusf** [comment]
Seems to be a safe upgrade. I've tried it out for a while and everything works as it should.

Also, since we were on the topic of navigation, some things may have already been implemented in JavaFX, so it might change our considerations.

**Comment by damithc** [comment]
What about existing users? They have to upgrade java right?

**Comment by dariusf** [comment]
Yes, but it should happen automatically. With this we have gone from using an explicitly-included, older version of JavaFX to using the system JDK's bundled version.

**Comment by damithc** [comment]
Ok then, we can give it a try.

**Comment by damithc** [comment]
The memory usage seems to be lower than before (although still high).
