### ISSUE TITLE
Deleted labels keep reappearing

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#499]
Some of the old labels e.g. `status-closed` keep reappearing although I have deleted them many times. Is HT causing this? I remember older versions of HT had a behavior like that.

**Comment by dariusf** [comment]
I should have removed all the code which recreates them. Are they being recreated in GitHub as well?

**Comment by damithc** [comment]
Yes, on GitHub. I deleted them on GitHub yesterday and they have not
appeared again so far. May be there is one user who has an old config file
containing the old list of labels?

**Comment by dariusf** [comment]
Possibly... but they would need to have an old version too, at least from before mid-December.
