### ISSUE TITLE
Project switcher does not show the selected project

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#501]
![image](https://cloud.githubusercontent.com/assets/1673303/6543949/da61730c-c570-11e4-82b8-1ad9010180ea.png)

**Comment by dariusf** [comment]
How did this happen? When it started there was nothing there?

**Comment by damithc** [comment]
The list of projects is still there in the dropdown. But the 'selected'
value remains empty no matter which project is loaded.

**Comment by dariusf** [comment]
Managed to reproduce this. The problem was that we never set the value correctly when switching repository. Strangely it didn't surface until now, so it was probably the JavaFX upgrade that caused it.
