### ISSUE TITLE
Issues shown in HT not getting updated

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#502]
![image](https://cloud.githubusercontent.com/assets/1673303/6545083/47a2e4a8-c5af-11e4-8b19-a5b023bcf8aa.png)

**Comment by damithc** [comment]
When I use HT on the HT project, I don't observe this problem. But I observe it when I use it on TEAMMATES project. 
It also looks like a long delay in the updates appearing in pView rather than updates not appearing at all.

**Comment by damithc** [comment]
For example, I added these two labels within a minutes of each other. The first label appeared in pView after a long delay. The second one has not appeared yet. Could be a bug/delay on the GitHub API.
![image](https://cloud.githubusercontent.com/assets/1673303/6545154/bb20ce9c-c5b2-11e4-8543-14d866e2989f.png)

**Comment by damithc** [comment]
By the way, this example issue in the above comment doesn't appear in the `updated:2` filter, so HT is unaware that the issue has been updated recently.

**Comment by damithc** [comment]
After 30 minutes, the 2nd label has not shown up in the pView. So I don't think it is going to show up at all. Only a hard refresh brought that label into the pView.

**Comment by damithc** [comment]
Tried on PowerPointLabs project. Seems to work there too. So it is either specific to TEAMMATES project or affects bigger projects.

**Comment by dariusf** [comment]
It's definitely an API problem, though on whose end I'm not sure (similar to syncs taking very long).

**Comment by damithc** [comment]
Let's work on narrowing it down to whose bug it is. If it is GitHub, I'll
find a way to get in touch with them about it.

**Comment by damithc** [comment]
It may be the case that updates take time to propagate through GitHub servers.
Try adding a safety buffer when requesting updates. e.g. if the last update was done T minutes ago, request for the updates done within the last T+10 minutes, to allow for a 10 minute propagation delay.

**Comment by damithc** [comment]
Seems there are recent releases of eGit. Isn't that the one we are using? https://github.com/eclipse/egit-github/releases

**Comment by dariusf** [comment]
Yes, that's the one. We'd been watching the Maven repository and missed the releases... I'll try out the latest releases.

**Comment by damithc** [comment]
Things seems to be better with the new eGit version
