### ISSUE TITLE
Implement keyboard Shortcuts (BrowserView and PanelView)

### ISSUE THREAD

**Issue by rd1992** [HubTurbo/HubTurbo#506]
#### Browser view
* scroll to top t
* scroll to bottom b
* page up/down u/d

#### Panel view
* ma[x]imize Ctrl+x
* mi[n]imize Ctrl + n
* [d]efault/mi[d] size Ctrl+d

**Comment by rd1992** [comment]
@damithc had a query regarding scrolling. what happens if the user holds u/d? currently he will have to repeatedly press u or d to scroll. Long press of those keys doesnt continue scrolling

**Comment by damithc** [comment]
Should be ok.
