### ISSUE TITLE
Increase the time window for double space

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#510]
Currently, sometimes my double space is not fast enough to get recognized as double space. What's the duration now? Can you increase the duration a bit more?

**Comment by rd1992** [comment]
Currently it is 1 second. However checkout #513.

**Comment by rd1992** [comment]
@damithc is this still an issue you face?

**Comment by damithc** [comment]
At times the double space clears the filter box before jumping to the issue
list. Not sure if it is something to do with he speed though. I was pretty
fast in some of those occasions.

**Comment by lejolly** [comment]
is the time window sufficient now?

**Comment by damithc** [comment]
seems to be fine now
