### ISSUE TITLE
NumberFormatException during login

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#538]
![image](https://cloud.githubusercontent.com/assets/1673303/6819180/0351f7c0-d2f8-11e4-8f96-3f5f01f09899.png)

**Comment by rd1992** [comment]
@damithc this happens because of the cache thing. Did you delete it manually?

**Comment by damithc** [comment]
I though HT is supposed to delete the cache automatically. I deleted the
cache and the error went away.

**Comment by rd1992** [comment]
it depends how you updated HT to the latest version.

**Comment by rd1992** [comment]
@dariusf can explain this better

**Comment by dariusf** [comment]
Yup, it's due to the old cache. The cache only gets deleted if HT was updated via the auto-updater (that's how we know that an update happened -- the auto-updater starts HT with some special parameters).

**Comment by damithc** [comment]
Makes sense. closing.
