### ISSUE TITLE
Space doesn't apply the filter

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#543]
When I'm typing a filter, typing a space should apply the filter.

**Comment by rd1992** [comment]
seems to work for me when i start typing is: issue. could you explain what you were typing?

**Comment by damithc** [comment]
![image](https://cloud.githubusercontent.com/assets/1673303/6825162/5a6a13b8-d333-11e4-88e5-cbd35deb232b.png)

**Comment by rd1992** [comment]
weird. I tried the same thing and i got the desired functionality. @dariusf can you try replicating this?

**Comment by dariusf** [comment]
It works for me only when there is selected text in the filter box and I press space. Typing normally doesn't seem to trigger it.

**Comment by damithc** [comment]
Still doesn't work, unless the filter is highlighted.

**Comment by dariusf** [comment]
This wasn't included in V2.4.0. I'll make another release.
