### ISSUE TITLE
Last space should be trimmed when the filter box gains focus

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#546]
When the filter box gains focus, the trailing space should be trimmed so that the user will type a space if he/she wants to continue adding to the existing filter.

**Comment by rd1992** [comment]
hmm. currently when we press double space to go to from list to filterbox everything gets selected and the caret is at the start of the filter typed (if any filter exists that is). You then press another space and then start typing your new filter. Are you saying that the space which exists at the end of the applied filter should not be there when the text gets selected?

**Comment by damithc** [comment]
Yes. If a space is already there, it's not intuitive for the user to type
another space.
