### ISSUE TITLE
Ctrl+X and Ctrl+D don't work

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#548]
Supposed to maximize and resize, but don't seem to work. Ctrl+N works though. I'm thinking if we should have just one shortcut for this, to cycle between the three sizes. Ctrl+R for resize? May be we can reassign Ctrl+N as an alternative for 'new panel'?

**Comment by rd1992** [comment]
these shortcuts work everywhere except in the filterbox. is that where you were trying them?

**Comment by damithc** [comment]
1. Yes, doesn't work in filter box. Is should right?
2. At other places (e.g. while on the issue list), the success rate is low. For example, sometimes Ctrl+D simply registers as D and moves the focus to a different panel. I tried using both my Ctrl keys. Not sure it is a problem with my keyboard.

**Comment by damithc** [comment]
It cannot be an issue with my Ctrl key because Ctrl+I and Ctrl+P works fine.

**Comment by rd1992** [comment]
Filterbox i'll fix. I did it by design. But i cant be sure of the second point you raised.

**Comment by damithc** [comment]
I'll try with my other computer and confirm the 2nd point.

**Comment by damithc** [comment]
Tried with other computer. Same behavior. When the focus is on the issue list, a quick Ctrl+X/D does not register. They work only if I press Ctrl key first, pause a moment, and press X/D slowly and deliberately.
