### ISSUE TITLE
Ctrl+I does not transfer focus to bView

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#552]
The focus seem to remain in pView. Tried a few times.

**Comment by damithc** [comment]
This seems to be an issue of not getting a proper handle on bView window. Not specific to Ctrl+I. Went back to normal after restarting.

**Comment by lejolly** [comment]
@ianngiaw are you able to reproduce this bug?

**Comment by ianngiaw** [comment]
@lejolly I'm not able to reproduce it for Ctrl + I, but I can for Ctrl + L. I'm not sure what the default behaviour for either of them should be though.

**Comment by lejolly** [comment]
check the code in browsercomponent I think and see if bringtotop is being called for that particular function
