### ISSUE TITLE
Users can access HT using a universal hotkey

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#553]
e.g. Win+H

**Comment by rd1992** [comment]
Picking this up for this milestone. What is the intended behavior?
1. Is this shortcut to launch the app? (will require 3rd party library)
2. What should happen if the app is running? Should the application come into focus? (again might not be cross platform)

Also what would be the equivalent of this in OS X and Linux? `Cmd + H` is already a system shortcut in OS X which can't be overriden

**Comment by damithc** [comment]
If it is already running, it should bring to focus. 
Use a three key combination?
