### ISSUE TITLE
HT gets stuck during project switching

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#554]
The progress bar keeps going for ever. Happened twice. May be connection timeout is not handled properly?

**Comment by dariusf** [comment]
Were there any exceptions in the log? Any weird behaviour like the progress bar constantly repeating, or like the progress bar showing when the project-switching box was enabled?

**Comment by damithc** [comment]
There was no error message in the log when it got stuck today.
No, the box was disabled. No other weird behavior. I had to restart HT to
get out of it.

**Comment by dariusf** [comment]
I checked for connection timeout errors not being handled but couldn't find anything. Could you post the parts of the log leading up to the getting stuck? So I can tell at which point it stopped.

**Comment by damithc** [comment]
I'll do that next time it happens.

**Comment by damithc** [comment]
Here's the tail of the log when it got stuck. Not sure if it is related to the DDoS attack GitHub is facing these days.
```
1837850 29 Mar 2015 11:42:45 INFO Model [JavaFX Application Thread] - Loading collaborators from cache...
1837851 29 Mar 2015 11:42:45 INFO Model [JavaFX Application Thread] - Loading labels from cache...
1837851 29 Mar 2015 11:42:45 INFO Model [JavaFX Application Thread] - Loading milestones from cache...
1837861 29 Mar 2015 11:42:45 INFO Model [JavaFX Application Thread] - Loading issues from cache...
1837879 29 Mar 2015 11:42:45 INFO CacheFileHandler [Thread-12] - Wrote to file for repo hubturbo/hubturbo with last checked time: Sun Mar 29 11:42:45 SGT 2015
1838685 29 Mar 2015 11:42:46 INFO UpdateService [pool-4-thread-1] - UpdateService response: 304
1838685 29 Mar 2015 11:42:46 INFO UpdateService [pool-4-thread-1] - Nothing to update
1838686 29 Mar 2015 11:42:46 INFO ModelUpdater [pool-4-thread-1] - No collaborators to update
```

**Comment by dariusf** [comment]
Is that the full log? What I normally get is something like this (a few extra lines at the beginning, which shouldn't have been skipped):

```
36880 29 Mar 2015 14:45:15 INFO ModelUpdater [pool-4-thread-1] - Updating model...
36881 29 Mar 2015 14:45:15 INFO UpdateService [pool-4-thread-1] - Starting update of /collaborators with ETag 4dd17e5d353055796a14b851f3f78e1a
38348 29 Mar 2015 14:45:16 INFO UpdateService [pool-4-thread-1] - UpdateService response: 304
38349 29 Mar 2015 14:45:16 INFO UpdateService [pool-4-thread-1] - Nothing to update
38350 29 Mar 2015 14:45:16 INFO ModelUpdater [pool-4-thread-1] - No collaborators to update
```

**Comment by damithc** [comment]
Here's the full tail, upto the point I killed HT.
```
1784350 29 Mar 2015 11:41:51 INFO UI [JavaFX Application Thread] - Triggered event IssueSelectedEvent
1802173 29 Mar 2015 11:42:09 INFO UI [JavaFX Application Thread] - About to trigger event IssueSelectedEvent
1802173 29 Mar 2015 11:42:09 INFO BrowserComponent [JavaFX Application Thread] - Showing issue #3203
1802173 29 Mar 2015 11:42:09 INFO UI [JavaFX Application Thread] - Triggered event IssueSelectedEvent
1837810 29 Mar 2015 11:42:45 INFO UI [JavaFX Application Thread] - Switching repository to hubturbo/hubturbo in progress
1837816 29 Mar 2015 11:42:45 INFO ModelUpdater [pool-4-thread-1] - Updating model...
1837816 29 Mar 2015 11:42:45 INFO UpdateService [pool-4-thread-1] - Starting update of /collaborators with ETag 41db1bae08c04806cf5bb10033451363
1837827 29 Mar 2015 11:42:45 INFO ServiceManager [Thread-12] - Loading from cache...
1837850 29 Mar 2015 11:42:45 INFO Model [JavaFX Application Thread] - Loading collaborators from cache...
1837851 29 Mar 2015 11:42:45 INFO Model [JavaFX Application Thread] - Loading labels from cache...
1837851 29 Mar 2015 11:42:45 INFO Model [JavaFX Application Thread] - Loading milestones from cache...
1837861 29 Mar 2015 11:42:45 INFO Model [JavaFX Application Thread] - Loading issues from cache...
1837879 29 Mar 2015 11:42:45 INFO CacheFileHandler [Thread-12] - Wrote to file for repo hubturbo/hubturbo with last checked time: Sun Mar 29 11:42:45 SGT 2015
1838685 29 Mar 2015 11:42:46 INFO UpdateService [pool-4-thread-1] - UpdateService response: 304
1838685 29 Mar 2015 11:42:46 INFO UpdateService [pool-4-thread-1] - Nothing to update
1838686 29 Mar 2015 11:42:46 INFO ModelUpdater [pool-4-thread-1] - No collaborators to update
2153594 29 Mar 2015 11:48:00 INFO TickingTimer [JavaFX Application Thread] - Stopping TickingTimer Sync Timer
2154595 29 Mar 2015 11:48:01 INFO TickingTimer [JavaFX Application Thread] - Successfully stopped TickingTimer Sync Timer
2154605 29 Mar 2015 11:48:01 INFO BrowserComponent [JavaFX Application Thread] - Quitting browser component
```

**Comment by damithc** [comment]
Note that I closed the progress dialog at some point because it was simply stuck in the 'loading issues ..' stage for 6 minutes.

**Comment by dariusf** [comment]
Okay, I can reproduce it reliably: the few lines at the beginning were absent because they were happening out of order.

The problem is a 60s-sync right as you switch repo. There's a very small time frame between the timer reaching 0 and the repo-switching box getting disabled where you can trigger a switch. The sync will still proceed, then get stuck (so at least it doesn't corrupt the cache). The repo-switch needs to sync to complete, so it too gets stuck.

The best I can do is to cancel the sync that starts as you switch. It's not an ideal solution, but it avoids both cache corruption and deadlocks. That small time frame is an inherent limitation with the way we do things (timer thread interfacing directly with the UI).

I imagine there is an architecture that avoids this problem, where all network operations are async and the UI just acts as a view of the data, allowing project switching and syncing to happen independently. That would require quite a bit more work though.
