### ISSUE TITLE
Tidy up the start up

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#569]
Start up is the first impression a new user gets, so we should tidy it up.
The small chrome driver window doesn't look good. May be use it as a splash screen?
It is also desirable to shorten the delay between the time user clicks the jar file and the time some visible response appears.

**Comment by rd1992** [comment]
Well i have reset the size of the chrome window to be the size we were using earlier. Still does not look great. However this issue also highlights a deficiency in our workflow. We can bypass the whole logging into github procedure in the bview and load the issue directly. Details can be found [here](https://developer.github.com/guides/basics-of-authentication/)

**Comment by damithc** [comment]
Sure, try it if it can be done.

**Comment by rd1992** [comment]
@dariusf before you release today could you checkout the branch for this issue? I changed the workflow for login. If you like it then you can merge it. Suggestions also welcome :)

**Comment by rd1992** [comment]
To explain further this is what the workflow is like:
1. User sees login window. Signs in.
2. Browser view is only launched when he clicks on an issue or uses a keyboard shortcuts to interact with the bview.

The switching of focus etc is currently for windows only though

**Comment by dariusf** [comment]
Tried it out. It launches a lot faster, which is great.

One small issue is that when you click on an issue and the browser launches, the browser doesn't go straight to the issue's page after login. Should this be fixed now or later?

**Comment by rd1992** [comment]
Well probably by next wed. So you can release it for now :)
