### ISSUE TITLE
'space applies filter' : UI freezes while applying the filter

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#573]
When a filter application is triggered by a space, is it possible to apply it in a non blocking way? Depending on the size of the project, the lag can be significant hindrance to typing a filter.

**Comment by damithc** [comment]
Actually, the user seem to be able to keep typing although the UI is frozen for a few moments. But it's better if the lag can be avoided.

**Comment by dariusf** [comment]
Filter application is pretty fast, even if there are a lot of issues. What's slow is the UI updating when there are a lot of items in the list. That can't be delegated to another thread unfortunately.

Maybe we could delay the application to when the user stops typing? For example, if space was pressed, wait for a lull (no typing for a short time), then apply. Maybe even selectively do this depending on the number of issues.

**Comment by damithc** [comment]
It doesn't seem to be a big problem in my laptop, even when I'm dealing with 20k issues.

**Comment by lejolly** [comment]
closed since space doesn't apply the filter anymore.
