### ISSUE TITLE
'space accepts current suggestion' can result in unexpected results.

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#574]
e.g I was trying to type `set up files` but ended up with `set updated files` :-p This can become quite annoying.

**Comment by rd1992** [comment]
This can go either way. To accept auto complete then the user will have to press another key to accept the suggestion before pressing SPACE or ENTER. Or the user presses Backspace to reject the filter and keep typing normally. Both ways involve the user pressing two keys.

**Comment by damithc** [comment]
True. User has to type an extra key either to accept the suggestion or reject the suggestion. At the moment I prefer to require the extra key for accepting the suggestion. Reaon: When the user wants to type `up` and expand it to `updated`, the user is consciously using a short form and aware of the longer form. He can add the extra key without thinking much. Whereas typing `up` and having to type an extra key to avoid `updated` can be seen as an unexpected annoyance. We can't expect users to lookout for unexpected suggestions every time they type a word in the filter.

**Comment by damithc** [comment]
No longer relevant as space does not accept the current suggestion any more.
