### ISSUE TITLE
bView restarted when I clicked on an issue

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#577]
Ended up with this
![image](https://cloud.githubusercontent.com/assets/1673303/6995676/afc408c4-db89-11e4-962e-c3d14ba7563f.png)

**Comment by rd1992** [comment]
Ahh. This is tied in with #569 . Will fix now

**Comment by dariusf** [comment]
What's the root cause for the browser restarting, though? Does it affect anything else?

**Comment by rd1992** [comment]
could be a bunch of stuff. will have to check the log

**Comment by damithc** [comment]
I'll send the log if it happens again.
