### ISSUE TITLE
Renaming labels or milestones causes crashes

### ISSUE THREAD

**Issue by dariusf** [HubTurbo/HubTurbo#584]
The issue is that issue events refer to old labels even if they no longer exist. Even if a label is renamed, it appears in the event log under its old name, and this causes problems for us when we try to find the label with the old name and can't.

Happens reliably but under specific circumstances (updated filter must show an issue with a renamed label).

A deeper issue is that we don't keep track of labels by identity, only by name. We need to somehow resolve the conflicts or ignore labels which don't exist, assuming they were renamed. This may require fundamental changes to how we deal with labels.

Same thing happens for milestones, but is easier to resolve since milestones seem to have an internal id (not sure if it's ever recycled though).

**Comment by rd1992** [comment]
test comment
