### ISSUE TITLE
Rename user config directory

### ISSUE THREAD

**Issue by dariusf** [HubTurbo/HubTurbo#610]
Currently we're storing global user configuration (last login name, last viewed repos, etc.) in a directory named `config`. The problem is that we have a directory with the same name which stores dev configuration.

We should rename one of them. Maybe the user one to `prefs`?

**Comment by damithc** [comment]
What's the name commonly used (by other apps) for user config folder?

**Comment by dariusf** [comment]
`settings` maybe?

**Comment by damithc** [comment]
Sounds good.
