### ISSUE TITLE
label filter should use 'starts with' behavior

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#649]
For example, if I use the `label:p` filter, it should show issues with label `p.high` but not `aspect-test`.
If not, I don't have a way to filter out issues with a priority label.

**Comment by damithc** [comment]
I wonder if this is a bug. The filter `-label:s` results include an issue with `s.Accepted` label
![image](https://cloud.githubusercontent.com/assets/1673303/7895017/32bbda58-06ab-11e5-99f1-2efc07d18c6a.png)

**Comment by dariusf** [comment]
`-label:s` matches only by name. The name portion of `s.Accepted`, `Accepted`, doesn't contain `s`, so it matches. To match against a group you have to append a `.`, like `-label:s.`.

The current logic is that you have a group name and a label name (`label.group`). These are treated and matched separately in both the filter and the actual label name using `String::contains`, not `startsWith`. `a.d` would match `aspect.boards`.

This may be unintuitive. Would it be better to just match a prefix of the entire label name instead?

I'll fix this together with #650, with the new tests.

**Comment by dariusf** [comment]
Doesn't seem to be a bug, and discussion on the rest is ongoing in #650.
