### ISSUE TITLE
auto-complete is getting in the way of editing filters

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#651]
When I'm editing an existing filter (e.g fix a typo), the auto-complete jumps in and inserts stuff that I don't need. Perhaps hold back auto-complete if there is a letter on the right?
I also noticed the cursor jumping back to the beginning of the filter at unexpected moments.

**Comment by dariusf** [comment]
Autocomplete should now only happen when there's nothing or only whitespace after the caret.

Can't reproduce the caret jumping. Not sure what could cause it.
