### ISSUE TITLE
Read updates shown in bold

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#662]
Only unread updates are supposed to show in bold right? In the screenshot below, updates within the filter period but before my last 'read' are also shown in bold.
![image](https://cloud.githubusercontent.com/assets/1673303/7910751/e78f8d5a-0889-11e5-8b7c-55e00a68ef76.png)

**Comment by dariusf** [comment]
Hmm, do you know how to reproduce it? You marked it as read and on the next update, those which were previously not shown in bold became bold?

**Comment by damithc** [comment]
test comment

**Comment by damithc** [comment]
testing @dariusf

**Comment by damithc** [comment]
test comment 2

**Comment by damithc** [comment]
Can't seem to be able to reproduce it. I'll update if it happens again.
