### ISSUE TITLE
Tweaks to documentation

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#669]
Here are some things I noticed (there may be others)
* Getting started
  - [x] have a 'Next' link at the bottom (this applies to other pages as well)?
  - [x] give an example of a filled up login dialog?
* UI basics
  - [x] also duplicate the screenshot from the previous page (the wire frame may be too abstract for end users)
  - [x] description of repository is outdated
* Working with panels
  - [x] The shortcut should be Ctrl+P not Ctrl+N
* Development env
  - [x] Eclipse appears under IDEA section
  - [x] mention that gradlew keeps memory unless the window is closed?
  - [x] mention that they should use the generated jar instead of the released jar?
  - [x] mailing list is a private group. we can create a hubturbo-contributors group.
* Changelog
  - [x] 2.8 is described but not released? We need to release a new version anyway.

**Comment by damithc** [comment]
Google group created https://groups.google.com/forum/#!forum/hubturbo-contributors

**Comment by dariusf** [comment]
[Our modified coding standards](https://github.com/HubTurbo/HubTurbo/pull/668#issuecomment-109193517). We should probably document this more formally?

**Comment by damithc** [comment]
Can have a separate page for the coding standard. For my own sanity, is it possible to use the one used by TEAMMATES (instead of the Google one)? That one is also based on the Google one and also used by CS2103 students.
