### ISSUE TITLE
bView layout is shifted at startup

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#681]
This is how it looks at start up (this happened after V2.8)
![image](https://cloud.githubusercontent.com/assets/1673303/8074845/f0f4c464-0f69-11e5-82e3-3be7d487df02.png)

**Comment by lejolly** [comment]
i'm unable to reproduce this on windows 8.1/server 2012 r2. could be a windows 7 specific bug? will look more into it when i have access to a windows 7 machine.

**Comment by damithc** [comment]
Yes, seems to be a one-time fluke. I can't reproduce it either. I'll reopen if it happens again.
