### ISSUE TITLE
3 test cases failing during build

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#682]
On Win 7
![image](https://cloud.githubusercontent.com/assets/1673303/8074853/287998c4-0f6a-11e5-8ca2-0620a52273bc.png)

**Comment by acruis** [comment]
The tests are passing on my machine. There should be some .png files in the home directory of HubTurbo. Could you upload them here? You can add `|width=100` after the image filename, as in `[images.png|width=100](linktoimage.png)` to resize the screenshots if they are too big.

**Comment by damithc** [comment]
![screenshot1433909084984](https://cloud.githubusercontent.com/assets/1673303/8082697/a6fecaec-0fb1-11e5-87c3-e5284fcb873d.png)
![screenshot1433909102738](https://cloud.githubusercontent.com/assets/1673303/8082702/afb3073e-0fb1-11e5-8aad-fb53a10acf0b.png)
![screenshot1433909228031](https://cloud.githubusercontent.com/assets/1673303/8082705/b378b21a-0fb1-11e5-9760-a4017bcb7961.png)
