### ISSUE TITLE
Issues should be sorted by latest updated time first in updated view

### ISSUE THREAD

**Issue by acruis** [HubTurbo/HubTurbo#683]
Currently, if no sorting order is specified, issues are sorted by descending ID (i.e. latest creation time first).

This is true even when the `updated:` filter is used. Intuitively, when the `updated:` filter is used, issues that are updated the latest should be shown on top (unless another sorting order is explicitly specified through the `sort:` filter).

**Comment by damithc** [comment]
Agreed.
