### ISSUE TITLE
Selection should not change when switching back from bView to pView

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#684]
Currently, the selection seems to be based on index rather than a unique identifier. For example, if the 3rd issue was selected originally, the 3rd issue will be selected after switching to pView even if the originally selected issue is no longer the 3rd issue.

**Comment by lejolly** [comment]
@acruis are you solving this as part of #679? if not i'll have a look at it.

**Comment by acruis** [comment]
Go ahead, #679 should not interfere with this.
