### ISSUE TITLE
Refactoring of the GUI logic

### ISSUE THREAD

**Issue by acruis** [HubTurbo/HubTurbo#685]
Currently there is a lot of logic in GUI, especially when the issue panels are repopulated as part of an update. The flow of execution can be unclear at times due to code in multiple classes in GUI being carried out as a result of repopulation of data, especially when events are triggered to carry data between the Logic component to said GUI classes.

This logic can be abstracted out into a "GUI Controller", so to say, which manages the flow of execution and serves relevant data to each GUI component.

**Comment by acruis** [comment]
@dariusf Do you think this is a good idea, or are there any problems with this approach?

**Comment by dariusf** [comment]
I'm all for refactoring, but what does it mean to serve relevant data to each component? Would it still involve events?

**Comment by acruis** [comment]
Events are probably unavoidable, but the new "GUI Controller" should be the one handling them in lieu of other GUI components.

As for serving relevant data to each component, for example, currently IssueColumn takes care of sorting (by initializing the SortedList) and triggering the getIssueMetadata method in Logic, which in turn triggers updateUIWithoutMetadata. However, the method that actually determines whether to display the update details is inside IssuePanelCard instead, where the filter string of the parent column has to be checked. This update logic can be handled by the new GUI component, which will determine whether the IssuePanelCard is to display update details.

Currently, ColumnControl is the component that is delivering the model data to its children IssueColumns, and holds the logic for managing columns when they are created/closed. The GUI Controller taking over (and adding more logic to) the first task would make the flow of the program a lot clearer.

**Comment by dariusf** [comment]
I like the idea of centralising the UI update logic (and it definitely could use clearer flow), but I'm a bit fuzzy on the details. Is the GUI controller conceptually part of UI or Logic? Does it serve a very different purpose from UIManager? Say it has listeners which catch events sent from Logic. How does it then communicate with the right JavaFX nodes?

**Comment by acruis** [comment]
I'm thinking the logic to locate the right nodes can be placed in the various GUI classes, as this logic should be relatively simple, and does not mutate data, either. The found nodes can be propagated through the hierarchy up to the GUI Controller, which is where the data will be mutated. The idea is to centralise mutation of the GUI data into a single class.

For a "GUI" component, the GUI controller would potentially contain a lot of logic, but it serves a much different purpose than Logic, as it has access to components of the GUI and is in charge of mutating it directly. In that sense, it would not be like the UIManager (whose job is to trigger events on the GUI, rather than to receive and carry out logic), and neither would it be like Logic, which does not have knowledge about the GUI at all.

**Comment by dariusf** [comment]
By propagating nodes up the hierarchy, do you mean with actual references? That gets hairy very quickly.

I'm wondering if we can use selectors to find the right nodes. That would only get us to the level of using jQuery to manipulate the DOM though... Still not particularly neat or elegant. Maybe you could explore a combination of using selectors to find nodes + data binding?

**Comment by damithc** [comment]
We can spend 1-2 days coding a representative slice in various approaches and see if any of the approaches give us a significantly better outcome.

**Comment by acruis** [comment]
@dariusf Even when using selectors to find nodes, I think what we receive as a result would still be the actual reference to the object. Do you mean "gets hairy" as in the process of locating the nodes, or the process of mutating the data within the nodes?

**Comment by dariusf** [comment]
If we don't use events or selectors, we would have to pass references to the nodes either up the UI tree (via getters) or down (via constructor parameters). The latter ones require us to modify the entire hierarchy and are harder to maintain.

**Comment by acruis** [comment]
Yep, passing the nodes up the UI tree through getters is what I'm thinking of. Is this approach harder to maintain?

**Comment by dariusf** [comment]
I would think so, since you would have to change every class up to the root whenever you add something. This can be like 5-6 classes if you want to get something like the issue card title.

**Comment by acruis** [comment]
Ah, that's true. On the other hand, they're mostly just getters so I don't think it introduces much overhead?

I looked into CSS Selectors, but it seems like the JavaFX UI does not have a DOM for us to select; testFX implemented their own code to locate the JavaFX elements.

**Comment by dariusf** [comment]
The overhead I'm concerned about is the boilerplate. Every getter between the root and the eventual destination is going to do nothing but relay the message down. That's a lot of clutter to add to existing classes I think.

A few other ideas:

1. Separate UI events from the others. Logic sends events which are listened for by UIController, and UIController then re-dispatches UI events to the relevant nodes. This requires discipline to improve the situation though.
2. JavaFX has data binding. Maybe we can pass some kind of proxy object down into the UI tree, have UI elements bind fields on it, and modify it in the UIController in response to events? May not cover all our use cases.
3. Reuse TestFX CSS selectors. How feasible is this?
4. Write a small library/DSL which handles traversal of the UI tree -- something like a specialised jQuery that understands our UI layout. For example, in UIController, `ui.panel(1).issueCards().forEach(this::doSomething)`. We wouldn't have to modify the UI classes, and it has the added advantage of decoupling UI implementation and interface, without CSS or TestFX.

**Comment by acruis** [comment]
1. Events have the potential to make handling code convoluted and/or defensive, which goes against the idea of this refactoring, which is to centralise GUI logic for simple maintenance and adding-on of features.
One example of why events can cause a lot of mangled code logic is ModelUpdatedEvent in the case of metadata updates, which required the use of an additional flag, which then in turn introduced more logic to manage this flag. It was difficult to make sense out of `triggerMetadataUpdate` and related code that manages this flag.
Also, like you said, this requires discipline and isn't really helpful as other members of the team might try to add new logic into the handler code (which is supposed to be as simple as possible, to centralise logic to the GUI controller).

2. The code to bind fields to the proxy object might be as long and repetitive as normal boilerplate. I like this idea, but how is this different from passing the JavaFX object itself up the entire hierarchy? From what I see, the direction of object-passing is just reversed.

3. So far, TestFX has been performing great with the test data (which is not that large), but I'm not sure about TestFX's scalability. I'm OK with using TestFX, but that also requires more logic for managing issue IDs on the GUI side.

4. How does the new library traverse the UI tree without code that allows them to access child UI nodes (i.e. getters)? Make everything `protected`? Visual matching?

I understand that boilerplate clearly violates DRY, but it's just three lines of code per field at most. A getter method shouldn't make a class's code any less readable. It's a bit less elegant in the sense that it requires the effort of typing three additional lines, but I'd take practicality over elegance any day. As for the case of adding new GUI classes, shouldn't this be rare and most of the time tied to a significant user story? I would say adding a getter method is the least of your worries in that case.

**Comment by dariusf** [comment]
1. Okay, I'm not in favour of this also.
2. Only one object needs to be passed down via constructors, instead of multiple objects being passed up via multiple paths.
3. I was hoping that selectors would be a modular part of TestFX (like Sizzle is to jQuery). Oh well, maybe it's not the best way.
4. Cast `Node`s to [`Parent`](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/Parent.html)s and call `getChildren()` to traverse. It would be coupled to the UI implementation, but anything depending on it wouldn't be.

I'm against getters because I'm not convinced it's the best approach. It's practical in the sense that it short-circuits the problem and is easiest to implement, but it's not going to scale up to a more complex UI: the overhead of nesting increases the more you nest, and everything along the way becomes coupled (whereas nesting overhead with CSS selectors is constant). If you don't control container nodes along the way, also, you can't add getters. You'll need some ad-hoc logic for accessing children and the getter will be more complicated.

I'm not saying we should come up with the most elegant, generalised solution for structuring UIs. We *should* come up with something that can minimise the overhead of change. Decoupling UI implementation from traversal is one way to accomplish that.

**Comment by dariusf** [comment]
What I'm talking about could be as simple as [this](https://gist.github.com/dariusf/80c3657fcdfa1c0bc3a2). There is also the [lookup](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/Node.html#lookup-java.lang.String-) method, which is built-in and may help?

**Comment by acruis** [comment]
Well this is awkward; I forgot about `getChildren()`, and I didn't realise the existence of `lookup` either. `lookup` seems to be utilising `getChildren()` as well, so I guess we're...done here?

**Comment by dariusf** [comment]
Well, getting node references is only the first step... Still need to figure out how to make the flow clearer.

**Comment by acruis** [comment]
I agree, but how would you abstract the CSS away? In the case of the issue panels, for example, do we leave some logic in `IssuePanelCard` to bind class / ID to each issue card?

**Comment by dariusf** [comment]
On creation we could assign an id via `IssuePanelCell`, which wraps `Card` (using the factory, like [this](http://stackoverflow.com/questions/20936101/get-listcell-via-listview)). Or maybe we can assign it based on the issue id? Is that what is done now?

**Comment by acruis** [comment]
Assigning using the factory based on visual order seems to be the safer choice here, but on second thought I see little use for IssuePanelCard IDs other than for testing purposes. Traversing and setting issue cards' details one by one is easily `O(n^2)`, so it's better to just get the panel and place issues there, I think.

**Comment by dariusf** [comment]
I guess you could write a method that returns a set of issue cards. Depends on what parts of the logic exactly you want to extract.
