### ISSUE TITLE
No error notification or recovery on corrupted repo JSON

### ISSUE THREAD

**Issue by acruis** [HubTurbo/HubTurbo#700]
A JSON storage file of mine was somehow corrupted. When I loaded HT, it detected that the JSON file exists for the repo, and tries to load it but fails silently, resulting in only a thrown exception and a blank panel where the repo's issues are supposed to be.

Ideally, the user should be notified of the problem through the status bar, and HT should automatically attempt to re-download the repo from GitHub.

![screen shot 2015-06-16 at 11 42 06 am](https://cloud.githubusercontent.com/assets/8437638/8175401/d9b38620-141c-11e5-85e1-ff7c63cf9ab5.png)

**Comment by damithc** [comment]
Yes, that would be better.
