### ISSUE TITLE
IncompatibleClassChangeError during build

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#705]
Got this during `gradlew build` of 2.9.0
```
:test
Exception in thread "Thread-10" java.lang.IncompatibleClassChangeError
Exception in thread "Thread-10" java.lang.IncompatibleClassChangeError
:check
:build
```

**Comment by lejolly** [comment]
i can't seem to reproduce it, have you tried using `clean build`?

![hubturbo_-____repos_hubturbo-hubturbo_hubturbo_](https://cloud.githubusercontent.com/assets/1589121/8223681/cabbb27c-15ad-11e5-96c2-06183ce553f5.png)

![jolly-server](https://cloud.githubusercontent.com/assets/1589121/8223685/d9337fce-15ad-11e5-961f-b56c8bb01df2.png)

**Comment by damithc** [comment]
Yes, a clean build did not have same error. Although it showed this error
at the beginning.
Note: C:\HubTurbo\src\main\java\util\DialogMessage.java uses or overrides a
deprecated API.

**Comment by lejolly** [comment]
yeah we'll have to move away from that eventually to create dialog boxes.
