### ISSUE TITLE
json files explode randomly

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#706]
I've encountered this twice now. The json file of teammates repo goes into 100s of Mb.

**Comment by lejolly** [comment]
the sample file appears to be mostly made out of nonsensical data, with the json part only at the beginning and the end of the file. 

before it starts
![teammates-repo_json_backup_and_osx_-_what_s_the_best_text_editor_for_use_with_large_files__-_ask_different](https://cloud.githubusercontent.com/assets/1589121/8224001/4fa459ea-15b2-11e5-828a-15037597034b.png)

after it ends
![teammates-repo_json_backup_and_json_files_explode_randomly_ _issue__706_ _hubturbo_hubturbo](https://cloud.githubusercontent.com/assets/1589121/8224005/606c75a0-15b2-11e5-8ed1-550458b65199.png)

i wasn't able to find any legitimate data in the middle of the nonsensical stuff.

**Comment by lejolly** [comment]
wonder if it's some unicode issue, cause it starts at the ó in https://github.com/TEAMMATES/repo/issues/2662 and ends at ’s in https://github.com/TEAMMATES/repo/issues/58

**Comment by damithc** [comment]
Yes, that is possible. Is the garbage received from GitHub? May be we should put in some checks to alert us when the received data is not as expected.

**Comment by lejolly** [comment]
yeah, adding a check if the json grows by `XXXX %` or `XXX MB` and then maybe showing the most recent `XX` lines of the log? @acruis what do you think?

**Comment by acruis** [comment]
Sounds good.

**Comment by damithc** [comment]
A dirty fix (until we discover the real cause) would be to identify the explosion, inform the user that the cache is corrupted, and do a hard refresh for the file. At least the user will be able to continue using HT.

**Comment by acruis** [comment]
When the json explosion occurs, does the program stop running?

**Comment by damithc** [comment]
Technically, no. But it causes the memory to exceed 1Gb effectively making the entire computer useless.

**Comment by acruis** [comment]
So the program continues to function as per normal (the status bar changes, keyboard shortcuts still work)?

When the program exceeds its heap limit, it throws an OutOfMemoryError but does not crash. Is this the case here?

**Comment by damithc** [comment]
I never reached that stage so far. Once it goes over 1Gb, I usually kill it because the other running programs become sluggish due to low memory. Today the json file was 90Mb so the situation was not that bad. Last time it was 300mb, that consumed much more memory when loaded. So the program technically continues to operate, which is actually worse than crashing. If crash, user knows something unexpected went wrong. In the current situation, user might think the program is just a memory hog.

**Comment by ndt93** [comment]
I tried Damith's 2 board's filters  and some variant filters out for this. There are some tests that can provide some leads on this.

1. Tests with Damith's 2 board's filters
2. Test when those repos contained in the filters are opened manually.
3. Test when those repos in the filters have been successfully opened beforehand
4. Test when repos in each of the filter are unique among all the filters.

I observe in (1) that there are sometimes 2 progress bars of the same repos, which may imply race conditions. Also in (1) the `openRepository` are called much faster for each `repoId` present in the filters than possible in (2). In (3) and (4) they don't really affect anymore. And also considering the nondeterministic behavivour of this problem, looking at concurrency issues may provide a some leads.

An example of where I think there is a race condition in the code:

*In `backend.logic.openRepository`*
```java
...
1. return repoIO.openRepository(repoId)
2.     .thenApply(models::addPending)
3.     .thenRun(this::updateUI)
4.     .thenRun(() -> UI.events.triggerEvent(new RepoOpenedEvent(repoId)))
5.     .thenApply(n -> true)
6.     .exceptionally(withResult(false));
 ...
 ```
 By the time *line 1* executed, the download has started for `repoId`. By the time *line 6* executed, the function have returned and ready to open another repo. However `models::addPending` in *line 2* might not have a chance to execute yet. From what I understand, we present simultaneous downloading of the same repo by using this pending queue, which in this case may failed to perform that task.

**Comment by damithc** [comment]
@ndt93, did you testing reproduce any data corruption? If not, this may be an issue not related to the json explosion.

**Comment by ndt93** [comment]
@damithc Yup, this might be a separate issue, just my wild guess that it could be related. I haven't been able to reproduce it, I usually runs out of API quota running 2 of the tests 10 times each and have to wait until the next day. I could get this explosion pretty easily early in June but so hard to get it now. Still trying to reproduce it, seems like pretty interesting behavior; unicode problem would give us weird data but this explosion to hundreds of MB...

**Comment by ndt93** [comment]
Something I noted is that last time, for me, the explosions typically happens with teammates or rails. There are 2 things about repos: they are bigger and have more updates. It also gets worse after each update.

Another problem is that the json files are written only during downloading and when there are new updates. The latter case seems to be a better candidate for this problem but hard to test during short period of usage since most of the time there are no new updates.

**Comment by acruis** [comment]
Explosion happened this afternoon for me.

Doesn't seem like it's a single character that causes this problem. There are multiple corrupted chunks interspersed among proper data in a single file:

![start](https://cloud.githubusercontent.com/assets/8437638/8647554/8926790e-298b-11e5-9cac-262a64622bc2.png)

![start1](https://cloud.githubusercontent.com/assets/8437638/8647564/9edc3f7c-298b-11e5-8202-3077b75e4bd3.png)

![start2](https://cloud.githubusercontent.com/assets/8437638/8647565/a0dca348-298b-11e5-85d2-f13fe5bae432.png)

**Comment by damithc** [comment]
We need more extensive logging to troubleshoot this kind of thing. Can we log everything received from GitHub before we do anything with it. Need to find if the garbage was sent from GitHub or generated by our end.

**Comment by acruis** [comment]
Does this happen only on a new repo download, or does it happen just on an update?

If it's the latter, it's most likely not caused by GitHub's data, as the text from the screenshots is from old issues - untouched for almost a year. We don't get these issues' data from GitHub any time other than during the initial big download.

In other words, it's probably a problem on our end.

**Comment by damithc** [comment]
We can do a regex match at a suitable location to detect as soon as this happens. As of now, I don't think the human detection of the situation is immediate.

**Comment by ndt93** [comment]
I have done quite a number of downloading new repos testing scenarios which didn't cause any problem so I think we can focus on catching it at the update phase first. I haven't been able to test different update scenarios yet though.

A few places I think are critical sections for logging is: data first obtained from github, data assigned to a new model when there are new updates, serialized data before being fed into GSON, string data right before it's written to file.

We can do a regex for teammates (or all repos). Would something like this work?

```
/[^\w \v\t\r\f\n"'()+\-,:@\\/#$!^%&*;|<>?=.]{3,}/ // Match 3 consecutive occurrences of rare characters
```

We can match only some fields or the entire repo string.

**Comment by ndt93** [comment]
For convenience of anyone who want to try the logging I mentioned above:

* Data right from github (i.e. through egit lib): In *backend.github.GitHubRepo* -> getUpdated*(...)
* Data assigned to a new model: In *backend.RepoIO* -> updateModel
* Serialized data before Gson: In *backend.json.WriteTask* -> save
* String data before written to file: In *util.Utility* -> writeFile

**Comment by damithc** [comment]
teammates json exploded just now :-p

**Comment by damithc** [comment]
Seems to be fine now. closing.

**Comment by acruis** [comment]
Yay!
