### ISSUE TITLE
Rename nonSelfSortable in Qualifier.java

### ISSUE THREAD

**Issue by lejolly** [HubTurbo/HubTurbo#707]
to `isNotSelfSortable`

**Comment by acruis** [comment]
Note that `nonSelfSortable` also occurs in [IssueColumn.java](https://github.com/HubTurbo/HubTurbo/blob/master/src/main/java/ui/issuecolumn/IssueColumn.java#L183).

**Comment by acruis** [comment]
Actually, I forgot: `nonSelfSortable` should be renamed as `isNonSelfSortable

**Comment by lejolly** [comment]
i think the longest version is the clearest

**Comment by acruis** [comment]
Okay, then we'll go with that.
