### ISSUE TITLE
Proposed behaviour for RepositorySelector

### ISSUE THREAD

**Issue by lejolly** [HubTurbo/HubTurbo#732]
The `RepositorySelector` should reflect the `.json` files saved on disk. 
The list refers to the `comboBox` in `RepositorySelector`. 
This means that: 
1. Opening a new repo from the `RepositorySelector` adds it to the list (last entered repository is the new primary repository). 
2. Opening a new repo from any `FilterTextField` adds it to the list (but doesn't make it the new primary repository). 
3. At startup, the `RepositorySelector` will be populated based on the `.json` files on disk. 
4. We don't need to save a list of last used repositories, just the last valid one that was entered. 
5. To remove a repository from the `RepositorySelector`, the user just has to delete the corresponding `.json` file and restart HT. 
6. If the last valid repository's `.json` file is deleted/missing, we populate the `RepositorySelector` normally but leave the default value blank. (Although this brings about the question of which default repository do we use?)

Alternatively we can save a list of valid last used repositories as a stack so we just go down the list if the last used `.json` is missing. OR we could just pop up the login dialog to force the user to choose a new primary repository. 

This should solve #619 and #665.

**Comment by damithc** [comment]
Sounds good. @dariusf any comments?
For 6, I don't mind selecting the first one in the list of repos as the default. User can change it easily if that's the wrong choice.

**Comment by damithc** [comment]
Test comment. Please ignore.

**Comment by damithc** [comment]
Another test comment.

**Comment by acruis** [comment]
Sounds good, but how would we sort the list of repos then? Alphabetically?

I suppose if the `.json` is missing, we can show the user the login dialog again, so that the user can explicitly specify the repo to be used as the default value. In this case, if the user wants to use the same repo (with the `.json` now missing), we download it for him/her.

**Comment by damithc** [comment]
Alphabetically is fine. It makes it easier to locate an item in the list. 
I'm not sure about using the login dialog for the purpose of selecting a default repo. That might puzzle the user (why do I have to login again?)

**Comment by HyungJon** [comment]
If the repos are loaded from the ```.json``` file, wouldn't that make them sorted based on recency?

**Comment by acruis** [comment]
Using the login dialog is only relevant to the edge case where the `.json` file goes missing (which is not a common scenario). The reason why I thought of showing the login dialog again is that we're using the login dialog for this purpose anyway when the user starts HubTurbo for the first time (specifying both the repo to use and the username/password). Plus, we can pre-fill the credentials field for the user in this case.

We can even explicitly notify the user of the missing dialog through additional text on the login dialog.

@HyungJon We're referring to the respective repos' data stores (`teammates-repo.json`, `HubTurbo-HubTurbo.json` etc. in the `store` folder), not the settings json.

**Comment by damithc** [comment]
Yes, getting the user to specify the default in a non-confusing way is idea. It is a rare edge case, so do whatever the easiest reasonable solution now and if that is not the ideal solution, create a separate issue for the ideal solution.

**Comment by dariusf** [comment]
This is a nice idea. To an experienced user the dropdown would indicate which repositories are cached and can be switched to quickly.

If the login dialog has to be changed a lot for this purpose, maybe we should use a new dialog. We can then make it absolutely clear what is happening without having to deal with more cases in the existing one.

**Comment by lejolly** [comment]
for now if the last default repo's `.json` is missing, we'll just load the first cached repo by alphabetical order then.

**Comment by acruis** [comment]
Alright.
