### ISSUE TITLE
Cannot add spaces in the middle of the filter

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#733]
The space key does not result in a space at this point (I wanted to add a space after `self`)
![image](https://cloud.githubusercontent.com/assets/1673303/8351092/4525ebcc-1b5d-11e5-84e1-08dba58a7dfb.png)

**Comment by damithc** [comment]
When in this state, I can't even add a space at the end of the filter :-p

**Comment by lejolly** [comment]
this only happens when the previous key was also a space? i think it's related to the double-space shortcut.

**Comment by ianngiaw** [comment]
It can happen if you press space once while an issue is selected, then manually selecting `filterTextField`. After that, you cannot add a single space anywhere in the textfield until you double-space out of the `filterTextField`.

**Comment by lejolly** [comment]
@damithc is this still reproducible?

**Comment by damithc** [comment]
yup.

**Comment by lejolly** [comment]
i can't seem to be able to reproduce it, could you provide a list of steps?

**Comment by damithc** [comment]
Steps: click in the middle of a filter and type space.

However, if you navigate to the filter box using keyboard and types a space, it works. Once you manged to enter a space, even clicking and typing will work after that. It seems once you manage to enter a space in the filter, it becomes 'unlocked' for more spaces.

**Comment by lejolly** [comment]
hmm i still can't reproduce it on either windows or os x.

**Comment by damithc** [comment]
Restart HT and try again (on Windows)

**Comment by lejolly** [comment]
Nope, still can't. @acuris @ndt93 can confirm?

**Comment by damithc** [comment]
Now I can't reproduce it either. The only difference between my previous version and this is one fixed issue (the one about Ctrl+R), but not sure that's the reason. I'll monitor and report if it happens again. I'll close for now.
