### ISSUE TITLE
Use runAndWait in tests instead of sleep

### ISSUE THREAD

**Issue by acruis** [HubTurbo/HubTurbo#739]
As mentioned by @dariusf, `PlatformEx.runAndWait` has a stronger guarantee that what comes after executes after compared to `sleep`, which makes integration tests more deterministic.

**Comment by lejolly** [comment]
may not work for every test case, but i'd love to be proven wrong for this.

**Comment by dariusf** [comment]
If it doesn't work, the use of explicit latches and barriers may be required. This part won't be as beginner-friendly and can be a separate issue.

**Comment by dariusf** [comment]
Subsumed by new testing guidelines (always synchronise explicitly!).
