### ISSUE TITLE
Label Picker

### ISSUE THREAD

**Issue by lejolly** [HubTurbo/HubTurbo#740]
Reduce interaction with browser
Autocomplete for shortest match
Will need to be broken up into smaller steps
Pop-up should be populated with existing labels

Later
Label groups: e.g. priority, if it has medium, by typing high, it should remove medium and put high

**Comment by acruis** [comment]
Label groups can be either exclusive (`p.High`) or nonexclusive (`feature-filters`). The classification is determined by whether the separator in the label name is a `.` or a `-`.

**Comment by damithc** [comment]
Shouldn't this match `enhancement` instead of `duplicate`?
![image](https://cloud.githubusercontent.com/assets/1673303/8612487/e18468e8-2703-11e5-8c92-0ca156428489.png)

**Comment by damithc** [comment]
Pressing space without any other letters applies the first label in the list. May be we should not do that? i.e. not start selecting labels until user types a non-space letter.

**Comment by lejolly** [comment]
ok i can disable selection when the textfield is empty, as for the previous one, currently selected labels are always placed in front for easy removal. you can use the up/down arrow keys to change the selection too.

**Comment by lejolly** [comment]
Closed with #759
