### ISSUE TITLE
Aggregate label updates to save space

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#744]
Updates like this can be condensed into a single line. e.g. `user` : `added-label` ~~`removed-label`~~ 
![image](https://cloud.githubusercontent.com/assets/1673303/8373593/d450c6c8-1c20-11e5-8fb6-01be1626c952.png)

**Comment by ndt93** [comment]
I'm working on this in case anyone is trying the same thing so we won't overlap.

**Comment by damithc** [comment]
@dariusf could you add Thien to project members and assign this issue to him?

**Comment by ndt93** [comment]
Ok, I already have some code for this on my fork though, so I will still continue this issue on my fork first.
