### ISSUE TITLE
Some updates not received until restart

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#748]
I had left HT running overnight y'day and when I checked in the morning, some of the latest updates did not appear under my `updated` filter. I did a restart and the missing updated appeared. Not sure what's the cause or how to repro. I'm recording it anyway, for future reference.

**Comment by acruis** [comment]
Steps to reproduce: (creates actual issue comments and requires access to an alternate GitHub account, recommended to be done on personal test repo)

1. Comment on issue (with account used for HT)
2. Comment on issue (with alternate account)

If comment from step 1 is within the update window, issue will not show up under the `updated` filter even after step 2.

**Comment by damithc** [comment]
This happened again. Raising priority.

**Comment by damithc** [comment]
Raising priority

**Comment by damithc** [comment]
Need to be fixed by next release.
