### ISSUE TITLE
Issues are marked as unread after a self-update

### ISSUE THREAD

**Issue by acruis** [HubTurbo/HubTurbo#750]
Followed from discussions in #679.

The issue passes the `updated:XX` filter because there is indeed a non-self update in the specified window. It passes the `is:unread` filter as it is marked as read before the model in the GUI is updated (which causes it to be marked as unread again).

**Comment by rd1992** [comment]
@acruis the updated filter need not be specified. I can reproduce this by just using is:unread -> Press E -> update issue in webView-> it gets marked as unread again. Can you confirm this?

**Comment by acruis** [comment]
@rd1992 Ah yep, I thought it was somehow related to the updated filter when I wrote this issue. It's not related to the updated filter as we mark the issues as "unread" during a refresh and not during a metadata retrieval. I'll change this issue's title to match.

**Comment by rd1992** [comment]
@damithc quick question. should we mark an issue as _unread_ at all? I am just thinking about it from a user perspective. once marked as _read_ i would like to keep it that way regardless of any updates. its like muting a conversation on facebook or whatsapp.

**Comment by damithc** [comment]
'marking as unread` is simply undoing a 'mark as read` operation done by mistake.

**Comment by damithc** [comment]
Any progress on this one?

**Comment by rd1992** [comment]
Yes. This was blocked by the metaupdate issue. Working on this now.

**Comment by rd1992** [comment]
Closed via #944
