### ISSUE TITLE
'mark as read' does not remove issue from 'is:unread' filter

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#754]
The issue eventually disappears from the panel but it takes 20 seconds (sometimes more) for that to happen. Previously, pressing `E` made the issue disappear immediately. Is the delay intentional? I don't mind such a delay if it was intentional and deterministic. In fact I prefer to have such a delay.
![image](https://cloud.githubusercontent.com/assets/1673303/8469983/99d0d7c8-20b6-11e5-94b5-326999d63a95.png)

**Comment by HyungJon** [comment]
It appears the panel view waits until the next refresh to remove issues that should not be displayed.

**Comment by damithc** [comment]
A delay is fine but, the focus should go to the next issue when I mark an issue as read.

**Comment by HyungJon** [comment]
Done. I see some rooms for improvements though.

1. Should the automatic change in focus be coded for only when the filter is is:unread? (I'm not entirely sure whether this is possible without major modifications though.)
2. Is there a strong enough need to implement a similar feature for marking issues as unread under is:read filter?

**Comment by damithc** [comment]
1. No need. It can be done even if the filter does not have `is:unread`
2. No need. Reason: No need to optimize the 'unread' operation because it is unlikely to be used a lot. The only use case for 'mark as unread' I can think of is for undoing a 'mark as read' operation that was done by mistake

**Comment by HyungJon** [comment]
All right. I will write some tests and submit a PR.
