### ISSUE TITLE
Document development workflow

### ISSUE THREAD

**Issue by dariusf** [HubTurbo/HubTurbo#757]
We should add a few things to either the Workflow or Development Environment documents, mostly so new developers can get started more easily:

- [x] How to run tests
- [x] How to run unstable tests
- [x] How to view CheckStyle violations locally
- [x] How to view code coverage locally
- [x] Commonly-used Gradle tasks

**Comment by acruis** [comment]
Agreed.

**Comment by damithc** [comment]
Not sure a beginner can document the workflow that he/she is new to. :-)

**Comment by HansNewbie** [comment]
- [ ] How to merge PR
  - follow command line instruction on GitHub PR merge, use git merge --no-ff -m "message" origin/your-branch-name.
