### ISSUE TITLE
Improve testing for mark as read

### ISSUE THREAD

**Issue by HyungJon** [HubTurbo/HubTurbo#760]
Add more comments and corner cases.
Assigned to myself.

**Comment by HyungJon** [comment]
How do I update my build path to refer to the new jar files added yesterday instead of the old ones? Automated tests work correctly, but I'm not able to do dogfooding because of this error due to build path problem.

**Comment by lejolly** [comment]
Reimport the project? Or remove all the references to the old jars in your project settings and add the new ones. IntelliJ is recommended because you can just refresh the gradle file and everything gets done for you.

**Comment by HyungJon** [comment]
Should I commit and push the modified CLASSPATH file as well?

**Comment by lejolly** [comment]
Oh yeah that would be helpful, sure.
