### ISSUE TITLE
Include documentation in main repo

### ISSUE THREAD

**Issue by acruis** [HubTurbo/HubTurbo#764]
Currently, all documentation is in the wiki. However, changes in documentation should be tied to changes in code i.e. both should be reflected in a single PR. GitHub wikis are standalone repositories, so this is not currently being done.

The state of the Wiki should correspond to the latest release version as the wiki page is where users of HT will be directed to in the bView if <kbd>F1</kbd> is pressed. However, the developers' documentation should be synced to the latest version in `master` (even if this is not the latest release version)

Furthermore, preferably, we should find a way to use the GitHub wiki editor to make changes to the documentation. Moving all documentation to the main repo means that we are more restricted in terms of editor capabilities.

One possible solution is to [include the wiki as a submodule](http://brendancleary.com/2013/03/08/including-a-github-wiki-in-a-repository-as-a-submodule/).

**Comment by dariusf** [comment]
I think the simplest way is to have it be part of the main repo. Easier to see changes in PRs.

There is a [UI for previewing edited files](https://github.com/HubTurbo/HubTurbo/edit/master/readme.md), so we don't lose that much. The wiki could either be manually updated by pushing to its repo (part of the build process maybe), or could link to the main repo.

**Comment by lejolly** [comment]
Closed with #798
