### ISSUE TITLE
Give a shortcut to close an issue from pView

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#770]
Currently it takes too many steps to close an issue.

**Comment by HyungJon** [comment]
Could I know the API for closing a GitHub issue? I'd like to work on this (if no one is doing it) but I could not find the required API, so I'm not sure whether this is within my capabilities. If it can work the way I'm thinking of, I should be able to implement it soon.

**Comment by damithc** [comment]
@HyungJon If you can't find the relevant API, try something a bit easier than this one first?

**Comment by HyungJon** [comment]
I seem to have found a method that can achieve closing an issue under ```IssueServiceExtended```

```Issue returnedIssue = super.getIssue(repository, issueId);
        editIssueState(repository, returnedIssue.getNumber(),
                returnedIssue.getState().equals(STATE_CLOSED));```

but it does seem out of my league to actually implement it to run from the GUI. I will try some other issues.

**Comment by damithc** [comment]
Duplicate of #1295
