### ISSUE TITLE
User can see remaining GitHub API calls for the hour

### ISSUE THREAD

**Issue by acruis** [HubTurbo/HubTurbo#771]
Related to #765.

Will be an additional option on the Preferences tab. Tentatively, change "Preferences" to something else - currently it just has Logout and Quit.

**Comment by lejolly** [comment]
the windows way would be to put it under a `File` menu?

**Comment by acruis** [comment]
Yeah, `Logout` and `Quit` should probably go under `File`. I'm not sure about API calls though, maybe under a new tab like `GitHub`?

**Comment by lejolly** [comment]
Does it need to be under a menu or just a counter or something on the menubar/statusbar?

**Comment by acruis** [comment]
I need to show the time until the next API reset, too.

**Comment by damithc** [comment]
Can you also show some info in the status bar? I want to monitor the quota consumption, rather than check it at a specific time.

**Comment by damithc** [comment]
Renames to match the issue type (i.e. `type.story`)

**Comment by acruis** [comment]
**Prototypes:**
* Next to repo selector:
![no1](https://cloud.githubusercontent.com/assets/8437638/8642529/f5024452-2957-11e5-801e-2db3253dc572.png)
* On menu bar:
![no2](https://cloud.githubusercontent.com/assets/8437638/8642530/fb1e1be0-2957-11e5-9e93-66dd71f4f2cd.png)

**Comment by acruis** [comment]
**More prototypes:**

* Remaining calls left:

![no2](https://cloud.githubusercontent.com/assets/8437638/8648186/376f428e-2991-11e5-9ec1-4483ee689ce0.png)

* Calls made during the hour:

![no1](https://cloud.githubusercontent.com/assets/8437638/8648192/41cd4b18-2991-11e5-82c3-a2d4ed33f6ee.png)

* Refresh time as tooltip: (appears on mouseover)

![cwxlxp](https://cloud.githubusercontent.com/assets/8437638/8648200/5498ddfc-2991-11e5-9100-953d2cbf9a59.gif)

**Comment by damithc** [comment]
Something shorter like `4200/45`? i.e. `remaining count/time to next reset` We can omit 5000 and other explanatory words. Those who need it will know what it is.

**Comment by acruis** [comment]
Okay
