### ISSUE TITLE
User can name a panel

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#782]
so that user can give a descriptive name to a panel e.g. `recent high priority updates` `PRs I'm reviewing` etc.

**Comment by HyungJon** [comment]
I approached this by displaying the panel name (default: "Panel") above the filter box, and adding a small button that allows the panel name to be changed. I am now writing the code for storing the panel names to json.

**Comment by HyungJon** [comment]
Since there are two bits of information being stored per panel, I believe the cleanest and most efficient way to store both name and filter into json is to use a separate class that encapsulates the two.

**Comment by damithc** [comment]
#781 may be good issue to do before doing this one.

**Comment by HyungJon** [comment]
It doesn't appear to be a pre-requisite, but I see the relation. I think it might be smoother to submit a PR that fixes both.

**Comment by HyungJon** [comment]
I completed the new function and confirmed it doesn't clash with existing tests. I will create suitable test cases and look into #781 next, and then try to improve the visual format.

**Comment by damithc** [comment]
It is not good to do more than one thing in a single PR because that makes
PRs hard to undo later. So if you do both issues, submit two PRs. Yes, it
is not a prerequisite, just that #781 is along the same lines but less
complicated.

**Comment by HyungJon** [comment]
I am almost done with creating tests now, but I'm having some difficulty with dragging panels. I used ```drag("#dummy/dummy_col1_closeButton").to("#dummy/dummy_col0_closeButton");``` (which is same as that used in ```PanelsTest```), but the panel doesn't move properly and moves back to the right of the intended position after the movement.

**Comment by damithc** [comment]
May be create a PR so that @lejolly or @acruis  can have a look? Also add a comment to show which specific part of the code is giving problems. By the way, this issue is not directly related to dragging panels, so I'm wondering why you need to drag panels in your tests.

**Comment by HyungJon** [comment]
The panel names need to be stored, so I added tests to make sure the names will be stored in the right order when a panel is created, deleted and dragged.

For now I will submit a PR without testing panel swap then.

**Comment by HyungJon** [comment]
I'll just submit a PR with only the name and rename function added, without saving the name. It's getting too big for one PR, so I'll create a separate issue that caters to saving panels based on name and filter.

**Comment by damithc** [comment]
A PR should as as small as you can make it, but it should contain a
meaningful change. Ability to name panels without ability to save the name
is not meaningful, so both should be in the same PR.

**Comment by HyungJon** [comment]
It looks like my changes aren't compatible with the update to master today. I'll start fresh from the new master. I will leave the problem with boards for another issue.

**Comment by damithc** [comment]
Rather than starting a new PR, the standard procedure is to merge the new
master to your branch and resolve any conflicts.
