### ISSUE TITLE
t.s should match type.story rather than type.research

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#785]
intuitively t.s should match type.story rather than type.research

**Comment by lejolly** [comment]
currently it's using a `String.contains` to match the second part, would a `String.startswith` make more sense? we could use `startswith` first and if there are no matches, switch to `contains`?

**Comment by damithc** [comment]
Another approach: if `contains` has multiple matches, we choose the one that is closest from the starting letter? On a related note, should we look for a third party string matching library rather than write our own algo? Can create it as a separate `type-research` issue.

**Comment by lejolly** [comment]
should be fixed with 3f251ad6127f46515ae47cdce215e55e82b712d3

**Comment by lejolly** [comment]
Closed with #759
