### ISSUE TITLE
Add  divider between label groups

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#786]
... to make it look more organized. A blank line or a subtle divider line?
![image](https://cloud.githubusercontent.com/assets/1673303/8714843/55530fca-2bac-11e5-88e3-1390b827feef.png)

**Comment by lejolly** [comment]
alternatively we could just group them as such:

feature
`aaa` `bbb` `ccc`

priority
`high` `low` `medium` `urgent` `zero`

etc

**Comment by damithc** [comment]
Yes, that is even better.
