### ISSUE TITLE
Sometimes, changes to label are not shown in the pView immediately after closing the label picker

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#788]
Sometime the new labels show up in the pView fairly quickly, but sometimes it takes quite a while. Not sure if the data refresh is getting in the way of updating the labels.

**Comment by lejolly** [comment]
i think they're only shown after receiving a successful response from github. right @acruis?

**Comment by acruis** [comment]
Yes, that's correct. It probably makes more sense to pre-empt the change in the UI before the response comes back, do you want to make a new issue for that?

**Comment by damithc** [comment]
Duplicate of #974
