### ISSUE TITLE
Label picker doesn't work if the bView is not showing the selected issue

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#791]
As the bView is no longer involved in picking labels, the label picker should work irrespective of what is displayed in the bView?

**Comment by lejolly** [comment]
sure, but in this case do we still want to bring the user back to the issue/pr page after the labels have been selected?

**Comment by damithc** [comment]
Perhaps no need. GitHub web interface automatically updates to sync with backend, so no need to refresh the webpage at all?

**Comment by lejolly** [comment]
the page automatically updates but the labels don't appear in the sidebar. they do appear as an event in the conversation view.

**Comment by lejolly** [comment]
which is why a refresh of the page is needed for them to appear.

**Comment by lejolly** [comment]
@damithc so should we keep the refresh after changing labels?

**Comment by damithc** [comment]
I see. Can we refresh only if it the right page?

**Comment by lejolly** [comment]
By right page do you mean that particular issue's page or any issue page?

**Comment by damithc** [comment]
The two options of what to do after user press enter on the label picker:
1. Reload that issue page no matter what the page bView was showing earlier 
2. Reload the bView only if it is already showing that particular issue
I'm ok with both.

**Comment by lejolly** [comment]
i've implemented 2 in c43502bef0cf22bdcec8be9a3cc26a4b0ec8de96

**Comment by lejolly** [comment]
Closed with #759
