### ISSUE TITLE
Change Eclipse development environment to use Gradle

### ISSUE THREAD

**Issue by lejolly** [HubTurbo/HubTurbo#792]
[Gradle has joined the Eclipse Foundation and is working to make it a first-class citizen in Eclipse. ](https://gradle.org/press-release/eclipse-gradle/)

For now, official support is still optional and must be installed using this [plugin](http://marketplace.eclipse.org/content/buildship-gradle-integration). After installation, one can just import the repo as a Gradle project directly into Eclipse. It will then download all necessary dependencies, etc. 

It seems to work (although not all the gradle tasks are visible), but I've tested assembling, testing and even checks (which include checkstyle). For a fresh installation of Eclipse, this is an easier option because the source, test, and resources folders do not need to be defined by the user. 

So shall we remove all Eclipse related files as well as the jars? I can then update the developer documentation.

**Comment by damithc** [comment]
Yes, why not :+1:

**Comment by dariusf** [comment]
Sounds great. We build some jars ourselves (EGit), so we should probably keep those around.

**Comment by lejolly** [comment]
Oh we did? It seems to work fine without the whole `lib` folder.

**Comment by damithc** [comment]
@dariusf what was the reason for building our own Egit? Do we need to continue doing that?

**Comment by dariusf** [comment]
The reason is that the [official](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.eclipse.mylyn.github%22) [builds](https://oss.sonatype.org/index.html#nexus-search;quick~org.eclipse.egit.github.core) are really outdated (from 2013), and some weird behaviour we were experiencing went away after upgrading (#502). I remember making some changes to how we handled ETags around that time, though, so I'm not sure if it was really the upgrade that fixed things.

**Comment by damithc** [comment]
Looking back, #502 could have been caused by running out of API quota. :-p @lejolly gradle is able to get the latest version of EGit? Let's try to avoid changing Egit, but if we have to change, let's add the relevant file into our repo so that we keep track of our changes.

**Comment by lejolly** [comment]
Gradle is getting EGit from [here](http://mvnrepository.com/artifact/org.apache.servicemix.bundles/org.apache.servicemix.bundles.egit.github.core) which seems to be the latest version (as checked from https://github.com/apache/servicemix-bundles).

**Comment by dariusf** [comment]
2.1.5 is quite old. We are using 3.7, and they've since moved on to [4.0](https://github.com/eclipse/egit-github/tree/master/org.eclipse.egit.github.core).

**Comment by lejolly** [comment]
I think the later version numbers are for the [Eclipse EGit Github Connector](https://github.com/eclipse/egit-github) and not the core (which is what we're using), 2.1.5 seems to be the latest version on [Sonatype](https://oss.sonatype.org/index.html#nexus-search;quick~org.eclipse.egit.github.core).

**Comment by dariusf** [comment]
Yeah, but that version is 2 or more years old. There have been additions to the GitHub API since then, and changes in the core subdirectory in the past 4 months at least.

I'm just concerned that the latest builds are not up to date with the current API.

**Comment by lejolly** [comment]
Ok, updated the EGit version straight from eclipse's repository in cb15485773e3983bbbf7d3f8d195cc396f128dd5.
