### ISSUE TITLE
Implement toString() for classes in backend.resource and backend.resource.serialization

### ISSUE THREAD

**Issue by ndt93** [HubTurbo/HubTurbo#794]
So that it's more convenient for logging and debugging

**Comment by ndt93** [comment]
I'm implementing this to troubleshoot the json explosion. If this issue is accepted I will make a pull request.

Another note is that most classes in `backend.resource` already have partial `toString()` so I won't change it since it can affect other part of the code. The full toString() will be implemented in their serializable counterparts. A trick to log the full non-transient data of a resource is converting it to the serializable version first: `(new SerializableIssue(turboIssue)).toString()`

**Comment by damithc** [comment]
@lejolly @acruis any thoughts? if no objections, @ndt93 can go ahead and create a PR for this.

**Comment by lejolly** [comment]
I'm fine with this, @acruis?

**Comment by acruis** [comment]
Go ahead @ndt93
