### ISSUE TITLE
Move both user and dev docs to main repo

### ISSUE THREAD

**Issue by lejolly** [HubTurbo/HubTurbo#797]

**Comment by damithc** [comment]
duplicate of #764

**Comment by lejolly** [comment]
@damithc are we considering using gh-pages? it would look a lot nicer but that would mean 2 PRs for each change, one for code (to master) and one for documentation (to gh-pages).

**Comment by damithc** [comment]
I'm not sure if it is worth the extra effort. Just look nicer, more things to learn and harder to maintain too right? Besides, the 2 PR thing is going to be annoying. Let's not go there at this time, but we can consider it when we have no other urgent things to do.

**Comment by lejolly** [comment]
ok then
