### ISSUE TITLE
ChromeDriverTest failure

### ISSUE THREAD

**Issue by HyungJon** [HubTurbo/HubTurbo#802]
Lines 68, 70 and 156 in ```ChromeDriverTest``` have ```assertEquals(GitHubURL.DOCS_PAGE, url);``` instead of ```GitHubURL.getPathForDocsPage```, causing the test to fail because it retrieves ```.../blob/%s/docs/...``` instead of ```.../blob/V2.9.0/docs/...```

Is this intended, or should this be changed?

**Comment by acruis** [comment]
Should be changed. Can you fix this?

**Comment by lejolly** [comment]
@HyungJon actually leave this to me, there's some shuffling of user doc pages to settle too.
