### ISSUE TITLE
Duplicate panel ID assignment

### ISSUE THREAD

**Issue by HyungJon** [HubTurbo/HubTurbo#808]
In ```FilterPanel```, when assigning an ID to its components like filter text field and close button, the ID is set based on the panel index when created. This allows duplicates ID.

e.g.1 create a panel to the right and then delete the first one, resulting in 2 filter text fields with the ID #dummy/dummy_col1_filterTextField.
e.g.2 create panels to the left, resulting in multiple filter fields with the ID #dummy/dummy_col0_filterTextField.

This isn't a big problem for normal usage, but could affect future tests when more extensive panel testing is added.

**Comment by dariusf** [comment]
Panels are already given an index which is updated on panel addition/removal. Could that be used to give child nodes ids?

**Comment by HyungJon** [comment]
Yes. Updating the IDs to use the panel index every time ```updatePanelIndices``` is called would be a good solution.

**Comment by HyungJon** [comment]
Will start after #807 is merged.

**Comment by HyungJon** [comment]
Discussion moved to #933
