### ISSUE TITLE
Repo field of login dialog is case sensitive

### ISSUE THREAD

**Issue by acruis** [HubTurbo/HubTurbo#812]
1. Open `TEAMMATES/repo` in HubTurbo
2. Logout from HubTurbo (File -> Logout)
3. Start HubTurbo again.
4. Specify `teammates/repo` in the login dialog

In step 4, HubTurbo will attempt to redownload teammates/repo even though `TEAMMATES-repo.json` already exists in store.

**Comment by dariusf** [comment]
This problem occurs anywhere a repo id is used as a key.

I guess the long-term solution would be a `RepoId` class with `hasCode` that normalises differences in case. We may want to make our own instead of using the GitHub version in case we want to add methods.
