### ISSUE TITLE
Standardize naming in user docs

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#817]
.md files, .png files and folders do not follow a consistent naming convention.

**Comment by lejolly** [comment]
how about `Creating-a-Release.md`, `Design-Decisions-and-Guidelines.md` and `Development-Environment.md`?

**Comment by damithc** [comment]
Only user docs for now. Dev docs to be done later.

**Comment by lejolly** [comment]
Ah ok
