### ISSUE TITLE
Additional steps for developers on 64 bits Linux

### ISSUE THREAD

**Issue by ndt93** [HubTurbo/HubTurbo#826]
The provided chromedriver_linux is 32 bits and doesn't work on a typical 64 bits Linux installation. So we either add a note in the developer/user guide for installing 32 bits support on 64 bits Linux (which is quite painful :P since in addition to installing base architecture support, a bunch of 32 bits libraries dependencies for chromedriver are also needed, most of which are not easily obtained and configuration steps differ between distributions).

Or we can provide support in HubTurbo using something like this to check for os architecture:
```java
Runtime.getRuntime().exec("uname -m");
```

I had this problem from the beginning and used the former method to resolve it but haven't mentioned it since I thought Linux is not supported. But now, it's mentioned in the developer's guide so well :P. Any opinion from the dev team?

**Comment by lejolly** [comment]
i'm sure we can easily include the 64 bit version of the linux chromedriver if proper detection can be added in `util.PlatformSpecific`, although i won't be able to test it though (unless i get a vm).

**Comment by ndt93** [comment]
Yah, the abstraction is really good for this kind of stuffs there. I can implement and test it if everyone agrees to use the latter method.

**Comment by damithc** [comment]
Go ahead Thien.
