### ISSUE TITLE
Recently updated issues not appearing in the feed panel

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#856]
This issue has an update 8 minutes ago, but it is not appearing in my panel. The filter is `(repo:hubturbo/hubturbo OR repo:powerpointlabs/powerpointlabs OR repo:teammates/repo) updated:12 is:unread sort:nonSelfUpdate`
![image](https://cloud.githubusercontent.com/assets/1673303/9130960/aa623b52-3d19-11e5-9bf4-1da7f24832a3.png)

**Comment by damithc** [comment]
That issue is not 'read' and doesn't appear even if I remove the `is:unread` filter. This happened a few times in the last few days. One reason could be that I've run out of API quota, but the API count shown on the UI seems fine.

**Comment by damithc** [comment]
Further observation: the missing issue appeared after I restarted HT.

**Comment by acruis** [comment]
The culprit is the `updated:12`, probably the same problem as #748.

**Comment by damithc** [comment]
Closing because of duplicate.
