### ISSUE TITLE
There should be a way to navigate between tabs of a PR

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#869]
as per title

**Comment by rd1992** [comment]
What keyboard shortcuts should we assign to this? I was thinking of using (**F**)iles and (**C**)ommits

**Comment by damithc** [comment]
For conversation? There should be a way to come back to the conversation tab.

**Comment by rd1992** [comment]
picking this up again. Instead of having different keys, can we use one key to use to just toggle between tabs? For example by default we are on the `Conversation` tab. Pressing a key, for example `t`, the `commits` tab becomes active. Another press of `t` will move to `Files`

**Comment by damithc** [comment]
Usually I know which tab I want to jump to. So having to tab is a pain, and time consuming too (tab loading takes time).

**Comment by rd1992** [comment]
hmm. okay so how about this? keep `F` for Files and `C` for commits tab. And `R` for conversation tab since we already use `R` for comments. If conversation tab is already loaded we jump to the new comment box. Else jumps to the conversation tab

**Comment by damithc** [comment]
Sounds good

-- 
Sent from a mobile device.

**Comment by rd1992** [comment]
Just realised can't use `f`. Already used for changing panels. @damithc you got any ideas for key we could use for files changed?

**Comment by rd1992** [comment]
Just realised can't use `f`. Already used for changing panels. @damithc you got any ideas for key we could use for files changed?

**Comment by damithc** [comment]
`g,r`, `g,c`, `g,f` ?
