### ISSUE TITLE
User can undo a change to the label 

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#870]
... so that user can use the label picker fast in the safety of the knowledge that any mistake can be undone.
similar to Gmail 'undo send' feature?

**Comment by lejolly** [comment]
probably just implement some backend delay? we'll update the ui immediately but hold off sending the change to github.

**Comment by damithc** [comment]
Yes, with the appropriate UI presentation. e.g. an extra icon to indicate that the issue is waiting to be updated.
