### ISSUE TITLE
Right click issues to show possible actions

### ISSUE THREAD

**Issue by LowWeiLin** [HubTurbo/HubTurbo#883]
For example, to assign labels like the 'L' shortcut key

**Comment by dariusf** [comment]
Besides the label picker, what else can we put in the context menu? Mark as read?

**Comment by LowWeiLin** [comment]
Read/unread, open in github, set assignee, milestone (if the features exists)?

**Comment by ndt93** [comment]
I will implement this with read/unread and label picker since they are tied to each issue and are not available in the main menu. Other items can be requested to be added in separate issues.
