### ISSUE TITLE
Support 'sort:assignee'

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#889]
As per title

**Comment by damithc** [comment]
This could be useful in CS2103, hence the high priority

**Comment by ndt93** [comment]
Should issues with no assignee comes first or later in the normal sorted list?

**Comment by damithc** [comment]
Not sure. What's the norm? When sorting strings, empty string come at the beginning or end? I think at the end is better, as there could be many issues without assignees.

**Comment by ndt93** [comment]
Empty string usually come first. I think at the end is more tidy although some people may prefer to see unassigned issues first to know which ones are not handled. Our assignee field is wrapped in an `Optional` object so we will have to handle it separately from strings if it's not assigned.

I will put them at the end for now then.

**Comment by damithc** [comment]
Yes, go ahead. Users can use `-has:assignee` or `sort:-assignee` if they are interested in seeing non-assigned ones first.
