### ISSUE TITLE
Allow longer names for panels

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#892]
Current max limit (38?) is a bit limiting. In my screen, there is space for more. May be use a 'flow' layout? i.e. if the name is too long for one line, it overflows to next line.

**Comment by HyungJon** [comment]
Shall I set a limit to how many lines the name can overflow to? Maybe around 3~5 lines.

I will also see if I can make the text overflow at spaces rather than any character, to make it neater.

**Comment by damithc** [comment]
I don't think we need to bother setting a limit. If the user does a weird thing such as enter a paragraph for panel name, it is fine to let him/her suffer a non-optimal behavior.

**Comment by HyungJon** [comment]
Done. Now the testing is going to be rather troublesome, since there's no validation any more. Only the overflow is happening based on text width, and because of this any testing of the names will have to use exactly the same algorithms to create the expected result to compare against, which will then be self-proving. Shall I remove name validation tests altogether and test only the panel renaming functionality?

**Comment by damithc** [comment]
If the mechanism to limit length is already in place, you can impose a limit (about three lines's length?)

**Comment by HyungJon** [comment]
I removed it. On more consideration, I should be able to test names that are longer than the width, then check whether the name will overflow properly by counting the number of newlines inserted.

**Comment by damithc** [comment]
Wait, you are adding line breaks manually? I thought line wrapping should be handled automatically by the UI control?

**Comment by HyungJon** [comment]
I'm adding spaces to prevent the text overflowing to the next line in the middle of a word, for tidiness. Unless there's a way to set ```javafx.scene.text.Text``` to do it automatically?

**Comment by HyungJon** [comment]
Oh... never mind. ```Text``` does seem to automatically do pretty wrap, which would make my implementation redundant. What kind of testing for names shall I do then?

**Comment by damithc** [comment]
I guess this will be hard to test because it is a visual adjustment. May be modify some of the test cases to have some long names?
