### ISSUE TITLE
Use better looking icons for panels

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#893]
These are OK, but can be better
![image](https://cloud.githubusercontent.com/assets/1673303/9423223/e82eea7c-48ed-11e5-9756-6e406cfb5503.png)

**Comment by acruis** [comment]
We can make use of GitHub octicons which are already [in the repo](https://github.com/HubTurbo/HubTurbo/blob/master/src/main/resources/ui/octicons/octicons.css).

Of relevance to us are [edit](https://octicons.github.com/icon/pencil/) and [close](https://octicons.github.com/icon/x/).

**Comment by dariusf** [comment]
If we use octicons, this can be a beginner issue.
