### ISSUE TITLE
Add a way to filter out self updates from the 'updated' filter

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#898]
e.g. some special character to indicate that self updates should be ignored

**Comment by codemanmeet** [comment]
Should we call the filter "updated-self"?

**Comment by damithc** [comment]
Is it possible to use a symbol such as `^`? @dariusf what do you think?

**Comment by codemanmeet** [comment]
I feel it might not be that intuitive, as `^` might also mean "not updated", which is not what we want. We want to filter by "updated by not-self" or "updated by others".

**Comment by damithc** [comment]
I would like it to be something that can apply in multiple places. e.g. the sort filter current called `nonSelfUpdate` should also be renamed to follow the same convention. That's why I'm looking for a symbol. `-self` sounds fine if it is interpreted as `minus` but some might view it as an additional attribute in which case it should be `-nonSelf`. Any other symbol we can use? How about `+`?

**Comment by damithc** [comment]
Or `%`?

**Comment by codemanmeet** [comment]
We should not ideally start a filter name with a symbol. If we want a negation of that filter, it might look something like this - `~%updated` which might not look neat. I feel the word `self` should still be used in this context as it is more intuitive than any symbol and would click with the user much easily. How about we call it "updatedBySelf"?

**Comment by codemanmeet** [comment]
I was thinking multiple scenarios through and figured that the best way to do this would be to have two separate filters - `updatedByOther` and `updatedBySelf` to avoid any confusion. The negation of `updatedByOther` would be all un-updated issues and self-updated issues while the negation of `updatedBySelf` would be all un-updated issues and other-updated issues. What do you think?

**Comment by codemanmeet** [comment]
@damithc @dariusf

**Comment by dariusf** [comment]
So you're suggesting something like `updated:2 updatedBySelf:false` to show all non-self updates in the past 2 hours?

I think a symbol would be useful if we have this self/non-self split for other qualifiers. There's also the possibility of supporting multiple aliases (including with symbols) for the same thing, with `updated` defaulting to one of them.

**Comment by codemanmeet** [comment]
Yup, you're right. But there is one issue. Let's say we use the symbol on updated like - `%updated` to indicate "updated by self" but what if you want "updatedByOther". The negative of "updated by self" is not updated by other. How do we solve this issue. My suggestion was to use `updatedBySelf:<2` actually.

**Comment by dariusf** [comment]
I think I misunderstood. What I thought you meant was to have a second qualifier to filter by whether or not the last update was done by the user, with no relation to update time.

This may be a viable alternative. Since your `updatedBySelf` is a conjunction of two things, splitting them would keep the semantics of `updated` simple, and avoid the confusing behaviour with negation.

**Comment by codemanmeet** [comment]
@damithc @dariusf Shall I go ahead with the implementation of `updatedBySelf` and `updatedByOther` then?

**Comment by dariusf** [comment]
Wait, we should consider the possibility of moving the self/non-self check into another qualifier. Keeping qualifiers simple makes them more composable.

**Comment by damithc** [comment]
I meant add the symbol at the end, not at the beginning. 
I'm not sure if 'non-self' thing is composable. It might be context dependent. For example, `updated%:2' means filter issues updated within last 2 hours by others and `sort%: updated` means sort based on last non-self update. `updated%:2 sort:updated` would be slightly different from `updated:2 sort%:updated` right?

**Comment by codemanmeet** [comment]
Yup, this works, but the problem of negation is still not solved. The negation of `updated by others`, represented by `~updated%:2` would still not yield `updated by self`. Same for sort. 

How will we represent `updated by self`?

**Comment by dariusf** [comment]
Okay, so we should stick to using single qualifiers.

I don't think the problem with negation can be avoided, because `~updated%:2` is `~(updated:2 && updatedBySelf:false)`, which is `~updated:2 || updatedBySelf:true`. It's an inherent part of having them combined, and we don't want to split them.

**Comment by codemanmeet** [comment]
@dariusf and I had a discussion regarding the format for the qualifiers for this issue and decided to go with `updatedBySelf` and `updatedByOthers`

**Comment by damithc** [comment]
Let's discuss at the meeting today. I prefer using a symbol.
