### ISSUE TITLE
'-label:p.' does not match issues without label group 'p'

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#903]
In TEAMMATES, priority labels are given as `p.*`. I was trying to use `-label:p.` to find issues without a priority, but it did not work.

**Comment by dariusf** [comment]
I can't reproduce this. It may be a parsing bug. Was that the full filter?

**Comment by damithc** [comment]
Here it is. I was looking for open issues that don't have a priority.
![image](https://cloud.githubusercontent.com/assets/1673303/9513453/e49ac9f2-4cc2-11e5-9ce8-5fbca861d06a.png)

**Comment by dariusf** [comment]
I managed to reproduce this on another Windows machine with a freshly-downloaded cache, but still can't locally (Mac, Java 1.8.0_60). Could you try deleting `teammates-repo.json`, then restarting HT? If it still happens for you, it's likely to be a platform-/Java version-specific issue.

**Comment by damithc** [comment]
Refreshing the cache did not fix the problem. Did it twice. My java version is 1.8.0_51. Perhaps add more logging to help us troubleshoot?

**Comment by dariusf** [comment]
Found the problem and was able to reproduce. Turns out some refactoring I did to locate the bug hid it.
