### ISSUE TITLE
Ctrl+R is triggering a 'reply' action

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#907]
When I use the Ctrl+R shortcut, it changes the repo, but also trigger a 'reply' action.

**Comment by HyungJon** [comment]
Happens because of overlapping ```KeyCode.R``` and both are registered to pView. Either action will have to be assigned to another key.

How about '''KeyCode.C''' for adding comment, since the name used in GitHub is comment rather than reply?

**Comment by damithc** [comment]
One is `R` and the others is `Ctrl+R` so we should be able to have both.

**Comment by HyungJon** [comment]
Found a walkaround. Added a condition for ```NEW_COMMENT``` to check whether the event clashes with ```SWITCH_DEFAULT_REPO```.

**Comment by HyungJon** [comment]
I felt reassigning the key code would be cleaner and more intuitive than adding a condition check. Anyway, I will push the PR with the check after I run a gradlew build.
