### ISSUE TITLE
Update chromedriver

### ISSUE THREAD

**Issue by lejolly** [HubTurbo/HubTurbo#917]
Doesn't seem to work reliably (if at all) with chrome 46.

**Comment by damithc** [comment]
On mac?

**Comment by lejolly** [comment]
On windows. but 46 is a dev version, i think the current one is 44.

**Comment by rd1992** [comment]
@lejolly i saw you updated to 2.18. But 2.19 came out on Aug 28. Any reason you dint update to that?

**Comment by damithc** [comment]
It's best not to update to the latest version until it's been out for a
while. So I don't mind using a slightly outdated version.

**Comment by rd1992** [comment]
yea makes sense. just the releases were less than a week apart for 2.18 and 2.19.

**Comment by damithc** [comment]
Seems to work so far. Perhaps we can load a dummy page first (e.g. a static
splash screen page from our website) and identify the window based on that?

**Comment by lejolly** [comment]
@rd1992 yeah at that time 2.19 was out in the downloads folder but the website hadn't been updated yet, so i just went with 2.18.
