### ISSUE TITLE
Implement headers iteration and ETags combination for multiple paged response from Github API

### ISSUE THREAD

**Issue by ndt93** [HubTurbo/HubTurbo#928]
Subtask 1 for #906

**Comment by ndt93** [comment]
Seems like the current resource update process only uses the ETag to determine if there are updates, in which case a complete list of a particular resource is downloaded and replaces the existing list instead of only getting updated items and merge with existing items (an exception is for issues since the API supports the `since` parameter).

So there is no point to extend the `PageIterator`. This subtask title is updated to reflect the fall back solution to iterate through the pages' headers and combine their ETags.

@dariusf You have any other ideas on this?

**Comment by dariusf** [comment]
Yes, we don't have very granular updates for other resources. If we couldn't possibly need individual pages' ETags for anything going forward, then I don't have much to add. This is the simplest thing we could do.

**Comment by ndt93** [comment]
All right, I will implement this then.

**Comment by ndt93** [comment]
Closing since #906 can be solved in 1 issue.
