### ISSUE TITLE
Display currently open board on title bar

### ISSUE THREAD

**Issue by HyungJon** [HubTurbo/HubTurbo#929]
Format: "HubTurbo V3.3.0 (Board 1)"

If there is no board open, indicate "No board open"

**Comment by HyungJon** [comment]
I'm not sure how I can test the names change by calling the methods in ```UI``` from the tests.

**Comment by damithc** [comment]
Why is this issue gone cold?

**Comment by HyungJon** [comment]
I am waiting for #950 to be merged so that I can add test cases for this feature in ```MenuControlTest```.

**Comment by damithc** [comment]
#950 merged.
