### ISSUE TITLE
Visible panel should have focus after start up

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#930]
After HT starts up, the visible panel (i.e. the first panel) should have the focus. I should be able to go to first issue by pressing `Ctrl+down`.

**Comment by HansNewbie** [comment]
I will focus the first panel on opening board as well.

**Comment by damithc** [comment]
Yes, the focus should be in the first panel even after changing boards. Good catch.

**Comment by HansNewbie** [comment]
Sorry, I did the pull request merged wrongly so this is not closed automatically. Fixed in ca91dbb84d91d0e735423cc560476643f08b544c

**Comment by damithc** [comment]
@HansNewbie you did not verify the 2nd sentence in the issue description (i.e. I should be able to go to first issue by pressing Ctrl+down.). That was the whole point of this issue. The intended outcome is more important than the mechanism. :-)

**Comment by HansNewbie** [comment]
Oops. Noted. I will look at it again.

**Comment by damithc** [comment]
Let closed issues be closed. I've already posted the problem as a new issue.

**Comment by HansNewbie** [comment]
Alright.
