### ISSUE TITLE
Improve or change panel element selection in tests

### ISSUE THREAD

**Issue by HyungJon** [HubTurbo/HubTurbo#933]
Node IDs are unreliable and immutable.

Alternative solution proposed today: add ```get``` method for each element that allows tests to select elements through ```PanelControl``` -> ```FilterPanel``` at index -> element.

This will need some way for tests to access ```PanelControl``` or ```UI``` directly.

**Comment by dariusf** [comment]
[This](https://github.com/HubTurbo/HubTurbo/issues/685#issuecomment-111802527) might help, though the approach is rather low-level and should be discussed further.

**Comment by HyungJon** [comment]
Or perhaps setting an ID for the UI itself?

**Comment by dariusf** [comment]
What do you mean?

My earlier post was a way to get a reference to a node by traversing the UI tree directly. It's low-level and breaks abstraction (i.e. it's fragile), but it sidesteps the problem of having to assign and maintain a dynamic id.

**Comment by HyungJon** [comment]
Working on this now. Can I clarify:
# How should the ```PanelControl``` be passed as a parameter? Also because If we can access it from tests, we could just use ```getPanel``` in ```PanelControl``` to get the panel directly.
# Would it be okay to add getters in ```FilterPanel``` to return elements (i.e. filterTextField, closeButton, etc)?

**Comment by dariusf** [comment]
1. As a parameter to?
2. I guess that would be fine.

**Comment by HyungJon** [comment]
For the ```UITraversal``` class. I'm going to pass ```PanelControl``` since this one is about panels.
