### ISSUE TITLE
Make Keyboard Shortcuts work in Mac

### ISSUE THREAD

**Issue by HansNewbie** [HubTurbo/HubTurbo#957]
Currently not all `Ctrl` keyboard shortcut works in Mac due to Mac OS wide shortcut (e.g. `Ctrl` + :arrow_down: is App Expose shortcut, hence will not jump to issue list). Consider using Mac `Cmd` button instead (e.g. copy in Mac is `Cmd` + `C` instead of `Ctrl` + `C` by default).

JavaFX has `KeyCode.META` for this, but I tested and it didn't work (might be version problem or JavaFX bug). It was suggested to use `KeyCode.SHORTCUT` to make OS agnostic key (it will be mapped to `KeyCode.CONTROL` in Windows and `KeyCode.META` in Mac, but no mention of Linux).

Info: http://stackoverflow.com/questions/12710468/using-javafx-2-2-mnemonic

**Comment by dariusf** [comment]
Shortcut and meta both work for me, both as `MenuItem` accelerators and when using `KeyCodeCombination::match`. Maybe the panel wasn't in focus?

**Comment by HansNewbie** [comment]
Hmm, it was. May be I missed some codes. It's good as long as it works :D

**Comment by dariusf** [comment]
It may be a bug with how focus is handled, as we implement it ourselves.

**Comment by dariusf** [comment]
I think this will make things more consistent with OS conventions, but there are other conflicts: Cmd + M is minimise/milestone, Cmd + H is reserved for hide, etc. Are we open to changing keybindings until there is no conflict?

**Comment by damithc** [comment]
Sure, we can try to change our shortcuts so that they are consistent across
the OSes and do not conflict with OS shortcuts.
