### ISSUE TITLE
Remove dead code in FilterPanel

### ISSUE THREAD

**Issue by HyungJon** [HubTurbo/HubTurbo#958]
The methods ```getCurrentName``` and ```filterByString``` in ```FilterPanel``` are not accessed anywhere, and are redundant. These two also seem to be one of the causes of frequent coverage decrease. Unless there is any future use for these, we could delete them.

**Comment by ravic1995** [comment]
There isn't any method called ```filterByString``` in ```FilterPanel```. 
But there is a method called ```getFilterByString``` and its being accessed in the ```BoardAutoCreator``` class.

**Comment by dariusf** [comment]
It's been a while, might have been removed already. I suppose for this issue you could transitively remove any dead code in the class (and possibly its superclasses). There are a couple of unused methods.
