### ISSUE TITLE
'F' key doesn't work at times

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#963]
Let's say I bring focus back to HT by clicking on the title bar. A panel is already highlighted. I press `F` to go to another panel, but it doesn't work. It starts working only if click on the panel and then press `F`.  So it seems sometimes panels are shown as if 'selected' but they don't react to keys that are supposed to work on a selected panel.

**Comment by HansNewbie** [comment]
If it is done at startup might be related to #969 which I am going to fix in the next milestone.

The case might be similar to the mentioned issue in which the `PanelControl` has the focus on such panel but the JavaFX focus is not in the panel.

**Comment by HansNewbie** [comment]
Pull request for the aforementioned issue is #982

**Comment by dariusf** [comment]
What Hans mentioned is most likely the problem. Should have been fixed in the above PR.
