### ISSUE TITLE
Adding labels rapidly interferes with undo

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#964]
e.g. 
1. add label1 to issue 1
2. before the undo window is over, add label2 to issue 2
expected: label 1 is applied to issue 1 and label2 is applied to issue 2
actual: HT shows label 1 applied to issue 1, but it is not updated in the server

**Comment by damithc** [comment]
This could be a potential 'show stopper' for anyone using the label picker, so better to fix it before we release the undo feature. @lejolly can have a look?

**Comment by lejolly** [comment]
noted, will take a look.

**Comment by damithc** [comment]
What's the delay with this one?

**Comment by lejolly** [comment]
fixing the issue is done, getting the test to run reliably on travis has been another thing altogether.

**Comment by damithc** [comment]
If the tests a passing locally, you can merge the fix now do the tests as a separate issue.
