### ISSUE TITLE
Add examples to sort documentation

### ISSUE THREAD

**Issue by dariusf** [HubTurbo/HubTurbo#965]
See discussion [here](https://github.com/HubTurbo/HubTurbo/pull/960#discussion_r39348770).

**Comment by damithc** [comment]
It's been 24 days since this started.

**Comment by rd1992** [comment]
Yeah it was supposed to be part of last milestone but dint get reviewed. You can the review the final commit in the pr above and I can merge it.

**Comment by damithc** [comment]
Based on the status, it is still `ongoing`, not `toReview` :-p
