### ISSUE TITLE
Repo list is not updated when a repo is added

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#967]
It seems the repo list (given under `Repos`) menu is not updated when a new repo is downloaded by typing the repo in a filter. The same goes for the repo dropdown.

**Comment by damithc** [comment]
Correction: the dropdown seems to be updated (I didn't notice it because the new repo was out of the view area). But the list under the `Repos` menu is not updated.

**Comment by HansNewbie** [comment]
@damithc this was intended so that currently active repo - default repo and repos in filters - cannot be removed (hence no redownloading of the repos right after removing).

**Comment by damithc** [comment]
It looks odd though. When a repo is added, user expect to see it any 'repo list'. I think it's better to add it to the list but prevent them from being removed later. e.g. show it as `repo name (being used; cannot remove)`. But not urgent.
