### ISSUE TITLE
updated-others and updated-self not working

### ISSUE THREAD

**Issue by codemanmeet** [HubTurbo/HubTurbo#968]
The filters `updated-others` and `updated-self` do not show issues after filtering.

**Comment by damithc** [comment]
I think in the past we pull meta-data only if `updated` filter is present. Without that filter, no metadata will be present and the new `updated-self/others` filters will not work. I think pulling of metadata should happen for any `updated*` filter. Furthermore, the display should show the updates inside the issue card if any of those filters are present.

**Comment by damithc** [comment]
We can't do the next release without fixing this bug.

**Comment by damithc** [comment]
what's the progress on this? The deadline for releasing this version is today.

**Comment by codemanmeet** [comment]
Working on it

**Comment by codemanmeet** [comment]
Submitted a PR.

**Comment by damithc** [comment]
Reminder: We cannot do a public release until this is fixed. @codemanmeet do you like @dariusf or @acruis to take over this issue?

**Comment by codemanmeet** [comment]
Yup, that would be great. I'm still not able to determine the problem even after changing `meta-qualifier` and `qualifier` lists that decide metadata downloading.

**Comment by damithc** [comment]
@dariusf or @acruis can one of you take over. This issue is holding up the release pipeline.

**Comment by dariusf** [comment]
I'll do it. @acruis can review.

**Comment by damithc** [comment]
Great. Thanks both.

**Comment by codemanmeet** [comment]
Thanks guys!
