### ISSUE TITLE
Focus goes to wrong filter after start up

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#969]
Actual: the first panel is selected, but the cursor is in the filter box of the last panel
Expected: the first panel is selected, cursor is not in any filter box. **At this point user should be able to use F/D to navigate panels and Ctrl+down to enter a panel**

**Comment by HansNewbie** [comment]
@damithc Right now Ctrl+down only works when the focus is on the filter box. So if the focus is on the panel (as per requested), pressing Ctrl+down will not enter the panel. The way to do it for now is pressing 2xSpace (to go to filter box) then Ctrl+down to go to issue list, or Ctrl+1 to go to first issue.

Do you want a new keyboard shortcut to go to issue list upon pressing Ctrl+down when focus is on panel?

**Comment by damithc** [comment]
For this issue, use ctrl+1 to jump to the first issue. We need to tidy up various ways of entering the issue list, but that can be done as a separate issue.

**Comment by HansNewbie** [comment]
Alright, noted.
