### ISSUE TITLE
Support ReviewComment and CommitComment in GithubClientEx

### ISSUE THREAD

**Issue by ndt93** [HubTurbo/HubTurbo#970]
Subtask of #654 

*egit* does not support Review Comments, so we need to interact directly with Github API for this.

**Comment by dariusf** [comment]
While we're at it, can we rename all the subclasses we use for consistency? `LabelServiceFixed`, `GitHubClientExtended`, etc. can all just have the 'Ex' suffix.

**Comment by ndt93** [comment]
Ok, sure. I will look into those.

**Comment by damithc** [comment]
This is a backend change that does not change the end-user features yet, right?

**Comment by ndt93** [comment]
Yup, the integration with end-user will be done for the next milestone.
