### ISSUE TITLE
Add a windows script to update to latest master

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#973]
This for devs to use (at least I need this, because I update my HT whenever there is an update to master).

0. pull latest master
1. shut down the running instance of HT
2. build without tests (e.g. `gradlew build -x test`)
3. launch newly-build HT

**Comment by damithc** [comment]
@acruis consider priority when taking issues. We should finish higher priority ones first.

**Comment by acruis** [comment]
This should be a quick one.
