### ISSUE TITLE
'updated' filter only shows comments

### ISSUE THREAD

**Issue by ndt93** [HubTurbo/HubTurbo#976]
![image](https://cloud.githubusercontent.com/assets/5065989/9875625/194f8632-5be2-11e5-9bb4-1298ab6a6ed8.png)

![image](https://cloud.githubusercontent.com/assets/5065989/9875669/8f5439b8-5be2-11e5-88b1-2f89e0a38e4e.png)

**Comment by damithc** [comment]
Yup. Must add a test case to catch the bug before fixing it. Otherwise this regression can happen again.

**Comment by damithc** [comment]
Caused by #748? @acruis 
I have a version that is just before #748 and it doesn't have this problem.

**Comment by acruis** [comment]
@damithc Yep, it's #778 (there's a typo in the merge message). Will fix ASAP.
