### ISSUE TITLE
Nothing shown in the panel on mac

### ISSUE THREAD

**Issue by lizan96** [HubTurbo/HubTurbo#978]
This is what my panel looks like
<img width="447" alt="2015-09-16 11 39 14" src="https://cloud.githubusercontent.com/assets/12683581/9895895/b3559dd6-5c67-11e5-9872-ec8843a0a389.png">

This is my java version.
<img width="575" alt="2015-09-16 11 41 11" src="https://cloud.githubusercontent.com/assets/12683581/9895910/dfb177d8-5c67-11e5-9092-de3467b1a7a5.png">

**Comment by lizan96** [comment]
Here is my HubTurbo log. Since my mac language is Chinese. 九月 means September.

804 16 九月 2015 10:53:32 INFO UI [JavaFX Application Thread] - V3.5.1
856 16 九月 2015 10:53:32 INFO KeyboardShortcuts [JavaFX Application Thread] - No user specified keyboard shortcuts found, using defaults. 
856 16 九月 2015 10:53:32 INFO KeyboardShortcuts [JavaFX Application Thread] - Loading user specified keyboard shortcuts. 
857 16 九月 2015 10:53:32 INFO KeyboardShortcuts [JavaFX Application Thread] - Assigning <E> to MARK_AS_READ
857 16 九月 2015 10:53:32 INFO KeyboardShortcuts [JavaFX Application Thread] - Assigning <U> to MARK_AS_UNREAD
857 16 九月 2015 10:53:32 INFO KeyboardShortcuts [JavaFX Application Thread] - Assigning <I> to SCROLL_TO_TOP
858 16 九月 2015 10:53:32 INFO KeyboardShortcuts [JavaFX Application Thread] - Assigning <N> to SCROLL_TO_BOTTOM
858 16 九月 2015 10:53:32 INFO KeyboardShortcuts [JavaFX Application Thread] - Assigning <J> to SCROLL_UP
858 16 九月 2015 10:53:32 INFO KeyboardShortcuts [JavaFX Application Thread] - Assigning <K> to SCROLL_DOWN
859 16 九月 2015 10:53:32 INFO KeyboardShortcuts [JavaFX Application Thread] - Assigning <D> to LEFT_PANEL
859 16 九月 2015 10:53:32 INFO KeyboardShortcuts [JavaFX Application Thread] - Assigning <F> to RIGHT_PANEL
859 16 九月 2015 10:53:32 INFO KeyboardShortcuts [JavaFX Application Thread] - Assigning <T> to UP_ISSUE
860 16 九月 2015 10:53:32 INFO KeyboardShortcuts [JavaFX Application Thread] - Assigning <V> to DOWN_ISSUE
909 16 九月 2015 10:53:32 INFO UI [JavaFX Application Thread] - Registered event handler OpenReposChangedEventHandler
976 16 九月 2015 10:53:32 INFO UI [JavaFX Application Thread] - Registered event handler UpdateProgressEventHandler
1000 16 九月 2015 10:53:32 INFO UI [JavaFX Application Thread] - Registered event handler IssueSelectedEventHandler
1001 16 九月 2015 10:53:32 INFO UI [JavaFX Application Thread] - Registered event handler PanelClickedEventHandler
1003 16 九月 2015 10:53:32 INFO UI [JavaFX Application Thread] - Registered event handler ShowRenamePanelEventHandler
1007 16 九月 2015 10:53:32 INFO TickingTimer [JavaFX Application Thread] - Started TickingTimer Browser Request Delay Timer
1008 16 九月 2015 10:53:32 INFO UI [JavaFX Application Thread] - Registered event handler IssueSelectedEventHandler
1009 16 九月 2015 10:53:32 INFO UI [JavaFX Application Thread] - Registered event handler IssueCreatedEventHandler
1010 16 九月 2015 10:53:32 INFO UI [JavaFX Application Thread] - Registered event handler LabelCreatedEventHandler
1012 16 九月 2015 10:53:32 INFO UI [JavaFX Application Thread] - Registered event handler MilestoneCreatedEventHandler
1013 16 九月 2015 10:53:32 INFO UI [JavaFX Application Thread] - Registered event handler ModelUpdatedEventHandler
1014 16 九月 2015 10:53:32 INFO UI [JavaFX Application Thread] - Registered event handler UpdateRateLimitsEventHandler
1016 16 九月 2015 10:53:32 INFO UI [JavaFX Application Thread] - Registered event handler ShowErrorDialogEventHandler
1035 16 九月 2015 10:53:32 INFO UI [JavaFX Application Thread] - Registered event handler BoardSavedEventHandler
1036 16 九月 2015 10:53:32 INFO UI [JavaFX Application Thread] - Registered event handler OpenReposChangedEventHandler
2619 16 九月 2015 10:53:34 INFO UI [JavaFX Application Thread] - Registered event handler ClearLogicModelEventHandler
2620 16 九月 2015 10:53:34 INFO UI [JavaFX Application Thread] - About to trigger event ModelUpdatedEvent
2623 16 九月 2015 10:53:34 INFO UI [JavaFX Application Thread] - Triggered event ModelUpdatedEvent
2624 16 九月 2015 10:53:34 INFO TickingTimer [JavaFX Application Thread] - Started TickingTimer Refresh Timer
2625 16 九月 2015 10:53:34 INFO TickingTimer [JavaFX Application Thread] - Started TickingTimer Notification Pane Timer
24149 16 九月 2015 10:53:55 INFO LoginController [pool-9-thread-1] - Logging in as lizan96
29818 16 九月 2015 10:54:01 INFO GitHubSource [pool-4-thread-1] - Logged in to GitHub as lizan96
29901 16 九月 2015 10:54:01 INFO UI [JavaFX Application Thread] - About to trigger event PrimaryRepoChangedEvent
29903 16 九月 2015 10:54:01 INFO UI [JavaFX Application Thread] - Triggered event PrimaryRepoChangedEvent
29903 16 九月 2015 10:54:01 INFO UI [JavaFX Application Thread] - About to trigger event BoardSavedEvent
29904 16 九月 2015 10:54:01 INFO UI [JavaFX Application Thread] - Triggered event BoardSavedEvent
29906 16 九月 2015 10:54:01 INFO BrowserComponent [JavaFX Application Thread] - Using chrome driver binary: chromedriver_2-18
29984 16 九月 2015 10:54:01 INFO BrowserComponent [JavaFX Application Thread] - Could not find chromedriver_2-18; extracted it from jar
29985 16 九月 2015 10:54:01 INFO BrowserComponent [JavaFX Application Thread] - Logging in on GitHub...
30166 16 九月 2015 10:54:01 INFO UI [JavaFX Application Thread] - Registered event handler ModelUpdatedEventHandler
30252 16 九月 2015 10:54:01 INFO UI [JavaFX Application Thread] - About to trigger event OpenReposChangedEvent
30253 16 九月 2015 10:54:01 INFO UI [JavaFX Application Thread] - Triggered event OpenReposChangedEvent
30256 16 九月 2015 10:54:01 INFO UI [JavaFX Application Thread] - Registered event handler ShowLabelPickerEventHandler
31355 16 九月 2015 10:54:02 INFO BrowserComponent [pool-10-thread-2] - Chrome window not responding.
31356 16 九月 2015 10:54:02 INFO BrowserComponent [pool-10-thread-2] - Relaunching chrome.
31356 16 九月 2015 10:54:02 INFO BrowserComponent [pool-10-thread-2] - Quitting browser component
61776 16 九月 2015 10:54:33 INFO Logic [pool-6-thread-1] - Refreshing 
61779 16 九月 2015 10:54:33 INFO UI [JavaFX Application Thread] - About to trigger event ModelUpdatedEvent
61782 16 九月 2015 10:54:33 INFO UI [JavaFX Application Thread] - Triggered event ModelUpdatedEvent
67881 16 九月 2015 10:54:39 INFO UI [pool-4-thread-1] - About to trigger event UpdateRateLimitsEvent
67882 16 九月 2015 10:54:39 INFO UI [pool-4-thread-1] - Triggered event UpdateRateLimitsEvent
91913 16 九月 2015 10:55:03 INFO UI [JavaFX Application Thread] - About to trigger event PanelClickedEvent
91916 16 九月 2015 10:55:03 INFO UI [JavaFX Application Thread] - Triggered event PanelClickedEvent
95594 16 九月 2015 10:55:07 INFO UI [JavaFX Application Thread] - About to trigger event OpenReposChangedEvent
95595 16 九月 2015 10:55:07 INFO UI [JavaFX Application Thread] - Triggered event OpenReposChangedEvent
96967 16 九月 2015 10:55:08 INFO UI [JavaFX Application Thread] - About to trigger event PanelClickedEvent
96970 16 九月 2015 10:55:08 INFO UI [JavaFX Application Thread] - Triggered event PanelClickedEvent
106784 16 九月 2015 10:55:18 INFO UI [JavaFX Application Thread] - About to trigger event PanelClickedEvent
106787 16 九月 2015 10:55:18 INFO UI [JavaFX Application Thread] - Triggered event PanelClickedEvent
121905 16 九月 2015 10:55:33 INFO Logic [pool-6-thread-1] - Refreshing 
121906 16 九月 2015 10:55:33 INFO UI [JavaFX Application Thread] - About to trigger event ModelUpdatedEvent
121908 16 九月 2015 10:55:33 INFO UI [JavaFX Application Thread] - Triggered event ModelUpdatedEvent
126907 16 九月 2015 10:55:38 INFO UI [pool-4-thread-1] - About to trigger event UpdateRateLimitsEvent
126908 16 九月 2015 10:55:38 INFO UI [pool-4-thread-1] - Triggered event UpdateRateLimitsEvent
151626 16 九月 2015 10:56:03 INFO BrowserComponent [JavaFX Application Thread] - Quitting browser component
913 16 九月 2015 11:38:52 INFO UI [JavaFX Application Thread] - V3.5.1
966 16 九月 2015 11:38:52 INFO KeyboardShortcuts [JavaFX Application Thread] - Loading user specified keyboard shortcuts. 
966 16 九月 2015 11:38:52 INFO KeyboardShortcuts [JavaFX Application Thread] - Assigning <E> to MARK_AS_READ
967 16 九月 2015 11:38:52 INFO KeyboardShortcuts [JavaFX Application Thread] - Assigning <U> to MARK_AS_UNREAD
967 16 九月 2015 11:38:52 INFO KeyboardShortcuts [JavaFX Application Thread] - Assigning <I> to SCROLL_TO_TOP
967 16 九月 2015 11:38:52 INFO KeyboardShortcuts [JavaFX Application Thread] - Assigning <N> to SCROLL_TO_BOTTOM
967 16 九月 2015 11:38:52 INFO KeyboardShortcuts [JavaFX Application Thread] - Assigning <J> to SCROLL_UP
967 16 九月 2015 11:38:52 INFO KeyboardShortcuts [JavaFX Application Thread] - Assigning <K> to SCROLL_DOWN
967 16 九月 2015 11:38:52 INFO KeyboardShortcuts [JavaFX Application Thread] - Assigning <D> to LEFT_PANEL
967 16 九月 2015 11:38:52 INFO KeyboardShortcuts [JavaFX Application Thread] - Assigning <F> to RIGHT_PANEL
968 16 九月 2015 11:38:52 INFO KeyboardShortcuts [JavaFX Application Thread] - Assigning <T> to UP_ISSUE
968 16 九月 2015 11:38:52 INFO KeyboardShortcuts [JavaFX Application Thread] - Assigning <V> to DOWN_ISSUE
1022 16 九月 2015 11:38:52 INFO UI [JavaFX Application Thread] - Registered event handler OpenReposChangedEventHandler
1107 16 九月 2015 11:38:52 INFO UI [JavaFX Application Thread] - Registered event handler UpdateProgressEventHandler
1139 16 九月 2015 11:38:52 INFO UI [JavaFX Application Thread] - Registered event handler IssueSelectedEventHandler
1141 16 九月 2015 11:38:52 INFO UI [JavaFX Application Thread] - Registered event handler PanelClickedEventHandler
1142 16 九月 2015 11:38:52 INFO UI [JavaFX Application Thread] - Registered event handler ShowRenamePanelEventHandler
1148 16 九月 2015 11:38:52 INFO TickingTimer [JavaFX Application Thread] - Started TickingTimer Browser Request Delay Timer
1149 16 九月 2015 11:38:52 INFO UI [JavaFX Application Thread] - Registered event handler IssueSelectedEventHandler
1151 16 九月 2015 11:38:52 INFO UI [JavaFX Application Thread] - Registered event handler IssueCreatedEventHandler
1152 16 九月 2015 11:38:52 INFO UI [JavaFX Application Thread] - Registered event handler LabelCreatedEventHandler
1154 16 九月 2015 11:38:52 INFO UI [JavaFX Application Thread] - Registered event handler MilestoneCreatedEventHandler
1155 16 九月 2015 11:38:52 INFO UI [JavaFX Application Thread] - Registered event handler ModelUpdatedEventHandler
1156 16 九月 2015 11:38:52 INFO UI [JavaFX Application Thread] - Registered event handler UpdateRateLimitsEventHandler
1158 16 九月 2015 11:38:52 INFO UI [JavaFX Application Thread] - Registered event handler ShowErrorDialogEventHandler
1179 16 九月 2015 11:38:52 INFO UI [JavaFX Application Thread] - Registered event handler BoardSavedEventHandler
1181 16 九月 2015 11:38:52 INFO UI [JavaFX Application Thread] - Registered event handler OpenReposChangedEventHandler
2803 16 九月 2015 11:38:54 INFO UI [JavaFX Application Thread] - Registered event handler ClearLogicModelEventHandler
2803 16 九月 2015 11:38:54 INFO UI [JavaFX Application Thread] - About to trigger event ModelUpdatedEvent
2806 16 九月 2015 11:38:54 INFO UI [JavaFX Application Thread] - Triggered event ModelUpdatedEvent
2808 16 九月 2015 11:38:54 INFO TickingTimer [JavaFX Application Thread] - Started TickingTimer Refresh Timer
2809 16 九月 2015 11:38:54 INFO TickingTimer [JavaFX Application Thread] - Started TickingTimer Notification Pane Timer
15134 16 九月 2015 11:39:06 INFO LoginController [pool-9-thread-1] - Logging in as lizan96
18314 16 九月 2015 11:39:09 INFO GitHubSource [pool-4-thread-1] - Logged in to GitHub as lizan96
18355 16 九月 2015 11:39:09 INFO UI [JavaFX Application Thread] - About to trigger event PrimaryRepoChangedEvent
18356 16 九月 2015 11:39:09 INFO UI [JavaFX Application Thread] - Triggered event PrimaryRepoChangedEvent
18357 16 九月 2015 11:39:09 INFO UI [JavaFX Application Thread] - About to trigger event BoardSavedEvent
18358 16 九月 2015 11:39:09 INFO UI [JavaFX Application Thread] - Triggered event BoardSavedEvent
18360 16 九月 2015 11:39:09 INFO BrowserComponent [JavaFX Application Thread] - Using chrome driver binary: chromedriver_2-18
18360 16 九月 2015 11:39:09 INFO BrowserComponent [JavaFX Application Thread] - Located chromedriver_2-18
18362 16 九月 2015 11:39:09 INFO BrowserComponent [JavaFX Application Thread] - Logging in on GitHub...
18556 16 九月 2015 11:39:10 INFO UI [JavaFX Application Thread] - Registered event handler ModelUpdatedEventHandler
18578 16 九月 2015 11:39:10 INFO UI [JavaFX Application Thread] - About to trigger event OpenReposChangedEvent
18579 16 九月 2015 11:39:10 INFO UI [JavaFX Application Thread] - Triggered event OpenReposChangedEvent
18582 16 九月 2015 11:39:10 INFO UI [JavaFX Application Thread] - About to trigger event OpenReposChangedEvent
18583 16 九月 2015 11:39:10 INFO UI [JavaFX Application Thread] - Triggered event OpenReposChangedEvent
18586 16 九月 2015 11:39:10 INFO UI [JavaFX Application Thread] - Registered event handler ShowLabelPickerEventHandler
19778 16 九月 2015 11:39:11 INFO BrowserComponent [pool-10-thread-2] - Chrome window not responding.
19778 16 九月 2015 11:39:11 INFO BrowserComponent [pool-10-thread-2] - Relaunching chrome.
19778 16 九月 2015 11:39:11 INFO BrowserComponent [pool-10-thread-2] - Quitting browser component
20583 16 九月 2015 11:39:12 INFO Logic [pool-4-thread-1] - Opening cs2103aug2015-w10-2j/main
23935 16 九月 2015 11:39:15 INFO UI [pool-4-thread-2] - About to trigger event UpdateProgressEvent
23936 16 九月 2015 11:39:15 INFO UI [pool-4-thread-2] - Triggered event UpdateProgressEvent
23937 16 九月 2015 11:39:15 INFO GitHubRepo [pool-4-thread-2] - cs2103aug2015-w10-2j/main | Loaded 21 issues (21% done)
23938 16 九月 2015 11:39:15 INFO UI [pool-4-thread-2] - About to trigger event UpdateProgressEvent
23938 16 九月 2015 11:39:15 INFO UI [pool-4-thread-2] - Triggered event UpdateProgressEvent
28053 16 九月 2015 11:39:19 INFO DownloadRepoTask [pool-4-thread-2] - cs2103aug2015-w10-2j/main | Downloaded 21 issue(s), 12 label(s), 6 milestone(s), 4 user(s)
28057 16 九月 2015 11:39:19 INFO UpdateService [pool-4-thread-2] - Updating cs2103aug2015-w10-2j/main/issues with ETag null
28058 16 九月 2015 11:39:19 INFO UpdateService [pool-4-thread-5] - Updating cs2103aug2015-w10-2j/main/collaborators with ETag null
28058 16 九月 2015 11:39:19 INFO UpdateService [pool-4-thread-4] - Updating cs2103aug2015-w10-2j/main/milestones with ETag null
28059 16 九月 2015 11:39:19 INFO UpdateService [pool-4-thread-3] - Updating cs2103aug2015-w10-2j/main/labels with ETag null
28059 16 九月 2015 11:39:19 INFO PageHeaderIterator [pool-4-thread-2] - Getting header page -1 for /repos/cs2103aug2015-w10-2j/main/issues
28060 16 九月 2015 11:39:19 INFO PageHeaderIterator [pool-4-thread-5] - Getting header page -1 for /repos/cs2103aug2015-w10-2j/main/collaborators
28060 16 九月 2015 11:39:19 INFO GitHubClientExtended [pool-4-thread-2] - Requesting: HEAD /repos/cs2103aug2015-w10-2j/main/issues?state=all&since=2015-09-16T03%3A39Z&per_page=100&page=1
28060 16 九月 2015 11:39:19 INFO PageHeaderIterator [pool-4-thread-3] - Getting header page -1 for /repos/cs2103aug2015-w10-2j/main/labels
28060 16 九月 2015 11:39:19 INFO GitHubClientExtended [pool-4-thread-5] - Requesting: HEAD /repos/cs2103aug2015-w10-2j/main/collaborators?per_page=100&page=1
28060 16 九月 2015 11:39:19 INFO PageHeaderIterator [pool-4-thread-4] - Getting header page -1 for /repos/cs2103aug2015-w10-2j/main/milestones
28061 16 九月 2015 11:39:19 INFO GitHubClientExtended [pool-4-thread-3] - Requesting: HEAD /repos/cs2103aug2015-w10-2j/main/labels?per_page=100&page=1
28061 16 九月 2015 11:39:19 INFO GitHubClientExtended [pool-4-thread-4] - Requesting: HEAD /repos/cs2103aug2015-w10-2j/main/milestones?state=all&per_page=100&page=1
28364 16 九月 2015 11:39:19 INFO GitHubClientExtended [pool-4-thread-2] - /repos/cs2103aug2015-w10-2j/main/issues responded with 200 OK
30359 16 九月 2015 11:39:21 INFO UpdateService [pool-4-thread-2] - cs2103aug2015-w10-2j/main/issues | page 0: 0 items
30360 16 九月 2015 11:39:21 INFO UpdateService [pool-4-thread-2] - New ETag for cs2103aug2015-w10-2j/main/issues: Optional[22b7d8dbea68cb89101b778edffd9d53]
30642 16 九月 2015 11:39:22 INFO GitHubClientExtended [pool-4-thread-3] - /repos/cs2103aug2015-w10-2j/main/labels responded with 200 OK
30662 16 九月 2015 11:39:22 INFO GitHubClientExtended [pool-4-thread-4] - /repos/cs2103aug2015-w10-2j/main/milestones responded with 200 OK
30676 16 九月 2015 11:39:22 INFO GitHubClientExtended [pool-4-thread-5] - /repos/cs2103aug2015-w10-2j/main/collaborators responded with 200 OK
30935 16 九月 2015 11:39:22 INFO UpdateService [pool-4-thread-3] - cs2103aug2015-w10-2j/main/labels | page 0: 12 items
30935 16 九月 2015 11:39:22 INFO UpdateService [pool-4-thread-3] - New ETag for cs2103aug2015-w10-2j/main/labels: Optional[e366ba44c634ce8c31aa98eae655d660]
30937 16 九月 2015 11:39:22 INFO UpdateLabelsTask [pool-4-thread-3] - cs2103aug2015-w10-2j/main | 12 label(s)) changed: [type.epic, type.story, type.enhancement, type.task, type.bug, status.ongoing, priority.high, priority.medium, priority.low, logic, parser, storage]
30994 16 九月 2015 11:39:22 INFO UpdateService [pool-4-thread-5] - cs2103aug2015-w10-2j/main/collaborators | page 0: 4 items
30995 16 九月 2015 11:39:22 INFO UpdateService [pool-4-thread-5] - New ETag for cs2103aug2015-w10-2j/main/collaborators: Optional[8b6aafae23089f9692c39ea5df52c69b]
30996 16 九月 2015 11:39:22 INFO UpdateUsersTask [pool-4-thread-5] - cs2103aug2015-w10-2j/main | 4 user(s)) changed: [dhpuyen, lizan96, AdamGan, ongzlalan]
32283 16 九月 2015 11:39:23 INFO UpdateService [pool-4-thread-4] - cs2103aug2015-w10-2j/main/milestones | page 0: 6 items
32283 16 九月 2015 11:39:23 INFO UpdateService [pool-4-thread-4] - New ETag for cs2103aug2015-w10-2j/main/milestones: Optional[a98525890101833568348d844c05c6e2]
32284 16 九月 2015 11:39:23 INFO UpdateMilestonesTask [pool-4-thread-4] - cs2103aug2015-w10-2j/main | 6 milestone(s)) changed: [V0.1, V0.2, V0.3, V0.4, V0.5, V0.0]
61943 16 九月 2015 11:39:53 INFO Logic [pool-6-thread-1] - Refreshing 
61947 16 九月 2015 11:39:53 INFO UI [JavaFX Application Thread] - About to trigger event ModelUpdatedEvent
61949 16 九月 2015 11:39:53 INFO UI [JavaFX Application Thread] - Triggered event ModelUpdatedEvent
65601 16 九月 2015 11:39:57 INFO UI [pool-4-thread-4] - About to trigger event UpdateRateLimitsEvent
65603 16 九月 2015 11:39:57 INFO UI [pool-4-thread-4] - Triggered event UpdateRateLimitsEvent
122064 16 九月 2015 11:40:53 INFO Logic [pool-6-thread-1] - Refreshing 
122066 16 九月 2015 11:40:53 INFO UI [JavaFX Application Thread] - About to trigger event ModelUpdatedEvent
122067 16 九月 2015 11:40:53 INFO UI [JavaFX Application Thread] - Triggered event ModelUpdatedEvent
124081 16 九月 2015 11:40:55 INFO UI [pool-4-thread-4] - About to trigger event UpdateRateLimitsEvent
124082 16 九月 2015 11:40:55 INFO UI [pool-4-thread-4] - Triggered event UpdateRateLimitsEvent
182214 16 九月 2015 11:41:53 INFO Logic [pool-6-thread-1] - Refreshing 
182215 16 九月 2015 11:41:53 INFO UI [JavaFX Application Thread] - About to trigger event ModelUpdatedEvent
182216 16 九月 2015 11:41:53 INFO UI [JavaFX Application Thread] - Triggered event ModelUpdatedEvent
184776 16 九月 2015 11:41:56 INFO UI [pool-4-thread-4] - About to trigger event UpdateRateLimitsEvent
184777 16 九月 2015 11:41:56 INFO UI [pool-4-thread-4] - Triggered event UpdateRateLimitsEvent
242346 16 九月 2015 11:42:53 INFO Logic [pool-6-thread-1] - Refreshing 
242347 16 九月 2015 11:42:53 INFO UI [JavaFX Application Thread] - About to trigger event ModelUpdatedEvent
242349 16 九月 2015 11:42:53 INFO UI [JavaFX Application Thread] - Triggered event ModelUpdatedEvent
244432 16 九月 2015 11:42:56 INFO UI [pool-4-thread-4] - About to trigger event UpdateRateLimitsEvent
244433 16 九月 2015 11:42:56 INFO UI [pool-4-thread-4] - Triggered event UpdateRateLimitsEvent
302527 16 九月 2015 11:43:54 INFO Logic [pool-6-thread-1] - Refreshing 
302529 16 九月 2015 11:43:54 INFO UI [JavaFX Application Thread] - About to trigger event ModelUpdatedEvent
302530 16 九月 2015 11:43:54 INFO UI [JavaFX Application Thread] - Triggered event ModelUpdatedEvent
305729 16 九月 2015 11:43:57 INFO UI [pool-4-thread-4] - About to trigger event UpdateRateLimitsEvent
305730 16 九月 2015 11:43:57 INFO UI [pool-4-thread-4] - Triggered event UpdateRateLimitsEvent
362650 16 九月 2015 11:44:54 INFO Logic [pool-6-thread-1] - Refreshing 
362652 16 九月 2015 11:44:54 INFO UI [JavaFX Application Thread] - About to trigger event ModelUpdatedEvent
362653 16 九月 2015 11:44:54 INFO UI [JavaFX Application Thread] - Triggered event ModelUpdatedEvent
364154 16 九月 2015 11:44:55 INFO UI [pool-4-thread-4] - About to trigger event UpdateRateLimitsEvent
364154 16 九月 2015 11:44:55 INFO UI [pool-4-thread-4] - Triggered event UpdateRateLimitsEvent

**Comment by damithc** [comment]
@lizan96 Java version used?

**Comment by ndt93** [comment]
@lizan96 Does the problem persist after you restart the application?

**Comment by lizan96** [comment]
@ndt93 yes. I tried to re-download the application but the problem still exits.

**Comment by damithc** [comment]
I had a look at the `store` folder and it was empty.

**Comment by damithc** [comment]
It was not entirely a Mac issue though, as there were others using the same version of HT on a Mac and did not have this problem.

**Comment by ndt93** [comment]
@lizan96 I'm unable to replicate this at the moment for your repository. What's the location where you install HubTurbo on your Mac?

@damithc If it's not in the store then either it's not downloaded properly (which the log says otherwise) or it's not written to disk properly.

**Comment by lizan96** [comment]
@ndt93 I install HubTurbo in the Downloads folder.

**Comment by ndt93** [comment]
My log is roughly similar but with an extra line:
>WriteTask [pool-5-thread-1] - cs2103aug2015-w10-2j/main | Written to JSON store

So it could be something to do with writing to the cache. We don't have any log deeper into the write task unfortunately. Need someone who is able to replicate this problem to break into/log the cache writing step.

**Comment by ndt93** [comment]
@lizan96 If possible, try leaving HubTurbo opened for a while after you enter the repository. It may takes some times for all issues to be downloaded/updated and written to disk.

**Comment by lizan96** [comment]
@ndt93 I leave it for nearly ten minutes but still doesn't work

**Comment by ndt93** [comment]
@lizan96 Ok, that's a confirmed persistent problem then. We will look into this.

**Comment by damithc** [comment]
Look for places where exceptions are caught and swallowed silently. If a write failed, there should be some exception thrown from somewhere.

**Comment by HansNewbie** [comment]
I tried Chinese in my Mac. Here is the part of the log:
```
28984 16 九月 2015 16:24:40 INFO UpdateService [pool-4-thread-3] - New ETag for HansNewbie/coral-repo/labels: Optional[dd013573bca40b3202ec1f9a61da330d]
28985 16 九月 2015 16:24:40 INFO UpdateLabelsTask [pool-4-thread-3] - HansNewbie/coral-repo | 17 label(s)) changed: [bug, duplicate, enhancement, help wanted, invalid, question, wontfix, Type-Defect, Priority-Medium, auto-migrated, Priority-High, OpSys-All, Type-Enhancement, Priority-Low, Component-UI, OpSys-Linux, Type-Review]
Exception in thread "pool-4-thread-2" java.lang.NullPointerException
30431 16 九月 2015 16:24:41 INFO UpdateService [pool-4-thread-2] - HansNewbie/coral-repo/issues | page 0: 0 items
	at github.update.UpdateService.getUpdatedCheckTime(UpdateService.java:208)
	at backend.github.GitHubRepo.getUpdatedIssues(GitHubRepo.java:89)
30432 16 九月 2015 16:24:41 INFO UpdateService [pool-4-thread-2] - New ETag for HansNewbie/coral-repo/issues: Optional[c4bb5798f7b9145c6334674033d44227]
	at backend.github.UpdateIssuesTask.run(UpdateIssuesTask.java:27)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
35784 16 九月 2015 16:24:46 INFO UI [JavaFX Application Thread] - About to trigger event PanelClickedEvent
35785 16 九月 2015 16:24:46 INFO UI [JavaFX Application Thread] - Triggered event PanelClickedEvent
35974 16 九月 2015 16:24:47 INFO UI [JavaFX Application Thread] - About to trigger event PanelClickedEvent
35980 16 九月 2015 16:24:47 INFO UI [JavaFX Application Thread] - Triggered event PanelClickedEvent
```

Seems that there is a problem in parsing the dates

**Comment by dariusf** [comment]
@lizan96 We've fixed this and it'll be in the next release. Thanks for reporting it! If there are further problems, feel free to open a new issue.
