### ISSUE TITLE
'E' does not jump to next issue

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#979]
'E' is supposed to mark issue as read and go to next issue. That's how it worked before. Today I noticed that it does not go to the next issue.

**Comment by damithc** [comment]
Seems to be a temporary issue. It's working again.

**Comment by rd1992** [comment]
If it doesn't happen anymore can we close this?

**Comment by damithc** [comment]
Still happening occasionally. Looks like it happens if HT is kept open for a long time (e.g. overnight). It goes away after restarting.

**Comment by damithc** [comment]
Closing for now.
