### ISSUE TITLE
Simplify navigation in to and out of issue panels

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#984]
How about this?
To jump to first issue of the panel in focus (from anywhere, even filter box): `Ctrl+Enter`
To jump to filter box of the panel in focus (from anywhere): `Ctrl+F`
To jump to nth issue of the panel in focus (from anywhere, even filter box): `Ctrl+n`

This means we remove the `space,space` shortcut and `ctrl+up/down` shortcut

**Comment by rd1992** [comment]
Personally like the `Ctrl + F`. However is `Ctrl+Enter` needed if we already have a `Ctrl + n`?

**Comment by damithc** [comment]
`Ctrl+enter` is easier to type than `Ctrl+1`. Plus it goes well with `Enter` that is used to apply a filter. We can make `Ctrl+Enter` apply filter and jump to issue list when the cursor is in the filter box
