### ISSUE TITLE
Refreshing the bView at the end of undo-period is disruptive

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#985]
I'm referring to the refresh we do after a label change is effected after the undo-window. Several times I was adding an explanatory comment in the bView when it got reloaded automatically. I don't think we need to refresh the entire page. GitHub pages can pull label changes from the server periodically.
May be we can trigger that behavior ourselves? If not, we can let it run its own course?

**Comment by lejolly** [comment]
ok github seems to update the labels pretty quickly now, will remove the refresh.
