### ISSUE TITLE
Fix quirks with updated-self and updated-others

### ISSUE THREAD

**Issue by dariusf** [HubTurbo/HubTurbo#994]
Currently they do not work when issues don't have metadata: issues need to pass `updated` to get metadata before they will work with the new qualifiers. This should be fixed and tested.

**Comment by damithc** [comment]
I thought this is what is being fixed in the recently closed issue.

**Comment by damithc** [comment]
If I understand correctly, the filter is still broken and not ready for public consumption?

**Comment by dariusf** [comment]
They didn't work at all before the recently-closed issue. Now they work, but you have to use `updated` first/along with them. This issue is about making them work intuitively, so `updated` isn't needed.

I don't think it's ready for public consumption.

**Comment by dariusf** [comment]
This was been subsumed under #1004.
