### ISSUE TITLE
updated-others missing issues

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#997]
![image](https://cloud.githubusercontent.com/assets/1673303/9979160/2dd3bac8-5f8f-11e5-9550-379f209bdd3a.png)

**Comment by dariusf** [comment]
I am working on this. I've implemented #994 and it helps, but there are other bugs.

An important flag was removed without replacement in #924 as well, and I'm trying to figure out how to deal with that.

**Comment by dariusf** [comment]
I don't think this is possible to fix completely by the next milestone. The control flow is difficult to reason about and extend, and I think the best way moving forward would to redesign how the updated filter works in general.

Would it be possible to remove the feature temporarily for the release?

**Comment by damithc** [comment]
Sure, go ahead and remove. We can still support the `updated` filter in the meantime right?

**Comment by dariusf** [comment]
Yup, it won't be affected.

**Comment by acruis** [comment]
I agree, this needs some time to get properly sorted out.
